### ISSUE TITLE
Incorrect highlighting when using backslashes for line continuation in TypeScript

### ISSUE THREAD

**Issue by aeschli** [Microsoft/TypeScript-TmLanguage#104]
_From @fantacytyx on March 1, 2016 12:58_

version 0.10.10-insider

![60ec0fb2ddde6d38feaff57a68db6528](https://cloud.githubusercontent.com/assets/8966236/13427589/0288360a-dff0-11e5-8d35-7483103fa87b.jpg)

[bug demo.zip](https://github.com/Microsoft/vscode/files/152779/bug.demo.zip)

_Copied from original issue: Microsoft/vscode#3583_

**Comment by billti** [comment]
Related to #40?

**Comment by anubmat** [comment]
Yes, this issue is similar to #40 and #5 and was recently fixed.

**Comment by anubmat** [comment]
Duplicate #40, #5
