### ISSUE TITLE
Methods sometimes not colored

### ISSUE THREAD

**Issue by felixfbecker** [Microsoft/TypeScript-TmLanguage#113]
Every method from line 556 is not colored correctly anymore.
![image](https://cloud.githubusercontent.com/assets/10532611/13596428/bd6217b2-e512-11e5-8354-2fc6f3c13a73.png)
![image](https://cloud.githubusercontent.com/assets/10532611/13596436/cccabce0-e512-11e5-95e1-977924368637.png)

source: [phpDebug.ts](https://github.com/felixfbecker/vscode-php-debug/blob/b6e428e46c52040fa97d073313c2f18c8517d7e6/src/phpDebug.ts#L543)

Since VS Code February release

**Comment by felixfbecker** [comment]
Might be related to https://github.com/Microsoft/TypeScript-TmLanguage/issues/112

**Comment by sheetalkamat** [comment]
Fixed by #257
