### ISSUE TITLE
Inconsistent highlighting for parameters and their types

### ISSUE THREAD

**Issue by thorn0** [Microsoft/TypeScript-TmLanguage#115]
vscode 0.10.10

1. On the one hand, class methods and function declarations and expressions are colored in one way, which I think is how it's supposed to look:
![image](https://cloud.githubusercontent.com/assets/94334/13605054/5a08bae0-e54e-11e5-9a40-ad6c4e3a045c.png)

2. On the other hand, arrow functions and object methods get completely different colors, which doesn't make any sense:
![image](https://cloud.githubusercontent.com/assets/94334/13605125/b629fe56-e54e-11e5-8337-67ff0887f6cb.png)

**Comment by felixfbecker** [comment]
Also notice the different colors of brackets and colons

**Comment by sheetalkamat** [comment]
Fixed by #257
