### ISSUE TITLE
Typescript syntax highlighting breaks when method return type has a number in the name

### ISSUE THREAD

**Issue by aeschli** [Microsoft/TypeScript-TmLanguage#125]
_From @bryceg on March 11, 2016 19:17_

When my return type on a method has a number in it, the syntax highlighting breaks for that method.
I'm using 0.10.10

![image](https://cloud.githubusercontent.com/assets/2497408/13712868/cb0f9c26-e77a-11e5-9bb4-e1e639924441.png)

_Copied from original issue: Microsoft/vscode#4030_

**Comment by anubmat** [comment]
Duplicate #80. Closing here.

**Comment by sheetalkamat** [comment]
Fixed by #257
