### ISSUE TITLE
Syntax coloring broken when omitting ';'

### ISSUE THREAD

**Issue by madaz** [Microsoft/TypeScript-TmLanguage#13]
Copied from 
https://github.com/Microsoft/TypeScript-Sublime-Plugin/issues/399
https://github.com/Microsoft/vscode/issues/119

![32746a82-8eb0-11e5-8bb5-2f7ed9110221](https://cloud.githubusercontent.com/assets/1139901/11356692/cb2410b2-92ab-11e5-904b-cbd2179895fb.png)

**Comment by anubmat** [comment]
Doesn't Look like a problem of the tmLanguage grammar anymore.

![image](https://cloud.githubusercontent.com/assets/17298501/13720035/1bdfb6f2-e7b4-11e5-9e42-c43d14d53e96.png)
