### ISSUE TITLE
"namespace" as a property name gets highlighted in JavaScript

### ISSUE THREAD

**Issue by aeschli** [Microsoft/TypeScript-TmLanguage#131]
_From @JamesDonnelly on March 19, 2016 15:50_

- VSCode Version: 0.10.11
- OS Version: Windows 8.1

Steps to Reproduce:

1. Create a new JavaScript file.
2. Enter `foo.namespace`.

The property `namespace` gets highlighted, however I don't believe `namespace` has any meaning in JavaScript.

![image](https://cloud.githubusercontent.com/assets/2203377/13899598/47d56630-edea-11e5-9e4a-6b019e7bfdb1.png)

_Copied from original issue: Microsoft/vscode#4458_

**Comment by aeschli** [comment]
_From @JamesDonnelly on March 20, 2016 0:2_

It seems the word `any` also gets highlighted like this as well.

    foo.any

**Comment by martinbilles** [comment]
Also true for variables named `number` or `string`.
