### ISSUE TITLE
No syntax highlighting in ES6 class definition Symbol.iterator method in JavaScript

### ISSUE THREAD

**Issue by marinabilles** [Microsoft/TypeScript-TmLanguage#134]
In a JavaScript ES6 class definition, if defining a method using the bracket syntax for the method name, such as `[Symbol.iterator]()`, the contents of the method is not syntax hightlighted.
![vscode-class-bracket1](https://cloud.githubusercontent.com/assets/5391834/13981829/bb5e789a-f0e6-11e5-8d57-7809762a973c.png)
In fact, this seems to be a problem with the way the grammar tries to find a "method" name to highlight. If a method call is the first thing inside the bracket method's body, it gets colored according to the rules of methods:
![vscode-class-bracket2](https://cloud.githubusercontent.com/assets/5391834/13981831/bc90c47a-f0e6-11e5-8b8c-4ee786f8769a.png)

**Comment by sheetalkamat** [comment]
Fixed by #257
