### ISSUE TITLE
'switch' not matched as '.keyword.control'

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/TypeScript-TmLanguage#138]
_From @donaldpipowitch on March 24, 2016 21:0_

- VSCode Version: 0.10.11 and recent Insiders version
- OS Version: Mac OS X

Steps to Reproduce:

```
function check(n) {
  switch(n) {
    case 1:
      console.log('one');
      break;
    default:
      console.log('other');
      break;
  }

  if (n === 1) {
    console.log('one');
  } else {
    console.log('other');
  }

  return n;
}

check(1);
```

`case`, `break`, `default`, `if`, `else` and `return` are matched as `.keyword.control`, but not `switch`. Tested with JavaScript and TypeScript.

I'd like to fix this myself, but would need some guidance to find the correct code.

_Copied from original issue: Microsoft/vscode#4659_

**Comment by anubmat** [comment]
It may have not yet been updated in VSCode but the scope of 'switch' is .keyword.control in the most recent TmLanguage repo. Pull request #105.

**Comment by Tyriar** [comment]
Seems fine in master :+1:
