### ISSUE TITLE
JSX file formatting modifies tag contents

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/TypeScript-TmLanguage#140]
_From @THemming on March 28, 2016 11:50_

- VSCode Version: 0.10.11
- OS Version: Max OS 10.11.4

Steps to Reproduce:

1. Create a JSX file with the following contents:
  ```jsx
  import React from 'react';
  
  export default ({message}) => {
      return (
          <li>{message}. Something else.</li>
      )
  }
  ```
2. Format the code (shift-alt-f)

Notice that the space between the full-stop and "Something" gets removed.

Expected:
Text content within JSX tags should not be modified.

_Copied from original issue: Microsoft/vscode#4711_

**Comment by sheetalkamat** [comment]
@zhengbli do you mind looking into this. I think you need to update the indent preferences.

**Comment by mhegazy** [comment]
Should be working correctly in latest drop of TypeSript (TS 2.0.2 or later). VSCode ships with an older version of TypeScript. Please see [Using Newer TypeScript Versions](https://code.visualstudio.com/docs/languages/typescript#_using-newer-typescript-versions) documentation for more details on updating your VSCode to use a different version of TypeScript.
