### ISSUE TITLE
syntax highlighting in sublime seems really wrong

### ISSUE THREAD

**Issue by farfromrefug** [Microsoft/TypeScript-TmLanguage#144]
Hi

I am using the typescript plugin for sublime text 3.
I can see that the the syntax does not colorize as much as the javascript syntax does.
![screen shot 2016-04-16 at 17 42 35](https://cloud.githubusercontent.com/assets/655344/14582060/260fa96c-03fb-11e6-9e7f-54489ed94b2a.png)
As you can see it also has a problem with arrow functions (but i think this one is already known)

Here is how it look with the javascript next syntax
![screen shot 2016-04-16 at 17 43 41](https://cloud.githubusercontent.com/assets/655344/14582065/47a333aa-03fb-11e6-9bce-7c50d2a4c719.png)
Is there any way to change the tmlanguage for ts files without loosing any typescript feature?
Thanks

**Comment by sheetalkamat** [comment]
Fixed by #257
