### ISSUE TITLE
Access modifiers in constructor are not highlighted when using decorators with parameters

### ISSUE THREAD

**Issue by aeschli** [Microsoft/TypeScript-TmLanguage#148]
_From @olostan on April 15, 2016 15:1_

- VSCode Version: 1.0.0

Language: TypeScript

Steps to Reproduce:

1. Add a decorator/annotation that accept parameter(s)
2. Put this annotation on constructor's parameters with "private"/"public" modifiers

![image](https://cloud.githubusercontent.com/assets/459897/14565474/f3bf3a9e-0333-11e6-9469-1cfd42c9db0c.png)

_Copied from original issue: Microsoft/vscode#5349_

**Comment by maxleiko** [comment]
It is the same on class property.

https://github.com/TypeStrong/atom-typescript/issues/934#issuecomment-217045559

**Comment by sheetalkamat** [comment]
Fixed by #257
