### ISSUE TITLE
Wrong colors in d.ts after `::`

### ISSUE THREAD

**Issue by egamma** [Microsoft/TypeScript-TmLanguage#15]
_From @niieani on November 25, 2015 16:44_

This content doesn't get parsed correctly for coloring:
```typescript
export declare const localhostAliases: {
    'localhost': boolean;
    '127.0.0.1': boolean;
    '::1': boolean;
};
```
![screen shot 2015-11-25 at 17 43 39](https://cloud.githubusercontent.com/assets/563469/11403242/1f32ab28-939c-11e5-9a68-09766bafbac6.png)

_Copied from original issue: Microsoft/vscode#635_

**Comment by zhengbli** [comment]
@egamma I have a fix at #25 , can you give it a try? Thanks!

**Comment by egamma** [comment]
@aeschli can you please do the verification for me, you already have the setup.

**Comment by aeschli** [comment]
@zhengbli  Looks good, seems to work!
FYI: To test an updated grammar, put the latest plist content to "C:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\typescript\syntaxes\TypeScript.tmLanguage"

**Comment by zhengbli** [comment]
@aeschli Thanks!
