### ISSUE TITLE
TypeScript syntax highlighting: improve function expressions

### ISSUE THREAD

**Issue by aeschli** [Microsoft/TypeScript-TmLanguage#150]
_From @OliverJAsh on April 20, 2016 18:57_

- VSCode Version: 1.0.0
- OS Version: Mac OS X latest

Steps to Reproduce:

1. Add the following to a TS file: `const foo = (): Model => ({ 'bar': 'baz' })`

Result: the function body expression has no detail.

![image](https://cloud.githubusercontent.com/assets/921609/14686724/02f506c2-0732-11e6-8d97-5432dbec081c.png)

This is true for larger expressions too:

![image](https://cloud.githubusercontent.com/assets/921609/14686734/0bd94320-0732-11e6-92ab-6efdc226942f.png)

_Copied from original issue: Microsoft/vscode#5566_

**Comment by OliverJAsh** [comment]
Any updates on this? It's really annoying

**Comment by sheetalkamat** [comment]
Fixed by #257
