### ISSUE TITLE
JS syntax highlighting with conditionals

### ISSUE THREAD

**Issue by aeschli** [Microsoft/TypeScript-TmLanguage#151]
_From @ralfstx on April 21, 2016 13:35_

- VSCode Version: 0.10.11
- OS Version: Ubuntu 15.10

In JavaScript, the value that follows the colon in a conditional statement is not highlighted. For example, in the following statement, the `null` won't be highlighted.

```
var foo = bar ? true : null;
```

_Copied from original issue: Microsoft/vscode#5608_

**Comment by sheetalkamat** [comment]
Fixed by #257
