### ISSUE TITLE
bad syntax highlight while '+=' in for?

### ISSUE THREAD

**Issue by aeschli** [Microsoft/TypeScript-TmLanguage#152]
_From @zheung on April 22, 2016 7:35_

- VSCode Version:1.0.0
- OS Version:Windows 8

Syntax highlight does not working while use `+=` in `for`.

Code:
```javascript
var node;
for(var i; i< 45;i++) {
	node = 234;

	node.a = 122;
	node.b += 122;
	node.b += '1'+1+'2';
}
```

see gif pls...
![1](https://cloud.githubusercontent.com/assets/894004/14734759/3f0e9ee8-089f-11e6-97d1-79b9220bd0be.gif)

_Copied from original issue: Microsoft/vscode#5642_

**Comment by sheetalkamat** [comment]
Fixed by #257
