### ISSUE TITLE
Highlighting breaks with for() condition in constructor

### ISSUE THREAD

**Issue by FirstTimeInForever** [Microsoft/TypeScript-TmLanguage#158]
![image](https://cloud.githubusercontent.com/assets/7830574/14963693/905d364a-10ad-11e6-8489-5cc6ee42288b.png)
and if I change it to greater
![image](https://cloud.githubusercontent.com/assets/7830574/14963751/c753977a-10ad-11e6-95df-818707116df6.png)

Have this issue in latest atom, ST3 and VS Code.

**Comment by sheetalkamat** [comment]
Fixed by #257
