### ISSUE TITLE
Variable declaration list: only 1st variable colored

### ISSUE THREAD

**Issue by stkb** [Microsoft/TypeScript-TmLanguage#16]
Problem found using vscode v0.10.2
Variables after the first in a list of declarations don't get the special color applied.

<img width="176" alt="declarations" src="https://cloud.githubusercontent.com/assets/6125444/11429577/35d62c54-947a-11e5-8bae-3f9417e4d8e7.png">

Note: Not all themes support this extra color.

**Comment by thorn0** [comment]
VS Code 0.10.10. It works if the declaration is single-line but breaks if it's not: 
![image](https://cloud.githubusercontent.com/assets/94334/13612254/20294972-e56f-11e5-9ed7-9af9fc89d106.png)
