### ISSUE TITLE
Typescript class field types don't have the 'type' class

### ISSUE THREAD

**Issue by aeschli** [Microsoft/TypeScript-TmLanguage#160]
_From @Aarilight on May 4, 2016 6:18_

- VSCode Version: 1.0.0
- OS Version: Windows 10

Steps to Reproduce:

1. ![](http://puu.sh/oFFik/dfd047fab7.png)
2. ![](http://puu.sh/oFFwh/edc55d6ba5.png)

The typescript syntax server doesn't give class field types the `type` class, and the colon and type are not split apart as they are for other types. Because of this, there is not currently a way to style them with other types.

(For reference, this is the scope that I'm using to colour the other locations of types: `type.cover, type.name - variable, type.operator - variable, type.square, type.support`)

_Copied from original issue: Microsoft/vscode#6084_

**Comment by Aarilight** [comment]
Ah, thank you, didn't realise there was a better spot to put this. May try a pull request if I can figure out an easy way to edit the tm plists. (Coming from atom where it's cson--so much prettier haha)

**Comment by sheetalkamat** [comment]
Fixed by #257
