### ISSUE TITLE
syntax highlight of shorthand async functions in object literals

### ISSUE THREAD

**Issue by aeschli** [Microsoft/TypeScript-TmLanguage#163]
_From @hasyee on May 6, 2016 9:59_

- VSCode Version: 1.0.0
- OS Version: Win 10

Steps to Reproduce:

1. Type this `.js` or `.ts` snippet:
```javascript
const o = {
	async f() {
		
	}
};
```
VSCode won't highlight `async` keyword without `function`.
However it works fine:
```javascript
class A {
	async f() {
		
	}
}
```

_Copied from original issue: Microsoft/vscode#6156_

**Comment by sheetalkamat** [comment]
Fixed by #257
