### ISSUE TITLE
syntax highlight of async function & arrow function

### ISSUE THREAD

**Issue by aeschli** [Microsoft/TypeScript-TmLanguage#168]
_From @ikarosu on May 11, 2016 2:51_

- VSCode Version:1.1.0
- OS Version:Windows 10

Steps to Reproduce:

0. creat new a javascript file
1. type`const foo = async () => {}`
2. we can see keyword "async" is not highlight

_Copied from original issue: Microsoft/vscode#6273_

**Comment by sheetalkamat** [comment]
Fixed by #257
