### ISSUE TITLE
JavaScript syntax highlighter mistakes

### ISSUE THREAD

**Issue by aeschli** [Microsoft/TypeScript-TmLanguage#170]
_From @qifeng0748 on May 19, 2016 3:53_

- VSCode Version: 1.1.1
- OS Version: Windows10 x64 10586.318

- This example, wrong.
![image](https://cloud.githubusercontent.com/assets/2580757/15381671/2b0d0cfc-1db4-11e6-941e-4f89ba109ed5.png)

- Remove new, right.
![image](https://cloud.githubusercontent.com/assets/2580757/15381681/433b2e4e-1db4-11e6-8aad-55f7479bccb3.png)

- Add (), right.
![image](https://cloud.githubusercontent.com/assets/2580757/15381764/1f676f4a-1db5-11e6-97bb-5c0d75a13895.png)

_Copied from original issue: Microsoft/vscode#6515_

**Comment by sheetalkamat** [comment]
Fixed by #257
