### ISSUE TITLE
Entire type literal is marked as a type

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript-TmLanguage#173]
Check out the section of the following file:

https://github.com/leebyron/testcheck-js/blob/55074483905139642bdaeca816b2bb725f77cba9/dist/testcheck.d.ts#L113-L418

Right now even comments within the type literal are marked as types.

**Comment by sheetalkamat** [comment]
Closing this as Microsoft/vscode#13046 should fix this.
