### ISSUE TITLE
RegExps inside arrow functions aren't highlighted

### ISSUE THREAD

**Issue by nicolo-ribaudo** [Microsoft/TypeScript-TmLanguage#177]
![arrow-fn-regexp](https://cloud.githubusercontent.com/assets/7000710/15648654/309b44d4-266c-11e6-8cf5-b7d4d5ace1f8.jpg)

The first one is correct, the second is parsed as a division

(Tested in VSCode 1.1.1)

**Comment by sheetalkamat** [comment]
Fixed by #257
