### ISSUE TITLE
Lamba/Arrow function breaks symbol resolution in Sublime Text 3

### ISSUE THREAD

**Issue by OdatNurd** [Microsoft/TypeScript-TmLanguage#183]
I'm not 100% sure that this hasn't been reported already; some bug reports seem to mention some aspect or other of something similar to this, but I'm not sure of the full scope, so I thought I'd throw this out there and you can close as needed if it's out of line.

Using Sublime 3114 (latest version as of this writing) and it appears that the syntax highlighting is wrong for all methods after a lamba method is defined. A side effect of this is that since the methods are no longer flagged with the proper scope, they don't appear in the Go To Symbol panel. The only workaround for that is to place such methods at the end of the class definition (although in this case you still can't jump to them via Go To Symbol.

Here's a contrived example showing a "regular" class on the left and one with a lamba on the right:

![sublime_typescript_problem](https://cloud.githubusercontent.com/assets/13212876/15981018/0b523c20-2f25-11e6-900a-39c44bdfcabc.png)

On the left, method1 has scope:
  * "source.ts meta.block.ts meta.declaration.object.ts meta.object.body.ts meta.method.declaration.ts entity.name.function.ts" 

On the right, it has become:
  * "source.ts meta.block.ts"

I imagine the problem is (among other things since `callback` is not properly assigned the correct scope either) has something to with how the space between methods goes from:

* "source.ts meta.block.ts meta.declaration.object.ts meta.object.body.ts"

to

* "source.ts meta.block.ts"

after the lamba method.

**Comment by sheetalkamat** [comment]
Fixed by #257
