### ISSUE TITLE
A token is not highlighted correctly

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript-TmLanguage#185]
_From @plantain-00 on June 12, 2016 12:53_

**TypeScript Version:** 

1.8.10

**Code**

```ts
const from = 1;
const to = 1;
const of = 1;
const foo = { from, to, of };
```

**Expected behavior:**
The `from` should be highlighted the same as `to`.
**Actual behavior:** 
The `from` should be highlighted the same as `const`.

Can get it from playground and VSCode.

_Copied from original issue: Microsoft/TypeScript#9105_

**Comment by sheetalkamat** [comment]
Fixed by #257
