### ISSUE TITLE
Arrow function parameter syntax highlighting does not work

### ISSUE THREAD

**Issue by aeschli** [Microsoft/TypeScript-TmLanguage#187]
_From @bcmarinacci on June 6, 2016 23:31_

- VSCode Version: 1.2.0
- OS Version: OS X 10.11.5

Regular function parameters are highlighted properly but arrow function parameters are not.

![screen shot 2016-06-06 at 4 16 41 pm](https://cloud.githubusercontent.com/assets/14657580/15841018/d1772760-2c02-11e6-80dd-b7342eb7b950.png)

_Copied from original issue: Microsoft/vscode#7275_

**Comment by sheetalkamat** [comment]
Fixed by #257
