### ISSUE TITLE
Enum names are classified as class names

### ISSUE THREAD

**Issue by sheetalkamat** [Microsoft/TypeScript-TmLanguage#194]
Enum names are classified as entity.name.class.ts instead may be it need to be entity.name.enum.ts 
https://github.com/Microsoft/TypeScript-TmLanguage/blob/master/TypeScript.tmLanguage#L304

**Comment by zhengbli** [comment]
We are using `entity.name.class.ts` for basically all type names, per the suggestions from the VSCode team. Does this cause any issue in highlighting?

**Comment by sheetalkamat** [comment]
Fixed by #257
