### ISSUE TITLE
Organize dependencies

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript-TmLanguage#2]
We need to transition the Sublime repo into depending on this repository. In theory, this is as simple as adding a [submodule](http://www.git-scm.com/book/en/v2/Git-Tools-Submodules) or [subtree](http://blogs.atlassian.com/2013/05/alternatives-to-git-submodule-git-subtree/) (though it sounds like what we want is just a subtree).

One problem is that the Sublime repository currently depends on this repository's top-level files existing  in _its own_ top level. Two solutions are:
1. Using soft links that reference files within this submodule.
2. Introducing a post-clone step that copies files over from this submodule.

I personally am leaning towards option 1.

An open question is whether or not the testing plugin should be merged into this repository. I am leaning towards us doing so. There is no reason our testing infrastructure needs to be private and separate from this repo. Merging the two will reduce friction for contributors and encourage users to write tests.

**Comment by sheetalkamat** [comment]
I think now we have better structure with grammar. All the changes to the yaml files happen in this repo and other repo's should just tmLanguage files
