### ISSUE TITLE
Generic type in interface breaks TSX syntax highlighting

### ISSUE THREAD

**Issue by aeschli** [Microsoft/TypeScript-TmLanguage#202]
_From @tomduncalf on July 5, 2016 14:14_

- VSCode Version: 1.3.0-insider a1293f5056e79c3f0e2cd3e24909f41ff4eef472 (does not affect 1.2.1)
- OS Version: OS X 10.11.3

Steps to Reproduce:

1. Create an interface which has a property of a type which uses a generic in its signature
2. Subsequent code is incorrectly highlighted, presumably due to angle brackets being interpreted as JSX

Example code:

```
interface Test<T> {
    test: T;
}

interface Props {
    prop: Test<T>;
}

class Whatever {
}
```

Actual result:

![image](https://cloud.githubusercontent.com/assets/5458070/16587544/0a56eea4-42c3-11e6-8feb-43f804f2e441.png)

Expected result: `class` should be highlighted properly e.g.

![image](https://cloud.githubusercontent.com/assets/5458070/16587548/1938bede-42c3-11e6-86b3-790dd7cef8c1.png)

_Copied from original issue: Microsoft/vscode#8761_

**Comment by aeschli** [comment]
_From @lediur on July 5, 2016 21:36_

I can reproduce this too. Other Intellisense features (e.g. type inference, info on hover) works, so it seems like just a syntax highlighting bug.

Version: 1.3.0-insider a1293f5
OS: Windows 10 Pro Insider 14379

Here's a gif:

![syntax-highlighting-typescript-generics](https://cloud.githubusercontent.com/assets/1077648/16600793/cf0ce416-42bd-11e6-8d9f-1efdf62ef3bb.gif)

**Comment by aeschli** [comment]
_From @PascalSenn on July 8, 2016 7:1_

**Workaround:** If you put a whitespace between the generic and the angle brackets the syntax should highlight correctly

![image](https://cloud.githubusercontent.com/assets/14233220/16679800/a901d644-44ea-11e6-9e63-eb7c0479dde8.png)

**Comment by aeschli** [comment]
_From @tomduncalf on July 8, 2016 7:14_

Ah thanks @PascalSenn, looks a bit ugly but better than no syntax highlighting!

**Comment by aeschli** [comment]
This has probably to do with https://github.com/Microsoft/TypeScript-TmLanguage/pull/19 which we are currently running of. TS looks good, but TSX shows the issue above.

**Comment by aeschli** [comment]
Also see https://github.com/Microsoft/vscode/issues/8045

**Comment by PascalSenn** [comment]
Probably the same issue as #196

**Comment by aeschli** [comment]
I reverted tsx to the version we had in 1.2 (current master, https://github.com/Microsoft/TypeScript-TmLanguage/commit/a78f05a1af40a3dbc1a87992b37e34e69631c94d). ts and js still use the changes of this pull request #191 which seems to work well.
