### ISSUE TITLE
Entire function is scoped as .token.function.meta.js

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/TypeScript-TmLanguage#208]
For this function:

```js
// An exceptionally useful comment
function func(param) {
	var text = 'string';
	for (var i = 0; i < param.length; i++) {
		text += i;
	}
	return {
		"text": text,
		"boolean": false
	};
}
```

The entire function contents is scoped with `.token.function.meta.js`, meaning if a style exists for this, which it does for several themes, this is what they do:

*Microsoft Predawn theme*
![image](https://cloud.githubusercontent.com/assets/2193314/16856542/7daf7336-49cf-11e6-83ec-fcfb5ab4578e.png)

I believe this is the reason [some people have pointed out](https://twitter.com/modfox/status/751187291515740160) about broken JavaScript text highlighting. Switching to the Atom JavaScript grammar removed the issue as the entire function block is not scoped as such.

/cc @aeschli

**Comment by Tyriar** [comment]
Any movement on this? This is also related to an issue I'm seeing in TS where the parameters are not being scoped correctly when using a converted sublime theme as they have the function scope.

**Comment by aeschli** [comment]
@Tyriar The problem is on our side https://github.com/Microsoft/vscode/issues/3008.
