### ISSUE TITLE
Syntax highlighting sometimes depends on semicolons

### ISSUE THREAD

**Issue by johnchristopherjones** [Microsoft/TypeScript-TmLanguage#217]
TypeScript syntax highlighting sometimes breaks when semicolons are omitted.  Attached are two screenshots from Atom and example code that produces the error.  Presently GitHub syntax highlighting for TypeScript produces the same error.

This issue might be related to #47.  This issue was initially raised as TypeStrong/atom-typescript#966 and referred here.  

Note the highlighting for both the word "statuses" and the string literal "started".

## Without Semicolon:

```TypeScript
export class StatusSelector {
  @Output() select = new EventEmitter()
  statuses = ["started", "completed"]
}
```

![statuses_without_semicolon](https://cloud.githubusercontent.com/assets/865836/15724645/092010dc-2816-11e6-8eb5-cc2a8cb47936.png)

## With Semicolon:
```TypeScript
export class StatusSelector {
  @Output() select = new EventEmitter();
  statuses = ["started", "completed"]
}
```

![statuses_with_semicolon](https://cloud.githubusercontent.com/assets/865836/15724653/0e5518fe-2816-11e6-93b9-dbfdbfe46748.png)

Edit: Revised screenshots

**Comment by sheetalkamat** [comment]
Fixed by #257
