### ISSUE TITLE
[js] syntax highlight goes to wrong by computed properties.

### ISSUE THREAD

**Issue by mysticatea** [Microsoft/TypeScript-TmLanguage#218]
- **VSCode** 1.4.0-insiders (0aa920603e48ad2333722d9ee97257e40ea24d12) and 1.3.1
- **OS** Windows 7

Steps to Reproduce:

1. write a computed property with method shorthand.

![image](https://cloud.githubusercontent.com/assets/1937871/16978478/ff78153c-4e96-11e6-9a14-472fab74dfd4.png)

**Comment by sheetalkamat** [comment]
Fixed by #257
