### ISSUE TITLE
Wrong Syntax highlighting for parameter decorators

### ISSUE THREAD

**Issue by aeschli** [Microsoft/TypeScript-TmLanguage#227]
_From @thomaspink on July 29, 2016 8:1_

- VSCode Version: Version 1.4.0-insider (1.4.0-insider)
- OS Version: MacOS 10.11.5

Steps to Reproduce:

1. Use multiple parameter decorators on your constructor (like Angular's `@Inject`)
2. The first decorator is highlighted different than the others (see screenshot)

![syntaxhighlight-error1](https://cloud.githubusercontent.com/assets/1368032/17241455/0d756662-5572-11e6-9a01-bdec3ed6cbbc.jpg)

_Copied from original issue: Microsoft/vscode#9939_

**Comment by aeschli** [comment]
_From @dominikstrasser on July 29, 2016 11:5_

Same here - this really bugs me :/

**Comment by sheetalkamat** [comment]
Fixed by #257
