### ISSUE TITLE
JavaScript Syntax Highlighting: Ternary object declaration

### ISSUE THREAD

**Issue by aeschli** [Microsoft/TypeScript-TmLanguage#234]
_From @JosephGarrone on August 5, 2016 4:45_

- VSCode Version: 1.4
- OS Version: Windows 10

Steps to Reproduce:

1. Create a new file and set language to JavaScript
2. Paste the following in:
```
class Test {
    let style = type ? {
        color: '#FFF',
        padding: '15px'
    } : {
        overflow: 'hidden',
        height: '0px'
    };
}
```

The resultant highlighting will render as such: 

![image](https://cloud.githubusercontent.com/assets/4310797/17426447/19d1a12e-5b1b-11e6-9b88-58ef584a72a8.png)

IE: No highlighting on second object and also breaks code formatting (Alt + Shift + F).

_Copied from original issue: Microsoft/vscode#10166_

**Comment by sheetalkamat** [comment]
Fixed by #257
