### ISSUE TITLE
Highlighting broken for "/*" '/*' and `/*`

### ISSUE THREAD

**Issue by aeschli** [Microsoft/TypeScript-TmLanguage#235]
_From @DavidSouther on August 7, 2016 15:18_

- VSCode Version: Version 1.4.0 (1.4.0)
- OS Version: OSX 10.11.6 (15G31)

Steps to Reproduce:

1. Insert the string '/*' `/*` or "/*" in a Tyepscript file
2. The rest of the file is highlighted as a comment, to the next */

![screen shot 2016-08-07 at 11 14 18 am](https://cloud.githubusercontent.com/assets/498712/17463294/9b56260e-5c90-11e6-81c3-66194db117da.png)

_Copied from original issue: Microsoft/vscode#10273_

**Comment by aeschli** [comment]
_From @DavidSouther on August 7, 2016 15:18_

Oh hey, it looks like github has the same issue!

**Comment by aeschli** [comment]
I reproduced with the following code snippet:
class A {
    @Route.GET('/*')
    get(q: Request, s: Response): void {
        s.sendFile();
    }
}

**Comment by sheetalkamat** [comment]
Fixed by #257
