### ISSUE TITLE
Color coding of TypeScript is broken when using : in @HostListener eventName

### ISSUE THREAD

**Issue by aeschli** [Microsoft/TypeScript-TmLanguage#238]
_From @jkyoutsey on August 5, 2016 15:35_

- VSCode Version: 1.4.0
- OS Version: Windows 8.1

Color coding of TypeScript is broken when using `:` in `@HostListener` eventName

Steps to Reproduce:
```typescript
    @HostListener("document:click", ["$event"])
    private ...(e) {
        ...
    }
```
![image](https://cloud.githubusercontent.com/assets/3846466/17441725/b08fe49e-5aef-11e6-934b-fd46918e1c7b.png)

_Copied from original issue: Microsoft/vscode#10205_

**Comment by sheetalkamat** [comment]
Fixed by #257
