### ISSUE TITLE
Function returning tuple containing lambda type breaks highlighting

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript-TmLanguage#241]
// Highlights correctly
    function f(): () => number {
        const x = 0;
    }

    // Function header highlights correctly; body does not highlight 'const' but does highlight 'x' and '0'
    function foo(): [number, () => number] {
        const x = 0;
    }

    // Only 'number', 'x', and '0' are highlighted.
    function f(): () => number {
        const x = 0;
    }

Tested in: VSCode, Sublime Text

**Comment by sheetalkamat** [comment]
Fixed by #257
