### ISSUE TITLE
VS fails in code highlighting with many switch/case statements

### ISSUE THREAD

**Issue by aeschli** [Microsoft/TypeScript-TmLanguage#243]
_From @kyssproject on August 10, 2016 9:4_

- VSCode Version: 1.4.0
- OS Version: Windows 10

Steps to Reproduce:

1. Create a file with this content

```
'use strict';

		var pieces = [];
		var numeration = [];

		for (var i in pieces) {
			switch (true) {
				case /^\"?Accession\"?/.test(pieces[i]):
					numeration[0] = i;
					break;
				case /^\"?Accession\"?/.test(pieces[i]):
					numeration[0] = i;
					break;
				case /^\"?Accession\"?/.test(pieces[i]):
					numeration[0] = i;
					break;
				case /^\"?Accession\"?/.test(pieces[i]):
					numeration[0] = i;
					break;
				case /^\"?Accession\"?/.test(pieces[i]):
					numeration[0] = i;
					break;
				case /^\"?Accession\"?/.test(pieces[i]):
					numeration[0] = i;
					break;
				case /^\"?Accession\"?/.test(pieces[i]):
					numeration[0] = i;
					break;
				case /^\"?Accession\"?/.test(pieces[i]):
					numeration[0] = i;
					break;
				case /^\"?Accession\"?/.test(pieces[i]):
					numeration[0] = i;
					break;
				case /^\"?Accession\"?/.test(pieces[i]):
					numeration[0] = i;
					break;
				case /^\"?Accession\"?/.test(pieces[i]):
					numeration[0] = i;
					break;
				case /^\"?Accession\"?/.test(pieces[i]):
					numeration[0] = i;
					break;
				case /^\"?Accession\"?/.test(pieces[i]):
					numeration[0] = i;
					break;
				case /^\"?Accession\"?/.test(pieces[i]):
					numeration[0] = i;
					break;
				case /^\"?Accession\"?/.test(pieces[i]):
					numeration[0] = i;
					break;
				case /^\"?Accession\"?/.test(pieces[i]):
					numeration[0] = i;
					break;
				case /^\"?Accession\"?/.test(pieces[i]):
					numeration[0] = i;
					break;
				case /^\"?Accession\"?/.test(pieces[i]):
					numeration[0] = i;
					break;
				case /^\"?Accession\"?/.test(pieces[i]):
					numeration[0] = i;
					break;
				case /^\"?Accession\"?/.test(pieces[i]):
					numeration[0] = i;
					break;
				case /^\"?Accession\"?/.test(pieces[i]):
					numeration[0] = i;
					break;
				case /^\"?Accession\"?/.test(pieces[i]):
					numeration[0] = i;
					break;
				case /^\"?Accession\"?/.test(pieces[i]):
					numeration[0] = i;
					break;
				case /^\"?Accession\"?/.test(pieces[i]):
					numeration[0] = i;
					break;
				case /^\"?Accession\"?/.test(pieces[i]):
					numeration[0] = i;
					break;
				case /^\"?Accession\"?/.test(pieces[i]):
					numeration[0] = i;
					break;
				case /^\"?Accession\"?/.test(pieces[i]):
					numeration[0] = i;
					break;
				case /^\"?Accession\"?/.test(pieces[i]):
					numeration[0] = i;
					break;
				case /^\"?Accession\"?/.test(pieces[i]):
					numeration[0] = i;
					break;
				case /^\"?Accession\"?/.test(pieces[i]):
					numeration[0] = i;
					break;
				case /^\"?Accession\"?/.test(pieces[i]):
					numeration[0] = i;
					break;
				case /^\"?Accession\"?/.test(pieces[i]):
					numeration[0] = i;
					break;
				case /^\"?Accession\"?/.test(pieces[i]):
					numeration[0] = i;
					break;
			}
		}
```

2. See the colorization in the editor, it stops in line 88 and until the rest of the document.

_Copied from original issue: Microsoft/vscode#10382_

**Comment by aeschli** [comment]
_From @Eggop92 on August 10, 2016 12:15_

This happen to me too, not with switch/cases, just with php open tag, after 88 line, the colorization stop working properly in PHP code.

**Comment by aeschli** [comment]
_From @alexandrudima on August 12, 2016 7:53_

@Eggop92 Please create a separate issue with a php code snippet that shows the problem.

In any case, these types of issues are caused by grammars that forget to pop rule stacks.

**Comment by aeschli** [comment]
The problem I see is that the regular expression in the case statement is not handled right.
![image](https://cloud.githubusercontent.com/assets/6461412/17661740/668eaaac-62e1-11e6-9f88-6651a0ca7a1c.png)

**Comment by kyssproject** [comment]
Sorry I don't know how it works, does it mean it is not an issue of visual code? It doesn't seem related to the particular regex, it seems like it is after a number of regex that the software fails in recognizing the code ...

**Comment by kyssproject** [comment]
I can see that the problem is not only with regex. In my case, it happens when there is the AngularJS declaration. See below:

```
angular.module('meme').factory('whatever',['$window', '$q',function($window, $q) {

		for (var i in pieces) {
			switch (true) {
				case /^\"?Accession\"?/.test(pieces[i]):
				case /^\"?Accession\"?/.test(pieces[i]):
				case /^\"?Accession\"?/.test(pieces[i]):
				case /^\"?Accession\"?/.test(pieces[i]):
				case /^\"?Accession\"?/.test(pieces[i]):
				case /^\"?Accession\"?/.test(pieces[i]):
				case /^\"?Accession\"?/.test(pieces[i]):
				case /^\"?Accession\"?/.test(pieces[i]):
				case /^\"?Accession\"?/.test(pieces[i]):
				case /^\"?Accession\"?/.test(pieces[i]):
				case /^\"?Accession\"?/.test(pieces[i]):
				case /^\"?Accession\"?/.test(pieces[i]):
				case /^\"?Accession\"?/.test(pieces[i]):
				case /^\"?Accession\"?/.test(pieces[i]):
				case /^\"?Accession\"?/.test(pieces[i]):
				case /^\"?Accession\"?/.test(pieces[i]):
				case /^\"?Accession\"?/.test(pieces[i]):
				case /^\"?Accession\"?/.test(pieces[i]):
				case /^\"?Accession\"?/.test(pieces[i]):
				case /^\"?Accession\"?/.test(pieces[i]):
				case /^\"?Accession\"?/.test(pieces[i]):
				case /^\"?Accession\"?/.test(pieces[i]):
					numeration[0] = i;
					break;
				case /^\"?Accession\"?/.test(pieces[i]):
					numeration[1] = i;
					break;
				case /^\"?Accession\"?/.test(pieces[i]):
				case /^\"?Accession\"?/.test(pieces[i]):
				case /^\"?Accession\"?/.test(pieces[i]):
			}
		}
```

And

...

		for (var i in pieces) {
			switch (true) {
				case /^\"?Accession\"?/.test(pieces[i]):
				case /^\"?Accession\"?/.test(pieces[i]):
				case /^\"?Accession\"?/.test(pieces[i]):
				case /^\"?Accession\"?/.test(pieces[i]):
				case /^\"?Accession\"?/.test(pieces[i]):
				case /^\"?Accession\"?/.test(pieces[i]):
				case /^\"?Accession\"?/.test(pieces[i]):
				case /^\"?Accession\"?/.test(pieces[i]):
				case /^\"?Accession\"?/.test(pieces[i]):
				case /^\"?Accession\"?/.test(pieces[i]):
				case /^\"?Accession\"?/.test(pieces[i]):
				case /^\"?Accession\"?/.test(pieces[i]):
				case /^\"?Accession\"?/.test(pieces[i]):
				case /^\"?Accession\"?/.test(pieces[i]):
				case /^\"?Accession\"?/.test(pieces[i]):
				case /^\"?Accession\"?/.test(pieces[i]):
				case /^\"?Accession\"?/.test(pieces[i]):
				case /^\"?Accession\"?/.test(pieces[i]):
				case /^\"?Accession\"?/.test(pieces[i]):
				case /^\"?Accession\"?/.test(pieces[i]):
				case /^\"?Accession\"?/.test(pieces[i]):
				case /^\"?Accession\"?/.test(pieces[i]):
					numeration[0] = i;
					break;
				case /^\"?Accession\"?/.test(pieces[i]):
					numeration[1] = i;
					break;
				case /^\"?Accession\"?/.test(pieces[i]):
				case /^\"?Accession\"?/.test(pieces[i]):
				case /^\"?Accession\"?/.test(pieces[i]):
			}
		}
...


The second case works as expected. The first case breaks the highlighting after case number 23

![capture](https://cloud.githubusercontent.com/assets/4474004/18341461/5b0ff4ac-75aa-11e6-8aaf-ee2491fabf05.PNG)

![capture2](https://cloud.githubusercontent.com/assets/4474004/18341465/5ed19d3e-75aa-11e6-81ca-21b5a22b9c52.PNG)

@aeschli , is this closed? does it mean this is not going to be solved?

**Comment by kyssproject** [comment]
Ah no sorry, I saw the Closed icon from the vscode, but here it remains open, nevermind

**Comment by kyssproject** [comment]
With the last update the highlighting issue seems to be solved(?), in my code it looks like this, so this item could be closed I suppose
