### ISSUE TITLE
Method named `switch` is colorized like keyword.

### ISSUE THREAD

**Issue by vagarenko** [Microsoft/TypeScript-TmLanguage#244]
Method named `switch` is colorized like keyword.
It also breaks colorization of the further code until `{` character.
![untitled](https://cloud.githubusercontent.com/assets/1395677/17697280/4c0a59e6-63cd-11e6-999a-0d98ed5164de.png)

tsc Version 1.8.10

**Comment by sheetalkamat** [comment]
Fixed by #257
