### ISSUE TITLE
'describe' and 'it' from Mocha/Jasmine are not highlighted.

### ISSUE THREAD

**Issue by kylelamse** [Microsoft/TypeScript-TmLanguage#245]
## example.spec.ts
```typescript
describe('test', () => {
  it('should', () => {
    // do things
  });
});
```

Shouldn't keywords from this style of unit tests be supported in the grammar?  Or is this by design not included?  [atom-typescript](https://github.com/TypeStrong/atom-typescript) uses the grammar in this repo, and I'm not getting `describe` or `it` highlighting in my unit tests, so that's why I posted the issue here.

I get this highlighting in my *.spec.js files in atom, but not for any *.spec.ts files using the plugin referenced earlier.  I would like to know if this is an issue with this grammar or if it's completely unrelated.

**Comment by sheetalkamat** [comment]
Fixed with #270
