### ISSUE TITLE
Agrs and types highlighting works for runction but doesn't for arrow function

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/TypeScript-TmLanguage#249]
Moved from https://github.com/Microsoft/vscode/issues/10677#issuecomment-241277679

---

From @whitecolor

```typescript

const selectDictionary = (dictionaries: StoredDictionaries, lang:string) => {

}

function selectDictionary(dictionaries: StoredDictionaries, lang:string) {

}
```

![image](https://cloud.githubusercontent.com/assets/736697/17839469/402cfd98-6802-11e6-93dd-37cd8d243d31.png)

**Comment by sheetalkamat** [comment]
Fixed by #257
