### ISSUE TITLE
Syntax highlighting breaks with multi-property objects within ternary operators 

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/TypeScript-TmLanguage#259]
Running in vscode v1.6.0-insider @ 20c3935a130f5b86d629a8543c9c71348c54c3de

TypeScript code:

```
let test = true ? { foo: 1, bar: 2 } : false
```

Results in: 

![image](https://cloud.githubusercontent.com/assets/2193314/18412837/9c2b9064-774d-11e6-9272-c7a5db5a9dc1.png)

- `bar` should be colored the same as `foo`
- `false` should be colored the same as `true`
- `2` should be colored the same as `1`

Scopes:

![image](https://cloud.githubusercontent.com/assets/2193314/18412840/bbda3bc2-774d-11e6-8808-f730d118a197.png)

**Comment by sheetalkamat** [comment]
This seems fixed with updated grammar by #257
