### ISSUE TITLE
Expressions in backtick strings are not colorized

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/TypeScript-TmLanguage#266]
Using https://github.com/Microsoft/TypeScript-TmLanguage/commit/3e0e15ee6c2a85d9693f8ec430c43af12f6dbdcd packages as an extension for VS Code.

I see the following:

![screen shot 2016-09-20 at 3 26 32 pm](https://cloud.githubusercontent.com/assets/4674940/18691157/fcdeb778-7f46-11e6-9231-dfd9f192beb1.png)

**Comment by sheetalkamat** [comment]
Fixed with #270
