### ISSUE TITLE
Typescript - do not color colon :

### ISSUE THREAD

**Issue by aeschli** [Microsoft/TypeScript-TmLanguage#27]
_From @isidorn on December 14, 2015 15:33_

Colons should not be colored blue, they should remain black.

<img width="311" alt="screen shot 2015-12-14 at 16 32 34" src="https://cloud.githubusercontent.com/assets/1926584/11785103/58431db0-a280-11e5-9dee-6026f2ef1649.png">

_Copied from original issue: Microsoft/vscode#1291_

**Comment by aeschli** [comment]
_From @mohsen1 on December 14, 2015 22:8_

Is this the right regex for this? https://github.com/Microsoft/vscode/blob/master/extensions/typescript/syntaxes/TypeScript.tmLanguage#L1067

**Comment by aeschli** [comment]
This is a problem of the grammar.
`:` get scope `token annotation body declaration function meta method object parameter type ts`

**Comment by anubmat** [comment]
![image](https://cloud.githubusercontent.com/assets/17298501/17232573/ff512f24-54dd-11e6-9f58-9eccb120078f.png)
I don't think this is a problem anymore. So closing.
