### ISSUE TITLE
TypeScript different colorization between VS and VSCode

### ISSUE THREAD

**Issue by nippur72** [Microsoft/TypeScript-TmLanguage#271]
VS code does not colorize certain keywords that are instead colorized in Visual Studio:

![colorize](https://cloud.githubusercontent.com/assets/2598443/18842094/31835d9a-8414-11e6-93ae-c4e27b79f3e2.png)

**Comment by mhegazy** [comment]
VSCode uses this tm language to colorize, VS uses the tree to drive colorization. so the systems are different and i would expect there to be differences in the result.

We are moving the next version of VS to use the same colorization model, and thus should share the same files with VSCode, Sublimtext, atom, etc..  so this should be addressed in the next version of VS.

**Comment by nippur72** [comment]
ok, thanks for the clarification, but since it's the VSCode model to be incorrect, would it be helpful to leave this issue open? (changing its title perhaps).

**Comment by mhegazy** [comment]
Should be fixed in VSCode with https://github.com/Microsoft/TypeScript-TmLanguage/pull/257.
