### ISSUE TITLE
Javascript highlighting vanished completely with the Latest TypeScript Javascript grammar plugin

### ISSUE THREAD

**Issue by sheetalkamat** [Microsoft/TypeScript-TmLanguage#279]
From issue #273 reported by @Jmclerck

My syntax highlighting for JavaScript vanished completely after installing this plugin, my Color Theme is set to `Dark+ (default dark)`, previously it looked like this:

![screen shot 2016-09-29 at 09 05 21 3](https://cloud.githubusercontent.com/assets/1395919/18945894/6f067924-8624-11e6-8910-c4ec0a86655f.png)

After installing this plugin in everything was white:

![screen shot 2016-09-29 at 09 05 00 3](https://cloud.githubusercontent.com/assets/1395919/18946009/eeb66814-8624-11e6-8d75-e15cb3062e42.png)

I notice now that this repo only mentions TypeScript but the [tweet](https://twitter.com/code/status/781198942578941953) here suggested JavaScript improvements too, either way, if this is only TypeScript it shouldn't really cause issues with other languages?

**Comment by sheetalkamat** [comment]
@Jmclerck Can you please provide more information of other extensions installed, vscode version etc so we can investigate this further? I am going to move your issue into separate one just to make sure we are tracking it correctly.

**Comment by nickytonline** [comment]
@sheetalkamat, I have the same issue.

OS: Ubuntu 16.04
VS Code:
- Version 1.5.3
- Commit 5be4091987a98e3870d89d630eb87be6d9bafd27
- Date 2016-09-22T08:40:08.699Z
- Shell 0.37.6
- Renderer 49.0.2623.75
- Node 5.10.0

It appears that it's not able to find the grammar files based on this error in the developer tools in VS Code.

```
shell.ts:428Unknown location for grammar <source.js>: Error: Unknown location for grammar <source.js>
    at Registry.loadGrammar (/usr/share/code/resources/app/node_modules/vscode-textmate/release/main.js:1564:30)
    at e.registerDefinition (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:119:27883)
    at file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:119:27755
    at e.invoke (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:35:665)
    at e.fire (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:35:2843)
    at file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:65:3675
    at n.Class.define.then (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:30:19707)
    at t.e._getOrCreateMode (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:65:3574)
    at file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:65:3203
    at n.Class.define.then (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:30:19707)
```

**Comment by Jmclerck** [comment]
Hi @sheetalkamat the plugins I have installed currently are:

- EditorConfig for VS Code @ `0.3.3`
- Beautify @ `0.2.1`
- Wallaby.js @ `1.0.27`
- TSLint @ `0.5.39`
- Debugger for Chrome @ `0.5.2`
- Debugger for iOS Web @ `0.1.2`
- linter-xo @ `2.1.0`
- Spelling and Grammar Checker @ `0.8.6`

My version of VS Code is `1.5.3`.

Please let me know if you need anything else and thanks for your help!

**Comment by sheetalkamat** [comment]
This has been fixed by @kieferrm and should be available in next version of extension. Thank you.
