### ISSUE TITLE
Latest TypeScript and Javascript Grammar: Code between brackets in Typescript React is colored as plain text

### ISSUE THREAD

**Issue by emzero** [Microsoft/TypeScript-TmLanguage#280]
Version 1.5.3
Commit 5be4091987a98e3870d89d630eb87be6d9bafd27
Date 2016-09-22T08:50:42.185Z
Shell 0.37.6
Renderer 49.0.2623.75
Node 5.10.0
Windows 7 SP1 x64

Using the [Latest TypeScript and Javascript Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) does provide better Typescript syntax coloring but code between `{ }` in Typescript React is being colored as plain text.

Here's a screenshot using the default dark+ theme.

![image](https://cloud.githubusercontent.com/assets/412489/18976838/a231a5b4-868b-11e6-9696-92f980332ef1.png)

**Comment by sheetalkamat** [comment]
This needs changes in theme settings too and hence the bug Microsoft/vscode#13167
