### ISSUE TITLE
Latest TypeScript and Javascript Grammar: Some functions are not being colored

### ISSUE THREAD

**Issue by emzero** [Microsoft/TypeScript-TmLanguage#281]
VS Code
Version 1.5.3
Commit 5be4091987a98e3870d89d630eb87be6d9bafd27
Date 2016-09-22T08:50:42.185Z
Shell 0.37.6
Renderer 49.0.2623.75
Node 5.10.0

Latest TypeScript and Javascript Grammar 0.0.2

Windows 7 SP1 x64

Using the default dark+ theme I believe functions are supposed to be yellowish but some are not properly colored as shown in the next screenshot.

![image](https://cloud.githubusercontent.com/assets/412489/18976953/991fe69c-868c-11e6-95dd-cee498202ad1.png)

**Comment by sheetalkamat** [comment]
Thank you for reporting this. 

The functions mentioned here are scoped as ```support``` functions and vscode needs to update the theme to make sure they get colored correctly. There is already bug tracking for it as Microsoft/vscode#13032 

Because this isn't issue with the grammar closing this bug here.
