### ISSUE TITLE
Latest TypeScript and Javascript Grammar: Distinguish between local variables from object properties?

### ISSUE THREAD

**Issue by emzero** [Microsoft/TypeScript-TmLanguage#282]
VS Code
Version 1.5.3
Commit 5be4091987a98e3870d89d630eb87be6d9bafd27
Date 2016-09-22T08:50:42.185Z
Shell 0.37.6
Renderer 49.0.2623.75
Node 5.10.0

Latest TypeScript and Javascript Grammar 0.0.2

Windows 7 SP1 x64

Is it possible to have different colors for local variables and object properties?

Using the Latest TypeScript and Javascript Grammar it seems that some themes are able to do this but not the default ones. Not sure if it's something related to the themes or to the TmLanguage.

Default Dark+
![image](https://cloud.githubusercontent.com/assets/412489/18977251/fed24e06-868e-11e6-98f9-d45f2de71041.png)

Monokai Dimmed
![image](https://cloud.githubusercontent.com/assets/412489/18977259/1889cf18-868f-11e6-9aba-e00633b2c768.png)

**Comment by sheetalkamat** [comment]
Thank you for reporting this. We already scope those things differently and theme can make use of it. I am moving this suggestion to vscode repo as Microsoft/vscode#13092  to see what they want to do with the Dark+ and other default themes.
