### ISSUE TITLE
[javascript][highlighting] Parsing error on non latin characters

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/TypeScript-TmLanguage#288]
From @buzzzzer in https://github.com/Microsoft/vscode/issues/13147

- VSCode Version: 1.5.3
- OS Version: Win 10

Steps to Reproduce:

1. Create new file
2. switch to javascript language syntax
3. Paste that:
```javascript
const somevargood = `somevar1`;

const абв_badvar = `somevar2`;

var  абв_badvar = `somevar3`;
const somevar = `somevar2`;
if( some ) then execfunc();
```
![image](https://cloud.githubusercontent.com/assets/1981785/19029816/1f3ccdf4-8952-11e6-990d-09d7107ec36c.png)

**Comment by sheetalkamat** [comment]
This does not repro with the latest extension from https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar

**Comment by sheetalkamat** [comment]
![nonlatinchars](https://cloud.githubusercontent.com/assets/8052792/19048606/eab1ec72-895b-11e6-8c4f-f01de844b10e.JPG)
