### ISSUE TITLE
Yield keyword is not coloured in JavaScript

### ISSUE THREAD

**Issue by aeschli** [Microsoft/TypeScript-TmLanguage#29]
_From @joaomoreno on December 14, 2015 13:52_

![image](https://cloud.githubusercontent.com/assets/22350/11782623/458b351c-a272-11e5-8bf2-ca1dc66c6560.png)

_Copied from original issue: Microsoft/vscode#1269_

**Comment by aeschli** [comment]
@joaomoreno Please always paste the code snippet as well...

**Comment by aeschli** [comment]
It's a problem of the grammar

**Comment by aeschli** [comment]
_From @joaomoreno on December 15, 2015 10:49_

Sorry!

```javascript
yield
```

:+1:

**Comment by aeschli** [comment]
_From @bpasero on December 15, 2015 10:58_

I think that is not the full snippet from the screenshot...

**Comment by zhengbli** [comment]
Fixed by #117
