### ISSUE TITLE
Typescript code coloring

### ISSUE THREAD

**Issue by denkomanceski** [Microsoft/TypeScript-TmLanguage#290]
I am comparing VSCode code highlighting on classes with WebStorm.. I am using the Dark+ theme which provides more colors and there are some major differences. Here is an example
1. This is webstorm: http://prntscr.com/cpx9ch 
2. This is VSCode http://prntscr.com/cpx9k9

I underlined the problems. I am able to navigate to these classes without problems but why in VSCode they are not in the proper color?
Do I have to add any additional configuration to VSCode to be able to see these?

**Comment by sheetalkamat** [comment]
@denkomanceski these should be better in the latest grammar and it is available through vscode extension at: https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar

Please open the bug if you find something wrong or needing improvement. Also please attach the code you are trying in that bug so we could easily investigate it. Thank you so much.

**Comment by denkomanceski** [comment]
This solves the problem. Thank you !
