### ISSUE TITLE
Javascript spread operator from function

### ISSUE THREAD

**Issue by dustinsanders** [Microsoft/TypeScript-TmLanguage#291]
I have found a highlighting issue using this plugin, and have tested with multiple themes. Attached is screenshot with Monokai Theme.

![screen shot 2016-10-06 at 11 03 40 am](https://cloud.githubusercontent.com/assets/15836012/19160339/1c1988be-8bb5-11e6-8692-f128e16d4cf2.png)

As you can see the first letter is a different color from the rest of the function name.

**Comment by mhegazy** [comment]
though object spread and rest are not supported by the tools, we should support this in the TM grammar.
