### ISSUE TITLE
[Symbol.iterator] Syntax highlighting

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript-TmLanguage#299]
_From @TheColorRed on October 10, 2016 1:7_

Version: 2.0.3

When using `[Symbol.iterator](){}` Syntax highlighting breaks.

Before:

![iterator-1](https://cloud.githubusercontent.com/assets/1571806/19225162/ce93952c-8e5b-11e6-8a12-d1457c7265df.png)

After:

![iterator-2](https://cloud.githubusercontent.com/assets/1571806/19225161/ce917a44-8e5b-11e6-944c-0f42af89f0ef.png)

_Copied from original issue: Microsoft/TypeScript#11474_

**Comment by mhegazy** [comment]
_From @aluanhaddad on October 10, 2016 3:47_

I am seeing this for all computed method names as well as for computed `get` and `set` accessor names within a class body.

**Comment by mhegazy** [comment]
_From @basarat on October 10, 2016 5:22_

Probably belongs here : https://github.com/Microsoft/TypeScript-TmLanguage :rose:

**Comment by sheetalkamat** [comment]
@TheColorRed  this should be fixed in latest grammar as part of #257 
You could try it out by installing [vscode extension ](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar)
