### ISSUE TITLE
Regular expression after `/* comment */` is not highlighted in TypeScript

### ISSUE THREAD

**Issue by zhengbli** [Microsoft/TypeScript-TmLanguage#3]
Importing https://github.com/Microsoft/TypeScript-Sublime-Plugin/issues/391

Issue example: 
```ts
let regex = /**/ /foo/;
```

**Comment by dna2github** [comment]
VSCode Version: `1.32.2`
OS Version: `MacOSX 10.12.6`

the problem still exists after @sheetalkamat closed #717 in 06d49b5 on Feb 7
