### ISSUE TITLE
Generator functions are incorrectly coloured in JavaScript

### ISSUE THREAD

**Issue by aeschli** [Microsoft/TypeScript-TmLanguage#30]
_From @joaomoreno on December 14, 2015 13:50_

![image](https://cloud.githubusercontent.com/assets/22350/11782574/00de555c-a272-11e5-96f2-24182e481c08.png)

_Copied from original issue: Microsoft/vscode#1268_

**Comment by joaomoreno** [comment]
```javascript
function foo() {}
function *bar() {}
```

**Comment by sheetalkamat** [comment]
Fixed by #257
