### ISSUE TITLE
References to `this` are not colored same way.

### ISSUE THREAD

**Issue by drulia** [Microsoft/TypeScript-TmLanguage#303]
Hey, I'm not sure if this is intended behavior or a glitch, but currently any theme that applies different coloring to `this` is not doing same for it's references, i.e. 
```javascript
let self = this;
```
would result in `self` being colored in the same way as any other variable.

The expected behavior would be to have `self` colored same way as `this`.

![this_coloring_comparison](https://cloud.githubusercontent.com/assets/1646365/19256039/090a919a-8f6c-11e6-9807-0ed55fbfb3fa.png)

**Comment by sheetalkamat** [comment]
This is not a grammar issue. This is theme issue. 
``` typescript
let self = this;
self.outletID = outletID;
```

```self``` in declaration is scoped as ```variable.other.readwrite```, ```this``` is scoped as ```variable.language.this```.
```self``` in assignment is scoped as ```variable.other.object```
