### ISSUE TITLE
Multi-line object destructuring in class method breaks syntax highlighting

### ISSUE THREAD

**Issue by vasek17** [Microsoft/TypeScript-TmLanguage#307]
VSCode Version: 1.6.0
OS Version: macOS 10.12

Related: #219 

When using object destructuring, a newline right after opening curly bracket breaks syntax highlighting. I am using [Latest TypeScript and Javascript grammar](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar).

It works with space after opening curly bracket:
![screen shot 2016-10-11 at 13 35 44](https://cloud.githubusercontent.com/assets/1569342/19268918/af123bf6-8fb7-11e6-9458-92beb223b52b.png)

but breaks when the space is not there:
![screen shot 2016-10-11 at 13 35 35](https://cloud.githubusercontent.com/assets/1569342/19268917/af018f22-8fb7-11e6-8446-95d51a3b2267.png)

**Comment by vasek17** [comment]
Sorry, closed by accident, reopening.

**Comment by mhegazy** [comment]
what version of https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar are you using?

**Comment by sheetalkamat** [comment]
Which version of extension are you using. Using latest version I cant repro this. 

![colors](https://cloud.githubusercontent.com/assets/8052792/19281287/7177f8f8-8f9e-11e6-88c6-0fa526a1048f.JPG)

Can you try out latest version of extension. If you still see the issue, could you please paste complete file code to see if there is anything else involved?

**Comment by vasek17** [comment]
Hi, I've installed it today, so it should be the current one (0.0.4).





On Tue, Oct 11, 2016 at 6:54 PM +0200, "Mohamed Hegazy" <notifications@github.com> wrote:





what version of https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar are you using?

**Comment by vasek17** [comment]
The minimal example of code that breaks:

```typescript 
const { a: 'hello' } = obj;
const {
  a,
} = obj;
// broken highlight
const x = 'world';
```

**Comment by sheetalkamat** [comment]
Hmm still doesn't repro: 
![capture](https://cloud.githubusercontent.com/assets/8052792/19281619/eada9114-8f9f-11e6-90d1-f3707ed1953b.JPG)

**Comment by sheetalkamat** [comment]
Do you have any other extensions installed, may be they are interacting with the grammar incorrectly?

**Comment by vasek17** [comment]
I'm sorry, was writing in a hurry. The previous code is wrong and the highlight is correct as on your screenshot.

Now I tried to look into it more and here's the correct minimal example of broken highlight:
```typescript
class Test {
  method() {
    const obj = { a: 'hello' };
    const {
      a
    } = obj;
    const x = 'world';
  }
}
```
(the highlight is broken even in github preview)

It works with a space after the opening curly brace:
![screen shot 2016-10-12 at 14 46 45](https://cloud.githubusercontent.com/assets/1569342/19310523/c82c8370-908a-11e6-8c99-0a3b469b1109.png)

But breaks if the trailing space is deleted:
![screen shot 2016-10-12 at 14 46 53](https://cloud.githubusercontent.com/assets/1569342/19310524/c82e78c4-908a-11e6-98a1-12a82f7a71a1.png)

It is broken even if I uninstall all extensions.

**Comment by sheetalkamat** [comment]
@vasek17  thank you for the repro. I am looking into it.

**Comment by vasek17** [comment]
Works nicely, thank you for the quick fix!
