### ISSUE TITLE
Wrapping cases of switch statement in brackets breaks the highlighter.

### ISSUE THREAD

**Issue by dcbrwn** [Microsoft/TypeScript-TmLanguage#308]
![image](https://cloud.githubusercontent.com/assets/12214069/19277082/2efbe79e-8fe1-11e6-8512-cef727ea35e9.png)

**Comment by sheetalkamat** [comment]
This is duplicate of #294  and fixed by #296

**Comment by dcbrwn** [comment]
Thanks
