### ISSUE TITLE
extends or implements not colored correctly when both are used at the same time

### ISSUE THREAD

**Issue by takumif** [Microsoft/TypeScript-TmLanguage#31]
![screen shot 2015-12-17 at 5 10 41 pm](https://cloud.githubusercontent.com/assets/5505433/11883760/0fc469da-a4e3-11e5-902f-84d815079f6d.png)

When `extends` and `implements` are used at the same time, the second one gets highlighted incorrectly with the color assigned to class names. In the above example `implements` should be blue instead of green.

**Comment by zhengbli** [comment]
The same with #38 .
