### ISSUE TITLE
[Visual Studio Code] es2015 Template `${}` syntax highlighting

### ISSUE THREAD

**Issue by BobChao87** [Microsoft/TypeScript-TmLanguage#311]
The PREVIEW version of the built-in TypeScript and JavaScript grammer highlighter in VS Code (extension package `ms-vscode.typescript-javascript-grammar`) no longer highlights interpolated variables in es2015 templates differently than the surrounding string.

Currently, without the extension, the code inside of template literals is highlighted as usual JavaScript code. Adding the new extension removes all highlighting making the template simply "string colored".

Current highlighting WITHOUT extension.
![without_extension](https://cloud.githubusercontent.com/assets/17022048/19286352/359cdd4e-8fb2-11e6-988e-04063998bcee.png)

PREVIEW highlighting WITH extension.
![with_extension](https://cloud.githubusercontent.com/assets/17022048/19286353/35a4045c-8fb2-11e6-9e25-5ccbaa10f100.png)

This might be related to #253. At the very least, that issue shows that this is indeed an issue and not an intended feature.

**Comment by sheetalkamat** [comment]
Its the issue with the theme and is tracked with Microsoft/vscode#13166
