### ISSUE TITLE
JSX/ES6 Wrong coloring of variables in JavaScript block between HTML-Elements

### ISSUE THREAD

**Issue by codeart1st** [Microsoft/TypeScript-TmLanguage#313]
![coloring](https://cloud.githubusercontent.com/assets/581407/19310930/b9d26d56-908c-11e6-8ea9-31d99180e797.png)

I think this.test should be get the same coloring as above. In the next snippet there is the same behavior and also the local variable e has missing coloring.

![coloring01](https://cloud.githubusercontent.com/assets/581407/19311007/f203a15e-908c-11e6-9e9d-6f3d0831e71d.png)

**Comment by sheetalkamat** [comment]
This is duplicate of #280  and is issue with the theme and is tracked by Microsoft/vscode#13167
