### ISSUE TITLE
Multi-line destructuring within a method still breaks highlight

### ISSUE THREAD

**Issue by vilic** [Microsoft/TypeScript-TmLanguage#315]
**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:**  0.0.4
**Code**

```ts
export class Foo {
    execute() {
        let {
            a
        } = {};

        let b;
    }
}
```

**Comment by sheetalkamat** [comment]
Duplicate of #307 and would be available in next version of the [TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar)
