### ISSUE TITLE
Better String Interpolation Highlighting

### ISSUE THREAD

**Issue by dustinsanders** [Microsoft/TypeScript-TmLanguage#317]
**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:**  0.4 / latest

**Code**

```ts
console.log(`Running a server at http://localhost:${port}${baseUrl}`)
```

<img width="744" alt="screen shot 2016-10-14 at 9 50 55 am" src="https://cloud.githubusercontent.com/assets/15836012/19391979/772ac962-91f4-11e6-9a67-53be45b89d21.png">

It would be better if the `$` and `{` were different colors than the string and variable

**Comment by sheetalkamat** [comment]
This is tracked by Microsoft/vscode#13166 and something vscode theme needs to handle.
