### ISSUE TITLE
ES6 coloring issues: import, constructor

### ISSUE THREAD

**Issue by egamma** [Microsoft/TypeScript-TmLanguage#32]
Extracted from Microsoft/vscode#1470 reported by @MacKentoch

Got same issues with **javascript ES6**.
As examples
 -  `import` (was red before) is now just grey
 -  `constructor` is now grey

*Occurs in  `OSX El capitan` and `windows 10`.*

Jsx seems not that much impacted (but still improvements to be done).

**Comment by MacKentoch** [comment]
@egamma @adnan333bd I confirm : 

**Big thanks!**

for 
- fast reply
- accurate analysis 
- and super nice VSCode.

For now, I switched theme and it ok.
Take all the time you need, I will go back dark the when it's ok.

**Comment by aeschli** [comment]
Right now, imports get the `keyword.operator` scope. `operator` is the problem. I'd suggest to change it to `keyword.control.import` as recommended by  http://www.apeth.com/nonblog/stories/textmatebundle.html

For constructors, it probably should also get the `keyword' scope.

**Comment by aeschli** [comment]
`import` is covered by #37

Renaming this issue for 'constructor' which is not colored at all. I would suggest 'support.type'
