### ISSUE TITLE
Class instance methods should get highlighted as methods 

### ISSUE THREAD

**Issue by mohsen1** [Microsoft/TypeScript-TmLanguage#320]
``` ts
class Person {
    walk = () => {}
    run() {}
}
```

![screen shot 2016-10-17 at 7 34 49 pm](https://cloud.githubusercontent.com/assets/543633/19462316/c968f5ce-94a0-11e6-88f9-7481351e864d.png)

`walk` should be green like `run`.

**Comment by mhegazy** [comment]
Seems to be working for me with latest version of https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar.

![image](https://cloud.githubusercontent.com/assets/8000722/19486326/de37c2ce-9512-11e6-8801-5ebd4f96dde4.png)

**Comment by mhegazy** [comment]
@sheetalkamat do we need to make changes to the theme file for sublime?

**Comment by mohsen1** [comment]
I guess it's an issue with the Monokai theme in VSCode. Light+ works as you shown. 

Shouldn't `walk` and `run` have the same color?

**Comment by sheetalkamat** [comment]
We currently do not check if declaration of variable/fields is arrow or function expression to give them 'function' scope. They are treated as 'variables'.

**Comment by sheetalkamat** [comment]
@mhegazy: Sublime theme does not color variables. and walk is field while run is method.
