### ISSUE TITLE
highlighting regression in latest extension [VS Code]

### ISSUE THREAD

**Issue by wprater** [Microsoft/TypeScript-TmLanguage#323]
**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:**  0.4 / latest

**Code**

```ts
(true ? foo() : bar.then(() => {
});

// breaks coloring below
const baz = 'nope';
```

**Comment by sheetalkamat** [comment]
Duplicate of #321
