### ISSUE TITLE
Latest version broke template strings in JSX

### ISSUE THREAD

**Issue by mohsen1** [Microsoft/TypeScript-TmLanguage#324]
```ts
function foo(a) { return <div className={`abcd-${a}`}></div> }
```

`a` in template string is not highlighted

**Comment by sheetalkamat** [comment]
Which version of Extension are you using? Also which vscode build? Which theme. This doesn't look like grammar issue. The things are scoped correctly by grammar.

**Comment by mohsen1** [comment]
![screen shot 2016-10-20 at 6 10 00 pm](https://cloud.githubusercontent.com/assets/543633/19583313/6f9c9dbe-96f0-11e6-8d40-7a38fe05ae8d.png)


VSCode Version 1.6.1 (1.6.1)
Just downloaded the grammar plugin 
Monokai theme

**Comment by sheetalkamat** [comment]
Opened bug in vscode for this.
