### ISSUE TITLE
No highlighting for property following method

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript-TmLanguage#327]
**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:**  latest

**Code**

```ts
interface X {
    x(): void
    y: number
}
```

The second line is not highlighted at all.

**Comment by sheetalkamat** [comment]
This is by design. There is no easy way to fix this and handle scenarios like when ```{``` start on new line or eg. parameters of constructor start on new line. 
Work around for this is to use semi colon at the end of the line, so modify your eg with
```typescript
interface X {
    x(): void;
    y: number;
}
```

**Comment by andy-ms** [comment]
There is a similar issue for a class following a function.
```ts
export function foo(): void
class x { }
```
