### ISSUE TITLE
Decorator causes following statement to always be parsed as method declaration

### ISSUE THREAD

**Issue by admosity** [Microsoft/TypeScript-TmLanguage#329]
**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:**  0.4 / latest

Atom:
![image](https://cloud.githubusercontent.com/assets/4655972/19689087/32ad9a22-9a9a-11e6-91b6-6cfb4275df11.png)

VSCode:
![image](https://cloud.githubusercontent.com/assets/4655972/19689114/4570235a-9a9a-11e6-8f0f-feba6a242ce5.png)

Sublime:
![image](https://cloud.githubusercontent.com/assets/4655972/19689202/93650ea4-9a9a-11e6-81d6-3dee2a6d033e.png)

**Code**

```ts
class Test {
  @SomeDecorator()
  protected blah: any;

  protected workingVar: any;
}
```

Any direction on how to fix this would be appreciated. Trying to fill my hacktoberfest submissions 😄

**Comment by sheetalkamat** [comment]
I am not able to repro this with [TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:  0.0.6

![capture](https://cloud.githubusercontent.com/assets/8052792/19699625/e1c6a23e-9aa8-11e6-8e67-2bea35b3b4ed.JPG)
