### ISSUE TITLE
TypeScriptReact.YAML-tmLanguage incorrectly generated?

### ISSUE THREAD

**Issue by admosity** [Microsoft/TypeScript-TmLanguage#333]
Not sure if I'm misunderstanding something (first time working with these grammar files), but why is 

https://github.com/Microsoft/TypeScript-TmLanguage/blob/master/TypeScriptReact.YAML-tmLanguage

so short?

It seems that most of it was removed in this commit:
https://github.com/Microsoft/TypeScript-TmLanguage/commit/dfdd2cb6f6df914c08ce7ab99c9a5d2854a962e3#diff-50e2014586f541b15f5689c420a80053

The script in TypeStrong/atom-typescript relies on the TypeScriptReact.YAML-tmLanguage for its grammar definition. 

I have an open pull request to update the grammar files for the atom-typescript plugin.
TypeStrong/atom-typescript#1112

**Comment by sheetalkamat** [comment]
The TypeScriptReact.YAML-tmLanguage is suppose to only contain diffs from the TypeScript.YAML-tmLanguage. None of the repositories should be relying on the Yaml files but the generated .tmLanguage files since those are the ones that are build using our script.

**Comment by admosity** [comment]
Thanks @sheetalkamat and sorry for the annoying issues. 👍
