### ISSUE TITLE
stand-alone `exports` identifier is colored wrong

### ISSUE THREAD

**Issue by zhengbli** [Microsoft/TypeScript-TmLanguage#336]
![image](https://cloud.githubusercontent.com/assets/1171301/19754121/844859e6-9bbf-11e6-9a3c-0cf482a90b7d.png)

**Comment by sheetalkamat** [comment]
This is by design. ```exports``` is scoped as ```support.variable``` even by the [atom grammar](https://github.com/atom/language-javascript) and many others
