### ISSUE TITLE
Allow interpolation coloring in template literal strings when using new JS/TS grammar

### ISSUE THREAD

**Issue by waderyan** [Microsoft/TypeScript-TmLanguage#341]
_From @zackschuster on November 3, 2016 16:18_

- VSCode Version: 1.7.0 (or pre-1.7 with new grammar extension)
- OS Version: Windows 10

Steps to Reproduce:

1. Write a template literal string with interpolation: <code>\`test ${var}\`</code>
2. Before the new grammar was introduced, interpolation received special coloring
3. Post new grammar, interpolation is colored the same as the rest of the string

Personally, I find this far less readable when scanning template strings; I have to look more carefully than before to pick out where I'm interpolating an expression. Is there a way we can return the old coloring while respecting the new design decisions behind the grammar rewrite?

_Copied from original issue: Microsoft/vscode#14917_

**Comment by mhegazy** [comment]
this is what i see now: 
![image](https://cloud.githubusercontent.com/assets/8000722/19982611/fae33512-a1c3-11e6-8eea-b1f8ce8f01de.png)

what is the desired behavior?

**Comment by zackschuster** [comment]
The desired behavior colors the interpolation tags to be blue:

![image](https://cloud.githubusercontent.com/assets/9667758/19984472/be93662e-a1cb-11e6-9614-a2129a5f6119.png)

**Comment by hq-mobile** [comment]
Hey,

Believe I am seeing what @waderyan is seeing (image below) in a pure JS project.

<img width="1263" alt="screen shot 2016-11-04 at 06 36 26" src="https://cloud.githubusercontent.com/assets/12352644/19996682/3ab66ebc-a259-11e6-957e-1039905b0d40.png">

Thanks
Dan :)

**Comment by sheetalkamat** [comment]
There was already Microsoft/vscode#13166 to track this which seems to be closed. @aeschli can you please take a look and see whats going on here. Our grammar has already scoped out the punctuations.. is there something I am missing

**Comment by aeschli** [comment]
I pushed a fix for VSCode. See Microsoft/vscode#13166.

**Comment by zackschuster** [comment]
Thank you!
