### ISSUE TITLE
Add support for CSS in JS syntax highlighting

### ISSUE THREAD

**Issue by aeschli** [Microsoft/TypeScript-TmLanguage#342]
_From @oscar-b on November 3, 2016 11:36_

- VSCode Version: 1.6.1
- OS Version: Windows 10

It would be nice to get syntax highlighting for CSS in JS files, for instance when using [styled-components](https://styled-components.com/)

Example:

```javascript
import styled from 'styled-components';

const Button = styled.button`
  /* Adapt the colors based on primary prop */
  background: ${props => props.primary ? 'palevioletred' : 'white'};
  color: ${props => props.primary ? 'white' : 'palevioletred'};

  font-size: 1em;
  margin: 1em;
  padding: 0.25em 1em;
  border: 2px solid palevioletred;
  border-radius: 3px;
`;

export default Button;
```

Support already exists for Atom and Sublime :)
https://github.com/styled-components/styled-components#syntax-highlighting

_Copied from original issue: Microsoft/vscode#14905_

**Comment by sheetalkamat** [comment]
@oscar-b this cannot be part of generic grammar as there is no indication why this should be css.  You can always write vscode extension that gets this done. 
Eg. look at the [vscode extension](https://marketplace.visualstudio.com/items?itemName=nwallace.language-vscode-javascript-angular2) that colorizes angular templates and comes from [repo](https://github.com/natewallace/language-vscode-javascript-angular2)

**Comment by oscar-b** [comment]
@sheetalkamat Not sure if that's true though, matching
```
styled.*` css `
```
Seems like it would work.

**Comment by sheetalkamat** [comment]
@oscar-b what I am suggesting you is that you would want to write an extension that does that. TypeScript or JavaScript standards do not say that any thing in template string that follows the pattern you mentioned has to be css

**Comment by mhegazy** [comment]
https://github.com/natewallace/language-vscode-javascript-angular2 is a similar extension that adds HTML syntax highlighting to some sections of the TS code for anuglar 2.

**Comment by oscar-b** [comment]
Gotcha I see what you mean, thanks, will have a look! :)
