### ISSUE TITLE
Coloring broken after parameterised type

### ISSUE THREAD

**Issue by aeschli** [Microsoft/TypeScript-TmLanguage#344]
VSCode 1.7.1:

colorizing stops after <number>: 
![image](https://cloud.githubusercontent.com/assets/6461412/20051030/072ba2ee-a4cd-11e6-92d2-3f91f4f72890.png)

```typescript
let a = Array<number>();   // Highlight ok here

interface egGenericsInArray {
   a: Array<number>;
}
let s = "nothing should fail here...";
```

**Comment by sheetalkamat** [comment]
Can't repro this. What am I missing? I don't have any extensions installed. Just VS Code 1.7.1
![capture](https://cloud.githubusercontent.com/assets/8052792/20071306/d1b03a6a-a4d8-11e6-9bd9-aea11e1231ba.JPG)

**Comment by aeschli** [comment]
Oh, sorry, forgot to mention to open it as `.tsx`
