### ISSUE TITLE
undefined is not a JavaScript/TypeScript keyword

### ISSUE THREAD

**Issue by aeschli** [Microsoft/TypeScript-TmLanguage#345]
_From @infinnie on November 7, 2016 7:52_

- VSCode Version: 1.7.1
- OS Version:

Steps to Reproduce:

1. Type `undefined` in a JavaScript/TypeScript file.
2. It would be highlighted as a keyword instead of a variable.

However as is specified, `undefined` is a global constant instead of a keyword.

_Copied from original issue: Microsoft/vscode#15083_

**Comment by MandarSant** [comment]
@aeschli why iam mentioned here

**Comment by aeschli** [comment]
@MandarSant , sorry, copy/paste error.
I meant @infinnie, FYI

**Comment by sheetalkamat** [comment]
```undefined``` is a constant and it is marked as that in the grammar. All the other grammars out there use the same scope.

**Comment by MandarSant** [comment]
@aeschli its ok no problem
