### ISSUE TITLE
Typescript export default not colored

### ISSUE THREAD

**Issue by aeschli** [Microsoft/TypeScript-TmLanguage#35]
_From @felixfbecker on January 3, 2016 14:38_

`export` should be blue

![image](https://cloud.githubusercontent.com/assets/10532611/12079178/11c97b26-b230-11e5-8480-4af05c13305c.png)

_Copied from original issue: Microsoft/vscode#1754_

**Comment by aeschli** [comment]
_From @AlexanderMattoni on January 3, 2016 19:24_

I also have run into a problem where when using `export default class Foo{}`, and then subsequently trying to re-export via "import.ts": `export * from "./foo";`, I was unable to get the class definition from a file  importing "import.ts", and node would also fail trying to run it.

"module has no exported member Foo", but it only happens with the `default` keyword.

**Comment by aeschli** [comment]
_From @felixfbecker on January 3, 2016 19:50_

@AlexanderMattoni you should open a seperate issue for that

**Comment by zhengbli** [comment]
Seems to be working fine now?
![capture](https://cloud.githubusercontent.com/assets/1171301/12610431/9d8138d8-c49c-11e5-9419-e54d856c3b65.PNG)

**Comment by djanosik** [comment]
There are still cases when some ES6 keywords are not colored (export, import, from, constructor, ...).
![image](https://cloud.githubusercontent.com/assets/858180/12911554/9f9b019a-cf13-11e5-8648-8d12ec9fe590.png)

**Comment by aeschli** [comment]
'default' now seems to get the 'keyword' scope, which is good.
'export' gets the 'keyword.operator' keyword which should IMO be improved: #37.
Closing issue.
