### ISSUE TITLE
typescript word hightLight issue

### ISSUE THREAD

**Issue by aeschli** [Microsoft/TypeScript-TmLanguage#351]
_From @baoziv587 on November 5, 2016 8:1_

- VSCode Version:1.71
- OS Version: mac os

Word hight light not work  for these code which below `Map<any>`.
If Map<(any)> or Map<T,P> ,it works.
 
![image](https://cloud.githubusercontent.com/assets/7347513/20028571/57279b30-a370-11e6-9bd2-4c59c05367d6.png)

_Copied from original issue: Microsoft/vscode#15029_

**Comment by aeschli** [comment]
_From @TheColorRed on November 5, 2016 17:32_

Try installing this extension: 
https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar

It is a preview of what is to come in TypeScript syntax highlighting

**Comment by aeschli** [comment]
_From @baoziv587 on November 7, 2016 2:59_

Thank you ,but it's not work for me

**Comment by aeschli** [comment]
_From @rebornix on November 7, 2016 5:51_

It's likely caused by #14921 as well.

**Comment by aeschli** [comment]
_From @waderyan on November 7, 2016 16:43_

@aeschli can you look into this? If there is something I can do to help please let me know.

**Comment by aeschli** [comment]
@TheColorRed The https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar is no longer needed as we have now adopted the latest version of TS in VSCode 1.7.1.

**Comment by aeschli** [comment]
Reproduced with this minimal sample in a js or tsx file:
```typescript
this._blockRenderMap = Map<any>({});
this._eventsMap = {};
```

**Comment by sheetalkamat** [comment]
Fixed by 4d0bdeb
