### ISSUE TITLE
JSDoc syntax highlight. Not supported @prop name

### ISSUE THREAD

**Issue by aeschli** [Microsoft/TypeScript-TmLanguage#353]
_From @IgorNovozhilov on November 11, 2016 6:17_

- VSCode Version:

![image](https://cloud.githubusercontent.com/assets/3082812/20206152/8fc7664a-a7ef-11e6-825a-cf6c7214e08e.png)

- OS Version: win7 pro

Steps to Reproduce:

Don't highlight for property name

![image](https://cloud.githubusercontent.com/assets/3082812/20206099/40333e4c-a7ef-11e6-994a-dc8a6fdfbcec.png)

See:
http://usejsdoc.org/tags-param.html
http://usejsdoc.org/tags-property.html

_Copied from original issue: Microsoft/vscode#15330_

**Comment by sheetalkamat** [comment]
@IgorNovozhilov We use the jsdoc grammar from [atom/language-javascript repo](https://github.com/atom/language-javascript) and would be waiting on their implementation of it.
