### ISSUE TITLE
Wrong Comment Syntax for TSX/JSX

### ISSUE THREAD

**Issue by daslicht** [Microsoft/TypeScript-TmLanguage#355]
When we open a ```*.tsx``` file,  VS Code shows TypeScript React in the bottom right corner.

If we now  highlight some text and call the comment shortcut, the block should be wrapped into the following:
```
	{/* ... */}
```

Currently there are just ```//``` inserted, which is wrong

**Comment by sheetalkamat** [comment]
I have moved this to Microsoft/vscode#15487 as it is not something wrong with the grammar.

**Comment by daslicht** [comment]
If the  Gramma correct, what is wrong ?

**Comment by sheetalkamat** [comment]
@daslicht vscode has logic to insert comments and would be able to investigate as to what is going on here.
