### ISSUE TITLE
JS high not correctly

### ISSUE THREAD

**Issue by aeschli** [Microsoft/TypeScript-TmLanguage#356]
_From @bakso on November 11, 2016 8:39_

- VSCode Version:1.7.1
- OS Version:MacOS 10.11.6

Steps to Reproduce:

```js
function formatBigNum(num) {
  num = Number(num)
  if (num < 10000) {
    return num
  }
  return (num/10000).toString().replace(/(\.[\d]{1})\d+$/,"$1") + 'w '
}
let hbAnimIndex = 0;
let hbAnimNode = null;
```

_Copied from original issue: Microsoft/vscode#15334_

**Comment by aeschli** [comment]
![image](https://cloud.githubusercontent.com/assets/6461412/20229278/cfb63ebe-a855-11e6-8179-e5e5c5bc8065.png)
Looks like the variables are not colored. It that what you meant?

**Comment by aeschli** [comment]
_From @ramya-rao-a on November 16, 2016 3:2_

I see this in insiders: 
![image](https://cloud.githubusercontent.com/assets/16890566/20333145/83edf554-ab65-11e6-9bee-a63d9d353fa7.png)


With a space after `num` in line 6 its all fine

![image](https://cloud.githubusercontent.com/assets/16890566/20333146/8ae00744-ab65-11e6-9f43-5881739ab2e2.png)


This is 1.7.1 
![image](https://cloud.githubusercontent.com/assets/16890566/20333194/d12172d8-ab65-11e6-9774-53e3f7878b11.png)

**Comment by ramya-rao-a** [comment]
_From @olvermue_


Take an existing .ts file and insert the following code:
```typescript
  private showPartyColors() {
    let foo = true ? (2 / 4) : (3 / (2 - 8));
    let bar = console.log('I am red, cause I am upset!');
    // here the code party is fully underway (42) ...
    let baz = (3 / 5) / 7;
    let haveParty = console.log('Now coloring of all code below this function is partially wrong.');
  }

  private mySeriousFunction(myParam: number, another: string){
    console.log('Seems I still have a hangover.');
  }
```
The current result is
![image](https://cloud.githubusercontent.com/assets/17193431/20380690/e2d0781e-aca3-11e6-8ce9-92270a00b739.png)
