### ISSUE TITLE
Syntax breaking

### ISSUE THREAD

**Issue by waderyan** [Microsoft/TypeScript-TmLanguage#357]
_From @Pszek on November 15, 2016 11:34_

- VSCode Version: 1.7.1
- OS Version: 10.11.6 (El Capitan)

After ternary operators ES6 string templates tend to break syntax highlighting (like the one below):
![zrzut ekranu 2016-11-15 o 12 31 47](https://cloud.githubusercontent.com/assets/10253750/20304317/c30ae2c8-ab2f-11e6-8ae6-cfc3c28fa738.png)

_Copied from original issue: Microsoft/vscode#15508_

**Comment by sheetalkamat** [comment]
@Pszek can you please paste your code here for investigation. Thanks

**Comment by Pszek** [comment]
Here you are:
```
const ProductPrice = ({inStock, price}) => {
  const dashCode = 8211
  const dash = String.fromCharCode(dashCode)
  return (
    <span
      className={styles.uPrice}
      itemProp='offers'
      itemScope=''
      itemType='https://schema.org/Offer'
    >
      <span
        itemProp='price'
      >
        {inStock
          ? I18n.toCurrency(price)
          : <div className={styles.outOfStock}>
            {`${dash}`}{I18n.t('spree.out_of_stock')}{`${dash}`}
            </div>}
      </span>
    </span>
  )
}
```
