### ISSUE TITLE
Apply `function-call` scopes to all function calls

### ISSUE THREAD

**Issue by nfour** [Microsoft/TypeScript-TmLanguage#364]
**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:**  0.4 / latest

**Code**

```ts
console.log
console.log()
process.exit()
fn()
```

In the above example, the `log` and `exit` are never matched on the `#function-call` directive within the tmLanguage. It also means `console.log` and `console.log()` have identical scoping on the `log`. 

The `#function-call` directive should add `function-call` scoping so that we can better highlight control flow.

The problem with `function.entity.name` is that it is hard to target with deep nesting scenarious. 

Adding `function-call` is a good step for regular function calls.
`name: entity.name.function.function-call.js`

I'd make a pull request but the fact is that scopes like `support.function.console` are hardcoded throughout, consuming the `#function-call` scoping.

I'm wondering if a re-ordering could fix this or if it's orthogonal to the direction of the this tmLanguage.

**Comment by sheetalkamat** [comment]
@nfour I think adding ```meta.function-call``` for whole function call is better approach than changing the scope names of ```entity.name.function``` to ```entity.name.function.function-call``` It becomes more generic wherein it can be used for support functions too. I will send out PR that modifies this and I think achieves what you are asking for. Take a look at the PR and let me know if that helps.
Note that we have ```meta.definition entity.name.function``` for all the function definitions so it isn't hard to distinguish function definitions that way.

**Comment by sheetalkamat** [comment]
As per [comment](https://github.com/Microsoft/TypeScript-TmLanguage/pull/367#issuecomment-265387808) this is not needed at this point in time.
