### ISSUE TITLE
Uppercase variables are not highlighted in string templates

### ISSUE THREAD

**Issue by emzero** [Microsoft/TypeScript-TmLanguage#368]
**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:**  0.0.10 / latest

`CREDIT_CARD` should be colored the same as `creditCard`

![image](https://cloud.githubusercontent.com/assets/412489/20577894/3f6a77c4-b1a3-11e6-895f-1d3e16420462.png)

```ts
let creditCard = 'cc';
const CREDIT_CARD = 'CC';

console.log(`Payment Type: ${creditCard}`);
console.log(`Payment Type: ${CREDIT_CARD}`);
```

**Comment by sheetalkamat** [comment]
This should be moved to vscode because the language does scope out the constant correctly as:
``` 
Scope:                         source.ts
                               meta.var.expr.ts
                               meta.var-single-variable.expr.ts
                               meta.definition.variable.ts
                               variable.other.readwrite.ts
```

**Comment by aeschli** [comment]
@sheetalkamat There's no 'variable' in the scope, just 'constant.other'.
'constant' is used for all kind of things, such as literals ('constant.character', "constant.numeric', 'constant.language'), keywords ("constant.language"), in regex ('constant.other.character-class.regexp'), library class names ('support.constant')
that we all don't want to color like variables.

IMO this foremost a variable/property, and and constant is rather a secondary thing.
What about calling it 'variable.other.constant' ?

**Comment by sheetalkamat** [comment]
@aeschli Atom grammar uses same scope names for constants: eg. https://github.com/atom/language-javascript/blob/master/grammars/javascript.cson#L1180

**Comment by aeschli** [comment]
@sheetalkamat See https://www.sublimetext.com/docs/3/scope_naming.html for Sublimes recommendation on the usage of `constant.*` and `variable.`.

'variable.other.constant' looks like a good match in our case.

**Comment by sheetalkamat** [comment]
All right. Will update the scope to ```variable.other.constant``` then.

**Comment by aeschli** [comment]
Thanks a lot!
