### ISSUE TITLE
add javascriptreact support for vs code

### ISSUE THREAD

**Issue by foisonocean** [Microsoft/TypeScript-TmLanguage#369]
add `javascriptreact` support for vs code please.

**Comment by sheetalkamat** [comment]
@foisonocean what do you mean by that. VSCode does support react syntax for javascript files. Can you please provide more details on what you are looking for. 
Thanks

**Comment by foisonocean** [comment]
@sheetalkamat 

syntax highlighting for `javascriptreact` is not very good.The extension [`Latest TypeScript and Javascript Grammar`](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) improved syntax highlighting for `javascript` `typescript` `typescriptreact`, but not include `javascriptreact`.

![image](https://cloud.githubusercontent.com/assets/15059605/20695454/0217ef86-b627-11e6-908f-29f8b5a4c8e4.png)

**Comment by sheetalkamat** [comment]
@foisonocean vscode uses same grammar as typescript react for .js and .jsx files.

**Comment by sheetalkamat** [comment]
@foisonocean Please reopen with specific repro code sample with the issue so we can investigate it. Since javascript grammar already supports jsx, there is no action needed for this at this point.
