### ISSUE TITLE
Javascript syntax highlighting inconsistency

### ISSUE THREAD

**Issue by aeschli** [Microsoft/TypeScript-TmLanguage#371]
_From @EikaMikiku on November 30, 2016 10:11_

- VSCode Version: 1.7.2
- OS Version: Win10

Steps to Reproduce:
canvas's 2d context has a func called "moveTo"
example:
```javascript
c.moveTo(0, 0); //moveTo is highlighted the same way as a keyword
c.lineTo(100, 100); //lineTo is highlighted the same way as a function
```
Looks like it revolves around the "move":
```javascript
obj.move(); //move is highlighted as a keyword (bad)
obj.moved(); //moved is highlighted as a function (good)
obj.moveT(); //moveT is highlighted as a function (good)
obj.moveTo(); //moveTo is highlighted as a keyword again (bad)
```

Edit: looks like github syntax highlighter has the same issue, lol

_Copied from original issue: Microsoft/vscode#16262_

**Comment by sheetalkamat** [comment]
This is not a issue with the grammar. The moveTo is support.function while lineTo is entity.name.function same with others

**Comment by aeschli** [comment]
IMO it's hard to understand why some functions are colored as 'library' functions and some not.
Only a few function calls to 'moveTo' is really go to canvas.moveTo.
Also, canvas.moveTo only can be considered a library in a JavaScript browser environment, but not in a node environment.
I'd favour to remove the coloring for 'library' functions and types. Makes the colorisation easer to understand and also simplifies the grammar.

**Comment by sheetalkamat** [comment]
we have had lot of filed bugs asking for the library function coloring #71, #72 to name a few.
We use same rules as what atom javascript grammar uses.

**Comment by sheetalkamat** [comment]
Also in my opinion if you don't care about support.function they should be colored same as entity.name.function instead of keyword in the theme

**Comment by aeschli** [comment]
The VSCode default themes don't make a color difference between 'library' functions and other function calls. But many other theme from the community do and I guess that what @EikaMikiku uses.

#72 is only coloring about function calls. That was a major request. From what I remember only very few really wanted the library coloring.

**Comment by sheetalkamat** [comment]
@aeschli I am still not convinced that we should just remove support identification all together.. Most of the default grammars including atom, sublime have this exact features and people seem to like it.

**Comment by EikaMikiku** [comment]
@sheetalkamat 
I moved from Sublime text to VSCode recently, that is why i noticed the highlight difference, sublime doesn't seem to have it.
![untitled](https://cloud.githubusercontent.com/assets/8401769/20795239/fb6adf70-b7c7-11e6-9a5c-29d275534313.png)

**Comment by sheetalkamat** [comment]
@EikaMikiku @aeschli there are descripencies in what each grammar supports as support functions, classes, objects, methods. 
eg. sublime marks methods like ```shift|sort|splice|unshift|pop|push|reverse|copyWithin|fill``` as support method. Atom grammar has different set of list for the same. We use this list from atom grammar eg. https://github.com/atom/language-javascript/blob/master/grammars/javascript.cson#L1637
