### ISSUE TITLE
TS highlight issue with standard-js style

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript-TmLanguage#384]
_From @unional on December 15, 2016 22:51_

- VSCode Version: 1.8.0

![image](https://cloud.githubusercontent.com/assets/3254987/21245164/d2db9a2c-c2d5-11e6-9fcd-274eb2927a10.png)

Second "declare" highlight is wrong. Putting in ";" on the line above fixes this:
![image](https://cloud.githubusercontent.com/assets/3254987/21245177/f052f87a-c2d5-11e6-9d49-651c0acfb116.png)

_Copied from original issue: Microsoft/vscode#17352_

**Comment by mjbvz** [comment]
Quick repo code: 

```
declare function foo(): any
declare function foo(): any
```

Tested with latest TypeScript grammar extension update

**Comment by unional** [comment]
Also probably related (for typings):

```ts
export function X(): void
export as namespace Y
```
![image](https://cloud.githubusercontent.com/assets/3254987/21246188/062f8ac2-c2dc-11e6-8ded-8662fdfefa77.png)
