### ISSUE TITLE
Typescript React - Generics cause highlighting to break

### ISSUE THREAD

**Issue by AaronAsAChimp** [Microsoft/TypeScript-TmLanguage#385]
**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:**  0.4 / latest

In the following minimal example the keyword 'let' is not properly highlighted. The issue is confirmed in Sublime Text 3 and Atom 1.12.6.

**Code**

```ts
let
b: Promise<number>;let a;
```

**Screenshot**
![screenshot_12_21_16 _4_54_pm-2](https://cloud.githubusercontent.com/assets/60481/21407427/52e5646a-c79e-11e6-8842-2557b9ab48f3.png)

**Comment by sheetalkamat** [comment]
This is by design. There is no way in text mate grammar rules to look ahead in the line. So there is no way to tell that b is actually continuation of the declaration and hence Promise is suppose to be type annotation. Also note that because of this we have to end rules at the end of line to guarantee working of the scenarios that omit ";" at the end.

**Comment by AaronAsAChimp** [comment]
Two things to note though:

1. This works perfectly fine for TypeScript, it only breaks for TypeScriptReact, I'm assuming the JSX element highlighting is taking precedence.
2. The above is only a minimal example. It also fails for the less contrived:

```ts
let variable: number = 12,
    b: Promise<number>;

let a;
```

A workaround would be to close (what its interpreting as) the number tag in a comment.

```tsx
let variable: number = 12,
    b: Promise<number>; // </number> // fixes syntax highlighting.

let a;
```

**Comment by sheetalkamat** [comment]
@AaronAsAChimp  Yes this is the limitation of tmLanguage grammar rules.
The better workarounds are
``` typescript
let variable: number = 12,  b: Promise<number>;

let a;
```

Also note that it isn't exactly right in TypeScript file either because Promise<number> gets classified as Class, Relational operator, Variable, Relational operator
