### ISSUE TITLE
Highlighting issue

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript-TmLanguage#388]
_From @whitecolor on December 24, 2016 12:17_

Highlighting is different in this too cases:
```ts
export const fun = (param: ParamType): FunResult => {
```

```ts
export const fun = 
  (param: ParamType): 
    FunResult => {
```

In the first snippet `param` is highlighted with orange, and types (`ParamType`, `FunResult`) are purple. And in the second `param` and `ParamType` has the same color as `fun` (const name) and `Result` is orange.

_Copied from original issue: Microsoft/TypeScript#13158_

**Comment by DanielRosenwasser** [comment]
In what editor? Please provide more info about the issue you're running into.

**Comment by DanielRosenwasser** [comment]
_From @whitecolor on December 25, 2016 2:49_

@DanielRosenwasser you see that the highlighting in too code snippets are different here in github? The same thing in the VisualStudio Code.

![image](https://cloud.githubusercontent.com/assets/736697/21469537/f651139e-ca76-11e6-9732-09a03829c5de.png)

In the first `param` is highlighted with orange, and types (`ParamType`, `FunResult`) are purple. And in the second `param` and `ParamType` has the same color as `fun` (const name) and `Result` is orange.

**Comment by sheetalkamat** [comment]
![capture](https://cloud.githubusercontent.com/assets/8052792/21625684/a023e7ce-d1c1-11e6-8053-e908e5c317da.JPG)

Note that color of fun cannot be same because of tmLanguage grammar lookup being single line at a time. There is no way to know that second fun is assignment to arrow function
