### ISSUE TITLE
Typescript parameter properties not colored

### ISSUE THREAD

**Issue by aeschli** [Microsoft/TypeScript-TmLanguage#39]
_From @felixfbecker on January 3, 2016 12:18_

`public` and `private` should be blue

![image](https://cloud.githubusercontent.com/assets/10532611/12078707/7ac9423c-b21c-11e5-8ba7-245a533f5376.png)

_Copied from original issue: Microsoft/vscode#1753_

**Comment by aeschli** [comment]
The `keyword` scope is missing on the token.

**Comment by felixfbecker** [comment]
Since this issue was moved, where should issues about syntax highlighting for **Javascript** go?

**Comment by mhegazy** [comment]
@felixfbecker this repo is the right place.

**Comment by anubmat** [comment]
The highlighting looks fine in Sublime:
![issue_39_sublime](https://cloud.githubusercontent.com/assets/17298501/13481219/a7dc962a-e098-11e5-86d5-221a363aef74.PNG)

However, this is an issue in vscode
![issue_39_vscode](https://cloud.githubusercontent.com/assets/17298501/13481275/10158f3a-e099-11e5-8a74-f9cddf8e4f07.PNG)

Code for reference:
`class Thing`
`{`
	`public static inject = ["$mdDialog","$http","$scope","$filter","$stateParams","$state"]`
        `constructor(public $mdDialog: angular.material.IDialogService, private $http: angular.IHttpService){}`	
`}`

**Comment by aeschli** [comment]
In the latest version of VSCode it looks also fine:

![image](https://cloud.githubusercontent.com/assets/6461412/13487834/3d29fe14-e11d-11e5-8c90-2f101a9c7471.png)
