### ISSUE TITLE
Namespace variable highlighting issue

### ISSUE THREAD

**Issue by tinganho** [Microsoft/TypeScript-TmLanguage#390]
**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:**  0.4 / latest

The below code highlights namespace as keyword instead of variable.
**Code**

```ts
let namespace: string;
namespace = '';
```

**Comment by sheetalkamat** [comment]
This doesn't repro in TS and JS Grammar Extension version: 0.0.13 / latest
![capture](https://cloud.githubusercontent.com/assets/8052792/21626181/8ab61fee-d1c4-11e6-881e-17455419b4df.JPG)
