### ISSUE TITLE
Syntax highlighting broken following ES6 spread operator

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript-TmLanguage#393]
_From @jamietre on December 29, 2016 14:58_

- VSCode Version: 1.9.0-insider commit 9486b4
- OS Version: Windows 10

Steps to Reproduce:

1. Create an ES6 class using `extends` and add `super(...args)`
2. Observe lack of highlighting after `super(...args)`
3. Profit

Just noticed it this morning on insider build.

Update  - affects any use of spread operator

![image](https://cloud.githubusercontent.com/assets/573056/21546518/3c45a28c-cdad-11e6-9c76-fc41eba35cab.png)

_Copied from original issue: Microsoft/vscode#17905_

**Comment by andy-ms** [comment]
While it works with the above example now, it still breaks for me in the simpler case:
```ts
const a = Math.max(...x);
const b = 2;
```

`const b = 2;` (and the entire rest of the file) is not highlighted at all.

**Comment by sheetalkamat** [comment]
Closing this as it is little bit different from the original issue and its easier to track that way. File #397

**Comment by jamietre** [comment]
Confused about the status here. This is still broken in today's insider build, there don't seem to be any open issues addressing it.

**Comment by mjbvz** [comment]
@jamietre To test the fix, please try installing the [*Latest TypeScript and Javascript Grammar* extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar)

**Comment by jamietre** [comment]
Beautiful, thanks! I'm a bit confused about the relationship between the VS Code insider build and dependencies such as this, e.g. why would the bug have manifested without my intervention in an insider build, but the fix did not?

**Comment by mjbvz** [comment]
VSCode insiders contains the latest build for VSCode itself . For dependencies like this, the insiders build picks up the version listed in the `package.json`, which may not be the latest published version. So to pick up a new version of the TS/JS grammar, we still have to update VSCode to pick up the latest release of this project.

The *Latest TS Grammar* extension offers an even more up to date version of the TS and JS grammar for testing. It can be installed in older, non-insiders VSCode releases as well and is updated like a normal extension.

Hope that clear things up
