### ISSUE TITLE
highlight issue on TypeScript with higher order function

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript-TmLanguage#399]
_From @unional on January 6, 2017 2:29_

- VSCode Version: 1.8.1
- tsc: 2.2.0-dev.20170103

```ts

interface Foo {
  do(): (() => any)
  someProps: string
}
```

![image](https://cloud.githubusercontent.com/assets/3254987/21705437/c89e3f42-d374-11e6-94b1-a210a616fd0b.png)

Notice `string` is not colored properly.

_Copied from original issue: Microsoft/vscode#18206_

**Comment by sheetalkamat** [comment]
This doesn't repro with latest grammar extension 0.0.14
![capture](https://cloud.githubusercontent.com/assets/8052792/21779720/ad3bec0e-d65d-11e6-94c3-f3d48fd73d44.JPG)
