### ISSUE TITLE
Muli-line strings in JavaScript not colored, code following multi-line string not colored

### ISSUE THREAD

**Issue by aeschli** [Microsoft/TypeScript-TmLanguage#40]
_From @KevinSCreative on December 30, 2015 18:13_

After the first line, multi-line strings in JavaScript don't get string color. In the following example, only "Hello World" has the string color, and the obj variable declaration is all one color. In the default theme, 'var' is supposed to be blue. I would also expect the rest of the string to be orange in the default theme, not just the first line. 

I am running VSC 0.10.6 and I have no extensions installed.

```ts
var test = 'Hello World!\
<div>\
<p>Testing</p>\
</div>\
    ';
var obj = $(test);

```
_Copied from original issue: Microsoft/vscode#1716_

**Comment by aeschli** [comment]
From Microsoft/vscode#2070 :
![js-highlighting-bug-resolution](https://cloud.githubusercontent.com/assets/5341447/12388399/e66b0cca-bdd2-11e5-9abe-d3a7346770d7.png)

**Comment by zhengbli** [comment]
Duplicate with #5

**Comment by Hakeemmidan** [comment]
In case anyone is still struggling with this: You can use backticks (``) to have multiple lines in a JS string:

```JS
const multiLineStr = `
  Hello
  world
`;
```

[Docs reference](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals#multi-line_strings)
