### ISSUE TITLE
Syntax highlighting broken in JSX when using arrow function's implicit return

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript-TmLanguage#401]
_From @matthamil on January 6, 2017 5:16_

- VSCode Version: 1.8.1
- OS Version: OSX 10.11.6

Steps to Reproduce:

1. Create a `.js` file, and write some JSX in it like so:

![image](https://cloud.githubusercontent.com/assets/11802078/21708284/94d486f8-d39c-11e6-91ec-2ef1149e5b1a.png)

2. Use an arrow function to implicitly return JSX.

3. Watch as the syntax highlighting below breaks.

This only breaks when the JSX is implicitly returned with the ES6 arrow function. If you wrap the JSX in parens, the syntax highlighting is not broken:

![image](https://cloud.githubusercontent.com/assets/11802078/21708312/d0693b00-d39c-11e6-899b-fe611387f394.png)

Using the arrow function and using an explicit return fixes the syntax highlighting as well:

![image](https://cloud.githubusercontent.com/assets/11802078/21708329/fa3fa860-d39c-11e6-83b5-eadaf5b76bd1.png)

_Copied from original issue: Microsoft/vscode#18208_

**Comment by mjbvz** [comment]
@matthamil I'm untable to repo this issue using this code:

```js
const a = (props) => (
    <Wrapper>
        <div>
            <a>fdsa</a>
            <button to={'fdasf'}></button>
        </div>
        <ul>
            {props.prop.map(x => <MyElement/>)}
        </ul> 
    </Wrapper>
);
```

![screen shot 2017-01-06 at 11 08 43 am](https://cloud.githubusercontent.com/assets/12821956/21729583/7ea2764c-d400-11e6-90a1-bf7b938c3c89.png)

Can you please provide the text source of the example code you are using. Also, do you have any extensions installed?

**Comment by matthamil** [comment]
@mjbvz After playing around with extensions and disabling them, I've identified the issue as this plugin: https://marketplace.visualstudio.com/items?itemName=joshpeng.sublime-babel-vscode

I'll open an issue there. Sorry for not thoroughly checking my plugins before opening an issue.

**Comment by mjbvz** [comment]
No problem. Thank you for quickly following up. 

Closing this issue since it seems an extension is the root cause
