### ISSUE TITLE
Readonly in literal type

### ISSUE THREAD

**Issue by andy-hanson** [Microsoft/TypeScript-TmLanguage#406]
**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:**  latest

**Code**

```ts
type T = { readonly x: number; }
interface I { readonly x: number; }
```

![screenshot](https://cloud.githubusercontent.com/assets/5387404/21957983/e851f024-da57-11e6-94b6-88d8c784188d.jpg)

As a side note, I've been seeing a lot of purple in the "Quiet Light" color theme in vscode. Would prefer black for normal identifiers.

**Comment by sheetalkamat** [comment]
I don't see this. This looks like theme issue. Moving this to vscode
![capture](https://cloud.githubusercontent.com/assets/8052792/22036771/7956a454-dca9-11e6-9673-a2f1cb3a1d49.JPG)

**Comment by sheetalkamat** [comment]
Opened Microsoft/vscode#18688
