### ISSUE TITLE
Function named support.module.node.ts entry is not recognized as a function

### ISSUE THREAD

**Issue by rokoroku** [Microsoft/TypeScript-TmLanguage#408]
**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:**  0.0.17 / latest

**Code**

```ts
// assume that assert and path is user-defined function here
assert(truthyValue, 'must be true');
path(pathArgs);
```

when a function name matches an entry within `support.module.node.ts` class, it won't be recognized as a `function`. 

The entries are: `assert|buffer|child_process|cluster|constants|crypto|dgram|dns|domain|events|fs|http|https|net|os|path|punycode|querystring|readline|repl|stream|string_decoder|timers|tls|tty|url|util|vm|zlib`

So it prevents syntax highlighting of functions named above entries.

**Comment by aeschli** [comment]
The default themes in VSCode (Dark+, Light+) didn't colorize 'support.module' so far.
Not clear to me what color is should get, function, variable or types?
Based on the list and the context that node modules of that name are used I'd say variable. 
But then these identifiers are very commonly used identifiers ('path', 'assert', 'util'). Coloring will lead to confusion, especially in source code not related to Node.

**Comment by rokoroku** [comment]
I meant, when it declared as a local function and used with function call (e.g. assert(true, ...)), it expected to be a 'function' grammar, not a 'support.module'. So it could be colorized with function color, like github code colorization  above.

**Comment by aeschli** [comment]
Comparing with the atom gramma: It does not seem to have NodeJS colorizing. 
![image](https://cloud.githubusercontent.com/assets/6461412/22206649/691dc806-e17c-11e6-9ee4-87453ffce435.png)
As it's not clear what a module stands for (function or variable or type) I'd suggest to remove the Node specific color rules from the TypeScript grammar.
Alternative would be to issue 2 scopes: for example 'support.function' 'support.module.node' for the assert example above

**Comment by sheetalkamat** [comment]
Because atom grammar doesnt have scope "support.node.module", I am going to remove "support.node.module" and if anyone asks for it, we can consider it then.
