### ISSUE TITLE
Var declaration statement with multiple declarations not tokenized correctly

### ISSUE THREAD

**Issue by aeschli** [Microsoft/TypeScript-TmLanguage#41]
Tokenize
```typescript
var token_text, token_type, last_type, last_last_text, indent_string;
```
Note that only the fist identifier gets a token
![image](https://cloud.githubusercontent.com/assets/6461412/12197436/42ea3378-b607-11e5-9f98-f392c811f70d.png)

the rest is one single token with scope
`token expr meta var`

**Comment by stkb** [comment]
Dup of #16. I'm working on it at the moment :)

**Comment by anubmat** [comment]
Looks good in sublime-text
![error_41_sublime](https://cloud.githubusercontent.com/assets/17298501/13481434/8befff2c-e09a-11e5-9b4a-80beb0a504f0.PNG)

Is a problem in vscode
![error_41_vscode](https://cloud.githubusercontent.com/assets/17298501/13481442/977d1e7e-e09a-11e5-9026-d696d513aa6e.PNG)

**Comment by aeschli** [comment]
Seems to also work in the latest version of VSCode (@anubmat on what version are you, and which theme?) :
![image](https://cloud.githubusercontent.com/assets/6461412/13487857/66dc663e-e11d-11e5-83da-ccc738f2b406.png)

**Comment by anubmat** [comment]
I am at version 10.8 and color theme Dark+ (default dark)

**Comment by thorn0** [comment]
VS Code 0.10.10. It works if the declaration is single-line but breaks if it's not: 
![image](https://cloud.githubusercontent.com/assets/94334/13612192/cfd0cd42-e56e-11e5-8bb1-1374a510d9a5.png)
