### ISSUE TITLE
Syntax highlighter confused by class properties with optional type

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript-TmLanguage#410]
_From @kevinbarabash on January 23, 2017 15:56_

- VSCode Version: 1.8.1
- OS Version: Mac OS X, 10.11.5

Steps to Reproduce:
1. Write a class containing class properties, e.g.
```
class Foo {
    state = {
        bar: (null: ?Bar),
    }

    toString() {
        const bar = this.state.bar;
        console.log(`bar = ${bar}`);

        // the rest of the file is in a string
    }
}
```
<img width="387" alt="screen shot 2017-01-23 at 10 54 46 am" src="https://cloud.githubusercontent.com/assets/1044413/22211203/5462dd38-e15a-11e6-9974-b43aaf39ca36.png">

The line `const bar = this.state.bar;` is also incorrectly highlighted.

Changing `?Bar` to`Bar` fixes the highlighting.

_Copied from original issue: Microsoft/vscode#19048_

**Comment by mjbvz** [comment]
Confirmed this still repos in using the newest 0.0.18 TS grammar vscode extension

**Comment by sheetalkamat** [comment]
@mjbvz and @kevinbarabash the code where state is assigned value is anyways incorrect syntactically. and this results in syntax errors as 
```
a.ts(3,19): error TS1005: ')' expected.
a.ts(3,21): error TS1136: Property assignment expected.
a.ts(3,25): error TS1005: ':' expected.
a.ts(3,26): error TS1136: Property assignment expected.
```
I don't think error like this is made enough to handle these kind of error scenarios.

**Comment by kevinbarabash** [comment]
@sheetalkamat I'm using flow for type checking.

**Comment by sheetalkamat** [comment]
@kevinbarabash we only support typescript/javascript.

**Comment by kevinbarabash** [comment]
@sheetalkamat is there anyway to swap out the syntax highlighter?

**Comment by sheetalkamat** [comment]
@kevinbarabash https://code.visualstudio.com/docs/customization/colorizer has information on colorizer for vscode.
