### ISSUE TITLE
Support `new ClassName()` rules

### ISSUE THREAD

**Issue by rokoroku** [Microsoft/TypeScript-TmLanguage#411]
**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:**  0.0.18 / latest

With VSCode 1.9 update, merging tmTheme grammar token has been broken:
https://code.visualstudio.com/updates/v1_9#_theme-matching-rules-now-respect-textmate-semantics

<img width="628" alt="2017-02-03 12 21 36" src="https://cloud.githubusercontent.com/assets/5208632/22578401/dbe3c3a8-ea0b-11e6-81d3-2fc690b20073.png">

Prior 1.9, we can colorize `new Date()` as yellow (so as function color) by using `new.expr.entity.name.type` rule, but we cannot colorize it with this way anymore. 

I want to use different syntax for `entity.name.type` and `new.expr.entity.name`

So I'd request a new grammar like `new.expr.entity.name` to colorize `Date`  from above screenshot.

**Comment by sheetalkamat** [comment]
The scope for Date in your sample is:
```source.ts  meta.var.expr.ts    new.expr.ts   entity.name.type.ts```
Using Microsoft/vscode#17933 you should be colorize these accordingly. It doesn't need change in the grammar.

**Comment by rokoroku** [comment]
Oh, we can using multiple grammar token by using whitespace between tokens, got it. Thank!
