### ISSUE TITLE
Grammar for interface entity name

### ISSUE THREAD

**Issue by rokoroku** [Microsoft/TypeScript-TmLanguage#412]
**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:**  0.0.18 / latest

**Code**
<img width="590" alt="2017-02-04 12 58 14" src="https://cloud.githubusercontent.com/assets/5208632/22615558/2d437404-eada-11e6-81d1-9841c5b5e6d6.png">

Currently the interface entity name's grammar is `entity.name.type.class` and `meta.class` which is same with class entity name's grammer, and cannot find different token with class entity.

Could we have grammar for interface entity name so that we can have different color between `interface` and `class` entities?

**Comment by sheetalkamat** [comment]
Fixed with e322180
