### ISSUE TITLE
Flowtype import type scope

### ISSUE THREAD

**Issue by nfour** [Microsoft/TypeScript-TmLanguage#414]
**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:**  0.0.18 / latest

This is more of a JS related issue, as this is the base for the JS tmLanguage.

![Imgur](http://i.imgur.com/pUDbSu5.png)

```js
import type { MyType } from './blah';
import { type MyType, MyRealThing } from './blah';
```

Currently, as above, `type` is not given a scope to target.

**Comment by sheetalkamat** [comment]
This grammar does not support flow. You can always build extension to support flow grammar
