### ISSUE TITLE
Mark JSX components differently from standard HTML tags

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript-TmLanguage#415]
_From @tannerlinsley on January 18, 2017 19:14_

<img width="406" alt="screen shot 2017-01-18 at 12 11 36 pm" src="https://cloud.githubusercontent.com/assets/5580297/22078988/675a7734-dd77-11e6-8a9f-d3617f495029.png">

This is no so in Atom (which is honestly the last thing keeping me from moving all the way to vscode):
![screen shot 2017-01-18 at 12 13 50 pm](https://cloud.githubusercontent.com/assets/5580297/22079010/823ed78e-dd77-11e6-84d8-f144930c4cfa.png)

It doesn't seem to be fixed by using any theme, or installing the https://github.com/dzannotti/vscode-babel extension.

Any ideas?

_Copied from original issue: Microsoft/vscode#18752_

**Comment by mjbvz** [comment]
The request here would be to mark custom component tags differently from html tags. Right now, both are scoped the same, for example:

```
entity.name.tag.js
meta.tag.js
meta.jsx.children.tsx
meta.tag.without-attributes.js
meta.var.expr.js
source.js
```

When I mentioned this to @mhegazy, I believe he suggested that this could be as simple as seeing if the first letter of the tag is capitalized.

**Comment by tannerlinsley** [comment]
I agree.  First letter being capitalized would be a pretty dead giveaway along with tags that contain object dot notation:
`<components.myComponent attr={...} />`

**Comment by mjbvz** [comment]
I tried this in atom with babel plugin.

For the jsx `<div />`, `div` is:

* source.js.jsx
* meta.tag.jsx
* entity.name.tag.open.jsx

For the jsx `<Div />`, `Div` is:

* source.js.jsx
* meta.tag.jsx
* entity.name.tag.open.jsx
* support.class.component.open.jsx

**Comment by tannerlinsley** [comment]
So it might only have to do with the syntax highlighting then, if it's already making the distinction.

**Comment by mjbvz** [comment]
Yes, I suspect so. This means that the highlighting won't be right all the time, but it should work in common cases fairly well.

Here's what I believe is the implementation of this in the babel grammar: https://github.com/gandm/language-babel/blob/dbb88f69aaf09bf30e517d6dc1c8144467743299/grammars/Babel%20Language.json#L2183

and here's where I think we would need to update the Typescript react grammar : https://github.com/Microsoft/TypeScript-TmLanguage/blob/master/TypeScriptReact.YAML-tmLanguage#L163

**Comment by tannerlinsley** [comment]
I'm not sure why this is closed.  I just tried to move to VSCode again from Atom and this still isn't fixed. @waderyan any insights here?  For someone using JSX and React, this is very sad experience :(

**Comment by waderyan** [comment]
@tannerlinsley can you take a screenshot of what you are seeing? Also please confirm you are on the latest version of VS Code.

**Comment by tannerlinsley** [comment]
Confirmed latest version. The screenshots above are still representative of
what I am seeing

**Comment by waderyan** [comment]
@mjbvz this seems to have shown up again.

**Comment by mjbvz** [comment]
@tannerlinsley Are you using VSCode 1.13?

**Comment by tannerlinsley** [comment]
Yes I am 😊

**Comment by mjbvz** [comment]
@tannerlinsley What theme are you using?

**Comment by mjbvz** [comment]
Closing as this has been fixed for the included vs code themes

**Comment by mustafawm** [comment]
This feature is missing from November version (1.18)!?
