### ISSUE TITLE
Syntax highlighting breaks for certain tokens

### ISSUE THREAD

**Issue by EthanRutherford** [Microsoft/TypeScript-TmLanguage#416]
**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:**  0.0.18 / latest

For some reason, for a specific name, VS code stops highlighting one specific token after a certain line in the file. The file is not terribly long (303 lines), no lines are terribly long, and the name is syntax highlighted on one line (light blue), not syntax highlighted on the next (white). In this instance the variable name is `path`. Changing the name to something else highlights appropriately, but it does not fix the problem as changing it back to `path` breaks it again. I have no idea how it gets in this state, so I can't really provide steps to reproduce, it seems completely arbitrary.

![image](https://cloud.githubusercontent.com/assets/5589147/22865712/abdb83ca-f11e-11e6-807c-063f5126e0ce.png)

It seems to be broken for the variable path anywhere in the file. The only reason that the two instances above (on the first line of the function) are highlighted is that one is proceeded by let and the other is a property of an object.

(originally reported [here)](https://github.com/Microsoft/vscode/issues/20514)

**Comment by dustinsoftware** [comment]
I can also repro this issue with the simple test case below (all extensions are disabled)

![image](https://cloud.githubusercontent.com/assets/942358/22895553/c5a46b38-f1d1-11e6-9802-429c33056225.png)

**Comment by EthanRutherford** [comment]
It does seem to be consistently broken for these specific tokens. There may be more, but these are the ones we've run into.

**Comment by EthanRutherford** [comment]
Add `url` to that list
![image](https://cloud.githubusercontent.com/assets/5589147/23096710/f9452b86-f5d6-11e6-9d43-36744a6c2f9f.png)

**Comment by dustinsoftware** [comment]
Repros in VS Code 1.9.1. I can't repro in Code-Insiders.

**Comment by sheetalkamat** [comment]
This doesn't repro any more
