### ISSUE TITLE
Arrow functions: Signature not tokenized the same way as for functions

### ISSUE THREAD

**Issue by aeschli** [Microsoft/TypeScript-TmLanguage#42]
Tokenize this:
```typescript
			return this.travelWorld((cell: Cell) => {
				cell.live = Math.random() < this.initialLifeProbability;
				return cell;
			});
```
Note that `cell: Cell` is a single token (scope `block body decl declaration meta method object ts`).
It would be great if it can follow the tokenization for functions

**Comment by sheetalkamat** [comment]
Fixed by #257
