### ISSUE TITLE
The syntax color changes.

### ISSUE THREAD

**Issue by CatsMiaow** [Microsoft/TypeScript-TmLanguage#422]
**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:**  0.0.18 / latest

content property color
![20170224_122113](https://cloud.githubusercontent.com/assets/1300172/23289556/e3f39d2e-fa8d-11e6-8af0-581aff727e12.png)
![20170224_122104](https://cloud.githubusercontent.com/assets/1300172/23289559/e480418e-fa8d-11e6-8bf8-04aebbb0e242.png)

curly brace color
![20170224_104323](https://cloud.githubusercontent.com/assets/1300172/23289557/e420c10a-fa8d-11e6-9c32-0a18d805da27.png)
![20170224_104341](https://cloud.githubusercontent.com/assets/1300172/23289558/e44f9d4a-fa8d-11e6-903c-bc42bd0d975c.png)

There is no problem running the code.

**Comment by sheetalkamat** [comment]
This does not repro any more.. If it repros, please copy paste the code and theme. Thank you.
