### ISSUE TITLE
Jsdoc Not Marking Properties with Dash in Symbol Name

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript-TmLanguage#424]
**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:**  0.0.18 / latest

From https://github.com/Microsoft/vscode/issues/21592

**Code**

```js
/**
 * @typedef Product
 * @property {string} title
 * @property {boolean} high-top
 */

/**
 * @type {Product}
 */
const product = null
```

**Bug**
`high-top` is not properly marked. It is scoped as:

* other.description.jsdoc
* other.meta.jsdoc
* comment.block.documentation.js
* source.js

while `title` is scoped as

* variable.other.jsdoc
* other.meta.jsdoc
* comment.block.documentation.js
* source.js

**Comment by sheetalkamat** [comment]
Please open the bug in atom/language-javascript as we use their code to colorize jsdoc. We will pick it once it is available
Thanks
