### ISSUE TITLE
Invalid classification after `...arguments`

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript-TmLanguage#429]
`...arguments` seems to break colorization

```ts
export default class Calendar extends Component {
  constructor(props) {
    super(...arguments);

    this.updateYears(props);

    this.state = {
      display: props.display,
    };
  }
}
```

![image](https://cloud.githubusercontent.com/assets/8000722/23826439/e0fb5318-0650-11e7-8eb0-a801b300d49e.png)

![image](https://cloud.githubusercontent.com/assets/8000722/23826440/eafe0d60-0650-11e7-8b52-69d10ce224e4.png)

**Comment by sheetalkamat** [comment]
Fixed by cc5499ddfaed2479af47a4c0d22bac0f46f6efd2
