### ISSUE TITLE
something wrong with the Syntax highlighting (javascript)

### ISSUE THREAD

**Issue by aeschli** [Microsoft/TypeScript-TmLanguage#43]
_From @yuanlinssdut on December 28, 2015 2:35_

![image](https://cloud.githubusercontent.com/assets/7608992/12013274/21861b5a-ad4e-11e5-925c-e89283f9fb9e.png)

_Copied from original issue: Microsoft/vscode#1672_

**Comment by aeschli** [comment]
_From @bpasero on December 28, 2015 8:14_

@yuanlin-ssdut more info please

**Comment by aeschli** [comment]
_From @ZombieProtectionAgency on December 28, 2015 13:35_

@bpasero If I had to guess I would think they are talking about the variables highlighting. on line two `$this` should be one color.

**Comment by aeschli** [comment]
_From @bpasero on December 28, 2015 15:10_

Right, my guess too.

**Comment by anubmat** [comment]
The problem is that 'this' is being recognized as a keyword. I am not sure if 'this' should be allowed to be used as variable name. @aeschli , can you help me label this as a bug (if we want to allow 'this' to be used as variable names) or a non-bug because it should not be supported.

**Comment by aeschli** [comment]
I think the problem is that the variable named `$this`should not be half highlighted as a keyword. But IMO it's ok to always highlight 'this' always as a keyword.
You probably just have to add the \b around the `this`.

**Comment by ZombieProtectionAgency** [comment]
Does the matching happen with javascripts regex? If so I dont think that `/\bthis/` would work. http://www.ecma-international.org/ecma-262/5.1/#sec-15.10.2.6
