### ISSUE TITLE
Spread operator can break JS highlighting.

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript-TmLanguage#431]
_From @jeffmcmahan on March 12, 2017 19:5_

- VSCode Version: 1.10.2
- OS Version: 10.11.6

Steps to Reproduce:

1. Place this code in a JS file:

    ```js
    myFunc
    (...argName)
    
    function otherFunc() {} // <-- Not highlighted.
    ```
Remove the spread operator or the line break and the highlighting works again.

## Why fix this?
The parser used by VSCode is plainly in error. And FWIW, stuff like this is useful when working with higher-order functions:

```js

funcName
  (...someArgs)
  (someMore)
  (someMoreAgain)

```

_Copied from original issue: Microsoft/vscode#22483_

**Comment by mjbvz** [comment]
The scope of the start of the `(...a)` is:

punctuation.definition.parameters.begin.js
meta.parameters.js
meta.arrow.js
source.js


while the scope of the `function` is:

meta.arrow.js
source.js

**Comment by jeffmcmahan** [comment]
@mjbvz - Could you say whether this'll take considerable time to fix? My code is *filled* with higher-order functions, and many use spread. This problem reduces VSCode to notepad for me. But I really like it otherwise and want to make the jump from Atom.

Sorry to bug you, and keep up the great work.

**Comment by mjbvz** [comment]
I think this line is the root cause: https://github.com/Microsoft/TypeScript-TmLanguage/blob/master/TypeScript.tmLanguage#L4420 That is what I believe is causing the `(...a)` and everything after it to be treated as an arrow.

As for fixing this however, I'm not sure. It may be that this pattern should only be detected as an arrow function if the `=>` is on the same line. I'll try playing around with it a bit further but can't promise anything

**Comment by mjbvz** [comment]
@jeffmcmahan Submitted a PR #442 with a potential fix

**Comment by jeffmcmahan** [comment]
Whoa that was fast. Thanks a million!

**Comment by jeffmcmahan** [comment]
Hey there. Do you think I could expect this in a release soon? I see the PR is untouched, thus far.

**Comment by sheetalkamat** [comment]
Sorry for the delay as I was on leave and couldn't take a look at this earlier. I have pushed the change out. I will be publishing updated version of TypeScript grammar version today and it should be available in that update.
