### ISSUE TITLE
Numeric object key causes different color for first letter

### ISSUE THREAD

**Issue by Skalman** [Microsoft/TypeScript-TmLanguage#432]
**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:**  0.0.18 / latest

**Code**

```ts
var a = {
    0: b.cd()
};
```

In `cd()`, the `c` has a different color from `d`. I can reproduce this for both TypeScript and JavaScript.

**Comment by sheetalkamat** [comment]
Fixed by 36ad8ae650421f104ec3636658480379dabf5647
