### ISSUE TITLE
Types colored differently after `as` vs after `type T =`

### ISSUE THREAD

**Issue by andy-hanson** [Microsoft/TypeScript-TmLanguage#436]
**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:**  0.0.18

**Code**

```ts
const x = 3 as Foo | Bar; // Fine
const y = 3 as Foo |
    Bar; // Not bolded
type T = Foo |
    Bar; // Bolded
```

**Comment by sheetalkamat** [comment]
This is by design and limitation of tmLanguage syntax and lookup that can only be done one line at a time.
