### ISSUE TITLE
Inconsistent highlighting for array type in parameter vs return type

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript-TmLanguage#437]
**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:**  latest

**Code**

```ts
function f(x: number[]): number[] { return x; }
```

![screenshot from 2017-03-30 11-00-20](https://cloud.githubusercontent.com/assets/19274678/24518915/494a296c-1538-11e7-990e-d4af1124feed.jpg)

**Comment by sheetalkamat** [comment]
Closing this for Microsoft/vscode#25041
