### ISSUE TITLE
JS Syntax highlighting gets confused with `catch`

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript-TmLanguage#448]
_From @NickHeiner on May 3, 2017 22:0_

- VSCode Version: 6eaebe3b9c70406d67c97779468c324a7a95db0e
- OS Version: macOS Sierra 16E195

The following code snippet does not look correct:

![image](https://cloud.githubusercontent.com/assets/829827/25683455/348cf39e-302a-11e7-9b36-be34642e6c48.png)

(Is there a different repo that this issue would be more appropriate for?)

_Copied from original issue: Microsoft/vscode#25859_

**Comment by mjbvz** [comment]
Confirmed in the latest grammar using the code:

```ts
Promise.reject('rejected').
    catch(console.log)
```

However, I'm not sure if this can be easily fixed. Textmate grammars work per line, and we've run into problems similar to this with the markdown grammar that have been difficult to resolve

**Comment by sheetalkamat** [comment]
Yes this is going to be by design as @mjbvz mentioned because of limitation to the grammar

**Comment by NickHeiner** [comment]
I'm also running in to this with `let` but I'm guessing it's going to be a `wontfix` for the same reason.

![image](https://user-images.githubusercontent.com/829827/43223453-ffe995ae-9007-11e8-9786-70663f062ec2.png)
