### ISSUE TITLE
Incorrect Highlighting of Multi-line Generic Type List

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript-TmLanguage#452]
**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:**  0.0.19 / latest

From: https://github.com/Microsoft/vscode/issues/26485

**Code**

```ts
class Test<A, B>{}
class Favorite extends Test<
  string | number,
  undefined
> {
  // class content  
}
```

<img width="298" alt="screen shot 2017-05-11 at 4 39 49 pm" src="https://cloud.githubusercontent.com/assets/815236/25970948/8538d71a-3668-11e7-903d-6a4fb50e50aa.png">

**bug**
After the newline, `string | number` are not part of the typescript type parameter list

**Comment by edgarjrg** [comment]
This is still happening 🤔
Version: 1.40.2
Commit: f359dd69833dd8800b54d458f6d37ab7c78df520
Date: 2019-11-25T14:52:45.129Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.0.0

![image](https://user-images.githubusercontent.com/10213241/69925223-bf42ed00-148d-11ea-96d6-033bd17ae5e8.png)
![image](https://user-images.githubusercontent.com/10213241/69925227-c964eb80-148d-11ea-8625-453fcf189398.png)

**Comment by FleetingAgent** [comment]
**Please Reopen!**

> Version: 1.96.3 (user setup)
Commit: 91fbdddc47bc9c09064bf7acf133d22631cbf083
Date: 2025-01-09T18:14:09.060Z
Electron: 32.2.6
ElectronBuildId: 10629634
Chromium: 128.0.6613.186
Node.js: 20.18.1
V8: 12.8.374.38-electron.0
OS: Windows_NT x64 10.0.22631

![Image](https://github.com/user-attachments/assets/0e62a390-5c02-4768-91cf-2cfac5bc5fd9)

![Image](https://github.com/user-attachments/assets/7255be7b-299d-442f-a246-bd671f0f9abb)
