### ISSUE TITLE
Scoping on javascript variables definition

### ISSUE THREAD

**Issue by rafamel** [Microsoft/TypeScript-TmLanguage#456]
**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:**  0.0.19 / latest

While inspecting scopes for Javascript in VSCode, if a variable is defined after `let` or `var`, its scope will rightly be within `meta.definition.variable`, while defining an additional variable after a comma results in that variable lacking the `meta.definition.variable` scope, making it, scope wise, indistinguishable from any other `readwrite` variable.

Is this the intended behavior?

![Correct](https://image.prntscr.com/image/94c2be268f414617b53f333858bff74c.png)
![Incorrect](http://i.prntscr.com/5bb086c422e8484aa10887df1fbf501d.png)

(Originally on [https://github.com/Microsoft/vscode/issues/26811](https://github.com/Microsoft/vscode/issues/26811))

**Comment by sheetalkamat** [comment]
This is by design to avoid incorrect scopings spanning multiple line declarations. The tmLanguage can lookup only a line at a time so it is something we cannot fix without other scenarios breaking
