### ISSUE TITLE
Scope collision between argumentless decorators and decorator arguments

### ISSUE THREAD

**Issue by dsifford** [Microsoft/TypeScript-TmLanguage#464]
**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:**  latest

Hello there,

As the title suggests, there's currently a scope collision between decorators that take no arguments and the arguments of decorators that do.

### Example

```ts
@withArgs(arg1, arg2)
//        ^^^^  ^^^^
@withoutArgs /*
 ^^^^^^^^^^^ */
class Foo {}
```

Above, the areas marked with `^^` have the exact same scope. So it becomes impossible to make these decorators look the same without also affecting the arguments of decorators that accept arguments.

Could this be adjusted?

Thanks in advance! 😄 

**Edit:** Below is the full scope of the example above

```
variable.other.readwrite.tsx
meta.decorator.tsx
source.tsx
```

**Comment by sheetalkamat** [comment]
This is not being asked much yet and implementing this would mean duplicating lot of code (because we share the expression code here and that includes too many regexs) hence this is for now by design. We can take a look at this again if the need arises in future

**Comment by dsifford** [comment]
Sounds great. Thanks nevertheless!

Much appreciated for all your hard work on this language. Bar none, _the_ most intricately scoped and detailed tmLanguage that I've come across. 👌 👌 

Keep up the great work.
