### ISSUE TITLE
Function Return Type on Next Line Breaks Syntax Highlighting

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript-TmLanguage#465]
**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:**  0.0.20

**Code**

```ts
function foo():
	T<number>
{}
```

<img width="176" alt="screen shot 2017-05-30 at 3 30 05 pm" src="https://cloud.githubusercontent.com/assets/12821956/26607753/eda63ac0-454c-11e7-8b14-7530bbb2223e.png">

This differs from the normal syntax highlighting: 

<img width="265" alt="screen shot 2017-05-30 at 3 31 33 pm" src="https://cloud.githubusercontent.com/assets/12821956/26607776/0a3a45e6-454d-11e7-865e-7c73d1720869.png">

The scope on `T` in the first case is:

- variable.other.constant.ts
- source.ts

In the singleline case it is instead:

- entity.name.type.ts
- meta.return.type.ts
- meta.function.ts
- source.ts

**Comment by sheetalkamat** [comment]
This is by design for now. It is limitation of tmLanguage grammar that has context of one line at a time without having better error recovery. This will not be fixed. As also mentioned in repro there exists the work around for this.

**Comment by sheetalkamat** [comment]
This is fixed in master
