### ISSUE TITLE
Multiline JSDoc Types

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript-TmLanguage#467]
From https://github.com/Microsoft/vscode/issues/27777

**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:**  0.0.20

**Code**

```js
/**
 * @param {{
 *  z: number
 * }} x
 */
function foo(x){}
```

Current highlighting: 

![screen shot 2017-05-31 at 2 49 02 pm](https://cloud.githubusercontent.com/assets/12821956/26655606/53488130-4610-11e7-9233-e99b946a0f90.png)

There seems to be some debate about whether this is supported or not: https://github.com/jscs-dev/node-jscs/issues/245 but it seems closure supports this syntax

**Comment by sheetalkamat** [comment]
We used the jsdoc grammar from atom/language-javascript. Please file the issue there and once fixed we will pick it up. Thank you.

**Comment by Raynos** [comment]
Can we re-open this issue ? The upstream repository is not maintained anymore ( https://github.com/atom/language-javascript/pull/645#issuecomment-496795093 )

Any changes to the jsdoc grammar to support multiline syntax highlighting wil lhave to be made directly in this repository.

**Comment by jeremyjacob** [comment]
Seconded. The issue is still present, despite support for multiline JSDoc types at the LSP level.
<img width="250" alt="image" src="https://github.com/microsoft/TypeScript-TmLanguage/assets/44799944/b229a618-8ed5-4733-81ac-2f26d8c3bc64">

**Comment by myfonj** [comment]
+1. Rephrasing info from linked issue (microsoft/vscode#206516), even simple line break before closing */ of "line" JSDoc comment makes it appear like a normal insignificant comment:

```JavaScript
/** @type {string} */
var a = "OK, highlighted as JSDoc.";
/** @type {string}
*/
var b = "ERROR, highlighted like a regular comment.";
```
Produces:
![First comment is highlighted, second is not.](https://github.com/microsoft/TypeScript-TmLanguage/assets/1761395/e28f6925-cf25-4266-9961-c12c3dc3ca3a)

And this code monster demonstrating that LSP crunches it without a problem, but highlighter fails:

![JavaScript code from following snippet showing hover tooltip inside typedef proving it is processed and error lens errors after var statements.](https://github.com/microsoft/vscode/assets/1761395/712facab-53ff-4663-8b8c-7fbc2c74e7ff)

```JavaScript
// @ts-check

/** @typedef
    * {
    typeof
    * ABC [
         number
    * ]
    }
           *       Ch -
   this
 - still
 * works
*/
// ↑ ERROR, highlighted as a comment, but processed

const ABC = /** @type {const} */(["a", "b", "c"]);
	
/** @type {Ch}
*/
// ↑ ERROR, highlighted as a comment, but processed
var x = 'd';

/** @type {Ch} */
// ↑ OK, highlighted
var y = 'd';
```
