### ISSUE TITLE
Bitwise Shift in For Loop Breaks Syntax Highlighting

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript-TmLanguage#469]
From https://github.com/Microsoft/vscode/issues/28167

**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:**  0.0.21

**Code**

```ts
for (var i = 0, length = 10; i < length >> 0; ++i) {
	var a = 10
} 
```

<img width="470" alt="screen shot 2017-06-07 at 10 16 06 am" src="https://user-images.githubusercontent.com/12821956/26891582-643fc278-4b6a-11e7-9df0-c258f3efa34d.png">

**Comment by sheetalkamat** [comment]
This doesn't repro in grammar from latest master branch. The extension is not updated yet and I will update it soon.
