### ISSUE TITLE
Highlighting fails when generic type declaration spans many lines

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript-TmLanguage#475]
**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:**  0.0.22 / latest

From https://github.com/Microsoft/vscode/issues/29135

**Code**

Using the typescript react gammar:

```ts
const connectedComponent = connect<
	ApplicationState,
	Dispatch<TodoAction>,
	HomeComponent
>(mapStateToProps, mapDispatchToProps)(Home);
```

Elements after `Dispatch<` are marked as a tsx component and not highlighted properly:

![screen shot 2017-06-20 at 1 46 04 pm](https://user-images.githubusercontent.com/12821956/27355163-d148c8d4-55be-11e7-91ac-88072c82e535.png)

**Comment by sheetalkamat** [comment]
This is by design as the grammar lookup doesn't allow multiple lines at a time. Hence at location connect < cannot be determined as type parameter.

**Comment by vjeux** [comment]
JSX doesn't allow any [a-z] character before the `<` for the outer one, so `Dispatch<TodoAction>` cannot be a JSX element. Is there a way to encode this inside of the TmLanguage format?

**Comment by sheetalkamat** [comment]
But the < could be less than operator.

**Comment by vjeux** [comment]
That's true but I don't really understand why it's an issue here. In this case, `<TodoAction>` is being  recognized as a JSX element. In the JSX element detection, could you ensure that the previous character is not `[a-zA-Z_$]`?

**Comment by sheetalkamat** [comment]
@vjeux yes that can be done, but please open another issue with valid code that is broken. Thanks

**Comment by ghost** [comment]
For anyone else coming here from the many linked issues -- Do also despise the sheer laziness, incompetence, and idiocy of "developers" like this?

Closed because "the grammar doesn't support it".  Cool, I get that.  So how about, I dunno, *updating the fucking grammar*?

Nah, let's just let it sit as a persistent issue that annoys every TS dev for a decade.  That's much better!

**Comment by ghost** [comment]
Legitimately criticize the TS team for being to lazy to do their literal jobs, get marked as abuse!  What a pathetic joke you all are.
