### ISSUE TITLE
Generic type parameters do not highlight when multiline

### ISSUE THREAD

**Issue by AlexanderOtavka** [Microsoft/TypeScript-TmLanguage#479]
**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:**  0.0.22 / latest

**Code**

```ts
const withConnect = connect<
  StateProps,
  DispatchProps,
  Props
>((state: StateModel) => ({
  list: state.rides.list,
}))
```

In vscode, we get the following highlighting:

<img width="275" alt="screen shot 2017-06-26 at 12 08 32 pm" src="https://user-images.githubusercontent.com/8042691/27556070-faeb1e22-5a68-11e7-89cf-f7a78b8ac85b.png">

It drops the yellow of the function name, as well as the teal of the type params that we would expect when it is all on one line.

**Expected highlight colors**

<img width="743" alt="screen shot 2017-06-26 at 12 15 32 pm" src="https://user-images.githubusercontent.com/8042691/27556128-397edb2e-5a69-11e7-88a6-f7ce5e702c11.png">

**Comment by AlexanderOtavka** [comment]
Whoops, looks like this is a duplicate of #475

**Comment by AlexanderOtavka** [comment]
Actually, after reading the full comment chain of #475, I'm reopening this since my code is actually valid.

**Comment by sheetalkamat** [comment]
As mentioned in https://github.com/Microsoft/TypeScript-TmLanguage/issues/475#issuecomment-309905772 this is by design.

**Comment by AlexanderOtavka** [comment]
Ok, that comment chain was a bit confusing.  Are there future plans to fix the grammar so it works over multiple lines?  It's kind of annoying having syntax highlighting break for multiline expressions.

**Comment by sheetalkamat** [comment]
It cant be fixed to lookup over multiple lines as that's the limitation of tmLanguage syntax.

**Comment by AlexanderOtavka** [comment]
Gotcha.  Sorry for the confusion.
