### ISSUE TITLE
@augments type not highlighted 

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript-TmLanguage#483]
**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:**  0.0.22 

**Code**

```ts
/**
 * @augments {{ prop: Foo2 }}
 */
class K { }
```

<img width="362" alt="screen shot 2017-07-06 at 5 26 06 pm" src="https://user-images.githubusercontent.com/12821956/27938037-372dd67c-6270-11e7-930c-e0d4b54a4062.png">

The ` {{ prop: Foo2 }}` is not syntax highlighted like types for `@param` are.

This seems to be fixed in atom. I'll look into updating the jsdocs grammar from atom/language-javascript

**Comment by sheetalkamat** [comment]
This is not fixed in atom/language-javascript.
