### ISSUE TITLE
Incorrect Highlighting after string containing <

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript-TmLanguage#487]
From: https://github.com/Microsoft/vscode/issues/30615

**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:**  0.0.22

**Code**

```ts
var x = { '01': '<' }; console.log('c', x);
```

<img width="399" alt="screen shot 2017-07-13 at 1 32 58 pm" src="https://user-images.githubusercontent.com/12821956/28186382-cddbd90c-67cf-11e7-802a-cb30e4da0d9b.png">

Expected highlighting:

<img width="361" alt="screen shot 2017-07-13 at 1 33 14 pm" src="https://user-images.githubusercontent.com/12821956/28186394-d4ea5836-67cf-11e7-840e-e6c1bfa85d64.png">

**Comment by mjbvz** [comment]
In the error case, the scope of `console` is:

- entity.name.function.ts
- meta.definition.method.ts
- meta.method.declaration.ts
- meta.objectliteral.ts
- meta.var.expr.ts
- source.ts

in the second case, it is:

- support.class.console.ts
- meta.function-call.ts
- source.ts

**Comment by sheetalkamat** [comment]
This doesn't repro
![capture](https://user-images.githubusercontent.com/8052792/28225987-50a832cc-6889-11e7-8076-1e6e6706f9c8.JPG)
