### ISSUE TITLE
The "cursor" property is given selector style in LESS files

### ISSUE THREAD

**Issue by JamesDonnelly** [Microsoft/TypeScript-TmLanguage#492]
I've only noticed this happening today, so I'm not sure if the latest VSCode update has introduced this bug (I'm running 1.14.0).

![Image](http://i.imgur.com/Z2nE8VC.png)

**Comment by sheetalkamat** [comment]
Can you please provide the code sample.. It would be needed to investigate this correctly.

**Comment by JamesDonnelly** [comment]
@sheetalkamat I'm able to reproduce this anywhere the cursor property is defined.

1. Create a file with the .less extension or change the language to LESS.
2. Use the following CSS:

```css
div {
  cursor: pointer;
  color: tomato;
}
```

This is the result I'm seeing (I'm now using 1.16.0):

![https://i.imgur.com/4Mhs9SH.png](https://i.imgur.com/4Mhs9SH.png)

This does not apply to files marked as using the CSS language, only LESS.

**Comment by sheetalkamat** [comment]
The grammar in this repo is used for javascript and typescript files. Moving this vscode repo.
