### ISSUE TITLE
Angular 2 / 4 decorators inside doc comments are not not properly highlighted

### ISSUE THREAD

**Issue by distante** [Microsoft/TypeScript-TmLanguage#493]
**Version**
  0.0.23

**Code**
```
/**
 *
 * @Input {boolean} [isTappable = true] , defines if the card will have the tappable attribute.
 * @Input {string} title , the title text.
 * @Input {string} description , the description text.
 * @description  this is my description 
 * 
 */
```
![screen shot 2017-08-01 at 10 19 00](https://user-images.githubusercontent.com/5490201/28815945-5758b9ac-76a3-11e7-8109-8c71becc0dff.png)

![screen shot 2017-08-01 at 10 19 30](https://user-images.githubusercontent.com/5490201/28815947-597267b0-76a3-11e7-87db-0d5eae04d4ec.png)

`@Input `should also be bluish like  `@description`

**Comment by sheetalkamat** [comment]
We don't do anything special here.. And use the jsdoc syntax from https://github.com/atom/language-javascript. Please file the issue there to see it fixed. thanks.
