### ISSUE TITLE
Colouring for text inside string template.

### ISSUE THREAD

**Issue by NoelAbrahams** [Microsoft/TypeScript-TmLanguage#501]
TS Version 2.4.1

![image](https://user-images.githubusercontent.com/1106823/29362174-c4a965c0-8282-11e7-8ddc-4687354955ef.png)

It's probably debatable, but I  think the `foo` should be coloured as text.

**Comment by sheetalkamat** [comment]
![501repro](https://user-images.githubusercontent.com/8052792/30399471-aa7f71c8-9888-11e7-879c-12093010723f.JPG)
Grammar and theme seem to work correctly

**Comment by NoelAbrahams** [comment]
It's not working in Visual Studio 2017.

**Comment by NoelAbrahams** [comment]
@sheetalkamat, can you please re-open this. thanks.

**Comment by sheetalkamat** [comment]
We have updated the grammar in VS with the latest and should be fixed now
