### ISSUE TITLE
Better Support for injecting grammars into template strings

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript-TmLanguage#503]
From: https://github.com/Microsoft/vscode/issues/5961

**Problem**
Many frameworks are using tagged template strings to embed other languages or construct domain specific languages. It is currently difficult to inject a grammar for these embedded languages into the the template string grammar

**Proposal**
Split the template string grammar element to better support injection. I'll submit a PR with this shortly

**Comment by mjbvz** [comment]
I've found a way to this without changing the grammar: https://github.com/mjbvz/vscode-js-template-string-grammar-injection-example

The solution was to introduce a noop rule that always consumes something inside the template string. I'll investigate to see if we can fix our engine to not require this

**Comment by xgqfrms** [comment]
https://github.com/xgqfrms/vscode/issues/8
