### ISSUE TITLE
Parameter types are not coloured if a newline is inserted before the first parameter

### ISSUE THREAD

**Issue by rcjsuen** [Microsoft/TypeScript-TmLanguage#507]
- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:16:18.034Z)
- OS Version: Windows_NT x64 10.0.14393
---
Create this TypeScript file in VS Code.
```TypeScript
let ok: any = {
    func: (x: any, y: any): void => {
    }
}

let bug: any = {
    func: (
        x: any, y: any): void => {
    }
}
```
Note that the syntax highlighting is not quite right. You can even see in the above example that GitHub's Markdown syntax highlighting is also off.

![image](https://user-images.githubusercontent.com/15629116/29688037-4f7e161e-8959-11e7-9ac7-3bf729aa031e.png)

**Comment by sheetalkamat** [comment]
This is by design and because of limitation of tmLanguage grammar syntax being not able to lookup multiple lines at once... So when looking at ( on the line of func we cant predict it being arrow and not just expression in parenthesis...

**Comment by sheetalkamat** [comment]
Released [VS Code Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version 0.0.33 that contains #552 which should address issues reported here. After letting it bake in that extension for 2-3 weeks, I could merge #552
