### ISSUE TITLE
Please consider colourising aliases (Visual Studio)

### ISSUE THREAD

**Issue by NoelAbrahams** [Microsoft/TypeScript-TmLanguage#509]
In the image below, I would like to see `bar` in `var b: bar.Baz` to have colour.

![image](https://cloud.githubusercontent.com/assets/1106823/7299670/35acd42c-e9cf-11e4-8f7e-90732cca885f.png)

The alias declaration itself should also be colourised: `import bar /*here*/ = foo.bar`

**Comment by NoelAbrahams** [comment]
Copied from Microsoft/TypeScript#2890

**Comment by mhegazy** [comment]
The TM language is just does the syntax. the semantic based colorization (e.g. classes vs variables) is done through the TS language service.
