### ISSUE TITLE
Class property types without semi-colons break highlighting

### ISSUE THREAD

**Issue by OttoRobba** [Microsoft/TypeScript-TmLanguage#51]
![typescript_bug](https://cloud.githubusercontent.com/assets/597287/12439488/51834f5e-bf18-11e5-97c1-b602b5c6a5bb.png)

In this example, x, y and constructor will not be properly colored. As you add in semi-colons, their highlighting is fixed.

Happens in Atom, Visual Studio Code.

Original bug: https://github.com/TypeStrong/atom-typescript/issues/820

**Comment by zhengbli** [comment]
Should be fixed with #48
