### ISSUE TITLE
Total breakdown of syntax highlighting with ES6 factory functions

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript-TmLanguage#510]
_From @David-Else on September 1, 2017 9:47_

- VSCode Version: 1.15.1
- OS Version: Fedora 26

Steps to Reproduce:

1. copy the code pasted below into vscode with Javascript as the language
2. observe the syntax highlighting fail

Please see the attached screen dump
![broken](https://user-images.githubusercontent.com/12832280/29964659-b1160702-8f02-11e7-939b-a5fb0de86590.png)

Reproduces without extensions: Yes

```js
    // Factory functions

    const createZombie = ({
        status = 1,
        width = 10,
        height = 10,
        xPosition,
        yPosition,
        color = "green"
    }) => ({
        status,
        width,
        height,
        xPosition,
        yPosition,
        color
    });

    const createHero = ({
        status = 1,
        width = 25,
        height = 50,
        xPosition,
        yPosition,
        color = "red"
    }) => ({
        status,
        width,
        height,
        xPosition,
        yPosition,
        color
    });
```

_Copied from original issue: Microsoft/vscode#33664_

**Comment by mjbvz** [comment]
This is a similar issue to #481 and some others. We currently do not handle multiline arrow function declarations well

**Comment by David-Else** [comment]
Thanks for your explanation. Hope it gets sorted soon, it look dreadful inside VSCode like that and is causing bad vibrations inside the editor.
