### ISSUE TITLE
u flag in regex breaks highlighting

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript-TmLanguage#513]
**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:**  0.0.22 / latest

**Code**

```ts
(/a/u);
```

**Comment by David-Else** [comment]
Fantastic, great work! So my issue 'Total breakdown of syntax...' is fixed :) Any idea how long till this fix shows up in vscode?
