### ISSUE TITLE
Hang on jsdoc comment with default value

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript-TmLanguage#515]
**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:**  0.0.22 / latest

From https://github.com/Microsoft/vscode/issues/34164

**Code**

```ts
/**
 * @param {boolean} [settings.debug= - Print getUpdate results in console.
 */
```

**Bug**
Grammar hangs while parsing

**Comment by sheetalkamat** [comment]
Note as discussed in the PR, we get our jsdoc grammar from https://github.com/atom/language-javascript
