### ISSUE TITLE
Support option chaining syntax highlighting

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript-TmLanguage#522]
**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:**  0.0.22 / latest

From https://github.com/Microsoft/vscode/issues/34776#event-1259771216

**Feature request** 
Support highlighting the proposed [option chaining](https://github.com/tc39/proposal-optional-chaining) syntax for JS/TS

```ts
const a = {
  b: {
    c: {
      d: {
        e: 1,
        g: [1, 2, 3],
      },
    },
    f: null,
  },
};

const brokenSyntaxHighlighting = () => {
  const array = a?.b?.c?.d?.g;

  /**
   * No TypeEror, but syntax highlighting is broken
   */
  const test = a?.b?.f?.f;

  for (let i = 0; i < array.length; i++) {
    console.log(array[i]);
  }
};

brokenSyntaxHighlighting();
```

![30707451-31af05c4-9f04-11e7-9b4f-12e6ff3ad2f8](https://user-images.githubusercontent.com/12821956/30709245-72ca5908-9eb6-11e7-8a41-5ecba2d79816.png)

TS support for this is tracked by: https://github.com/Microsoft/TypeScript/issues/16

**Comment by sheetalkamat** [comment]
This feature is still in stage 1. Will look at it once it gets into stage 3

**Comment by zalishchuk** [comment]
@sheetalkamat Is it really hard to implement syntax support for this feature? We have to use something like [idx](https://github.com/facebookincubator/idx) for these purposes which is not always convenient.

**Comment by oychao** [comment]
I need this very hardly.

**Comment by zalishchuk** [comment]
@sheetalkamat can you please update https://github.com/sheetalkamat/TypeScript-TmLanguage-VsCode Visual Code extension?

**Comment by fungilation** [comment]
Time to revisit this, with React Native 56 turning integrating optional chaining support, now in babel 7.

This is the best thing about coffeescript and so much more convenient than the verbose alternative. But broken syntax highlighting in VSCode is getting in the way of full adoption.

**Comment by mehulmpt** [comment]
Well currently you can sort of get around this by disabling VSCode's internal javascript linter and using something like eslint, but obviously you lose some features of vscode linter like dimming of unused variables/imports, etc.

**Comment by fungilation** [comment]
I see in my VSCode default config:
```
"eslint.enable": true,
```

Which tells me eslint is already the default VSCode linter? If not, how would you turn off the internal js linter?

**Comment by mjbvz** [comment]
This repository only handles syntax coloring. Semantic understanding of chaining is tracked by https://github.com/Microsoft/TypeScript/issues/16

**Comment by jabsatz** [comment]
Babel 7 has been released with the optional chaining operator as a plugin, is there any chance of revisiting this?

**Comment by daix6** [comment]
> This feature is still in stage 1. Will look at it once it gets into stage 3

It's time!!

**Comment by bondparkerbond** [comment]
Optional Chaining is officially in [Stage 3](https://github.com/tc39/proposal-optional-chaining). Should this issue be reopened?

**Comment by spassvogel** [comment]
Please consider to implement this.

**Comment by orta** [comment]
I agree, I think it's time this should get re-opened

**Comment by unbug** [comment]
wow, it's been years everyone, especially react devs are tortured by the progress.

**Comment by pirix-gh** [comment]
And nullish coalescing too, a bit off topic (but the bot wont let me open an issue or comment about it) - So I just added a reminder here.

**Comment by nhardy** [comment]
Should this be reopened? It looks like #768 only added nullish coalescing support, not support for optional chaining which will land in TS3.7 on November 5th.

**Comment by sheetalkamat** [comment]
@nhardy optional chaining is supported. If you have a sample that doesnt work please open another issue with it to track it separately.
