### ISSUE TITLE
Language definitions are not correct

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript-TmLanguage#523]
_From @bsvipas on September 22, 2017 5:32_

- VSCode Version: 1.16.1
- OS Version: macOS 10.12.6

```javascript
function download() {
	const a = document.createElement('a');
	a.href = ''; // href: support.variable
	a.target = ''; // target: support.variable
	a.download = ''; // download: variable.other (THIS IS BAD!)
}
```

```javascript
window.navigator.userAgent.toLowerCase(); // navigator: variable.other (THIS IS BAD!)
window.location.href = '' // Here everything is good, all are support.variable
```

Even GitHub doesn't have proper language definitions and it doesn't colorize these properties 😄 

To see it I used `Developer: Inspect TM Scopes`.

This is a little bit annoying, because it's hard sometimes to read code when code coloring is different, because of bad language definitions theme authors can't fix it.

_Copied from original issue: Microsoft/vscode#34804_

**Comment by mjbvz** [comment]
_From @tomas-cimermonas on September 22, 2017 5:52_

I've faced same issue with properties. Looking for solution.

**Comment by mjbvz** [comment]
Looks like we hardcode a bunch of dom symbol and property names and treat these specially. I propose we either:

1. Remove most of these these because the DOM is just another API 
1. Ensure all of these special cases only tack on additional scopes to properties and variables

**Comment by sheetalkamat** [comment]
@mjbvz This is by design though.. Most of the grammars for javascript scope these properties as we do.. We have used the same scope matching as what atom/language-javascript does

**Comment by mjbvz** [comment]
@bsvipas + @tomas-cimermonas Looks like Atom has the same behavior and that most themes work around this if they don't want dom properties colored differently. Can you do the same?

**Comment by bsvipas** [comment]
@mjbvz What do you mean by do the same? To not color DOM properties?

**Comment by sheetalkamat** [comment]
@bsvipas In the theme set the color for ```support.variable``` to be same as ```variable.other```
