### ISSUE TITLE
standard color of function name is ignored when the arguments is on new line

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript-TmLanguage#524]
_From @isaklafleur on September 22, 2017 9:1_

- VSCode Version:
- OS Version:

Steps to Reproduce:

**I'm using prettier extension and it recommends to break on to separates lines. VSC don't color the variable name according to function color if the arguments are not on the same line.**

Paste this in editor and you will see the standard function variable color does appear on function `findAbbreviations`, but not on `replaceAbbreviationsWithExpansions` 

```js
const findAbbreviations = (string, arrayOfAbbreviations) => {
  const stringArray = stringSplit(string);
  const abbreviationMatches = [];
  arrayOfAbbreviations.forEach(item => {
    if (stringArray.indexOf(item.abbreviation) >= 0) {
      abbreviationMatches.push({
        abbreviation: item.abbreviation,
        expansion: item.expansion
      });
    }
  });
  return abbreviationMatches;
};

const replaceAbbreviationsWithExpansions = (
  string,
  abbreviations,
  findAbbreviations
) => {
  if (findAbbreviations.length > 0) {
    const abbreviationMatches = findAbbreviations(string, abbreviations);
    let newString = string;
    abbreviationMatches.forEach(item => {
      newString = newString.replace(item.abbreviation, item.expansion);
    });
    return newString;
  } else {
    return string;
  }
};
```

Reproduces without extensions: Yes/No
Yes

_Copied from original issue: Microsoft/vscode#34813_

**Comment by mjbvz** [comment]
Simpler repo:

```js
const f1 = (x) => { }
const f2 = (
    x
) =>  {}
```

<img width="193" alt="screen shot 2017-09-22 at 2 07 30 pm" src="https://user-images.githubusercontent.com/12821956/30764364-671952b4-9f9f-11e7-85dd-0f49172e3741.png">

Scope of `f1` is:

```
entity.name.function.js
meta.definition.variable.js
meta.var-single-variable.expr.js
meta.var.expr.js
source.js
```


Scope of `f2` is:

```
variable.other.readwrite.js
meta.definition.variable.js
meta.var-single-variable.expr.js
meta.var.expr.js
source.js
```

**Comment by sheetalkamat** [comment]
This is by design since on line 1 we cannot recognize the assignment to f2 as lambda expression

**Comment by sheetalkamat** [comment]
Released [VS Code Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version 0.0.33 that contains #552 which should address issues reported here. After letting it bake in that extension for 2-3 weeks, I could merge #552
