### ISSUE TITLE
Template strings within an expression aren't highlighted

### ISSUE THREAD

**Issue by sompylasar** [Microsoft/TypeScript-TmLanguage#527]
**[atom-typescript](https://github.com/TypeStrong/atom-typescript) version:**  [11.0.9 (latest)](https://github.com/TypeStrong/atom-typescript/blob/v11.0.9/grammars/ts.cson)

Downstream issue: https://github.com/TypeStrong/atom-typescript/issues/1174
<img width="299" src="https://cloud.githubusercontent.com/assets/7235240/21953007/6178e556-d9e1-11e6-85c5-67075fbd59eb.png">

**Code**

Has the issue:
```ts
  const pgsqlQueryTemplate = (
    `INSERT INTO ${inputs.pgsqlTableFullName}
    (${pgsqlFieldNamesQuoted.join(', ')})
    VALUES
    (${pgsqlFieldNamesVariables.join(', ')})
    ON CONFLICT (${keyFieldNamesQuoted.join(', ')})
    DO UPDATE SET ${pgsqlUpdateAssignments.join(', ')}`
  );
```
<img width="476" alt="screen shot 2017-10-03 at 12 46 57 pm" src="https://user-images.githubusercontent.com/498274/31145574-fbdbce30-a838-11e7-82b4-fc0f33f3a500.png">
<img width="484" alt="screen shot 2017-10-03 at 12 47 54 pm" src="https://user-images.githubusercontent.com/498274/31145618-1f304bea-a839-11e7-8d5f-c34441e2b987.png">

Has the issue as well:
```ts
  const pgsqlQueryTemplate = (
    `INSERT INTO ${inputs.pgsqlTableFullName} ` +
    `(${pgsqlFieldNamesQuoted.join(', ')}) ` +
    `VALUES ` +
    `(${pgsqlFieldNamesVariables.join(', ')}) ` +
    `ON CONFLICT (${keyFieldNamesQuoted.join(', ')}) ` +
    `DO UPDATE SET ${pgsqlUpdateAssignments.join(', ')}`
  );
```

No issue:
```ts
  const pgsqlQueryTemplate = `INSERT INTO ${inputs.pgsqlTableFullName}
    (${pgsqlFieldNamesQuoted.join(', ')})
    VALUES
    (${pgsqlFieldNamesVariables.join(', ')})
    ON CONFLICT (${keyFieldNamesQuoted.join(', ')})
    DO UPDATE SET ${pgsqlUpdateAssignments.join(', ')}`;
```
<img width="612" alt="screen shot 2017-10-03 at 12 48 37 pm" src="https://user-images.githubusercontent.com/498274/31145653-39d9fe1e-a839-11e7-858f-543e49879dd4.png">
<img width="476" alt="screen shot 2017-10-03 at 12 50 38 pm" src="https://user-images.githubusercontent.com/498274/31145751-83260c98-a839-11e7-88f6-50b7f760dc06.png">

**Comment by sheetalkamat** [comment]
This does not repro on main branch of this grammar.. (In vscode without any other extension but latest grammar of typescript)

**Comment by sompylasar** [comment]
@sheetalkamat Thanks for checking, this looks like `atom-typescript` [should be updated](https://github.com/TypeStrong/atom-typescript/issues/1174#issuecomment-334248038).

Verified in the latest VSCode:
<img width="409" alt="screen shot 2017-10-04 at 11 33 47 am" src="https://user-images.githubusercontent.com/498274/31193077-ec2e5178-a8f7-11e7-9488-d714d567fc30.png">
