### ISSUE TITLE
[Visual Studio] No colour for `this` in spread operator

### ISSUE THREAD

**Issue by NoelAbrahams** [Microsoft/TypeScript-TmLanguage#528]
**TS Version**: 2.5.3
**Visual Studio**: Community 2017 Preview (2)

![image](https://user-images.githubusercontent.com/1106823/31176825-197a9a74-a90c-11e7-9d78-4a697c2e409c.png)

The same snippet in the playground is correctly colourised.

**Comment by sheetalkamat** [comment]
The grammar file from here is updated for VS drop and should work in next update/release
