### ISSUE TITLE
Need support for JSX Fragment Syntax

### ISSUE THREAD

**Issue by uniqueiniquity** [Microsoft/TypeScript-TmLanguage#534]
**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:**  0.0.22 / latest
JSX is adding support for fragment syntax. For more info, see https://github.com/facebook/jsx/pull/93.

**Code**

```ts
// Need to highlight the following as JSX tags
<></>;
<><span></span><><span></span></></>;

```

**Comment by sheetalkamat** [comment]
Fixed in #535
