### ISSUE TITLE
Mark jsdoc types with meta.embedded

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript-TmLanguage#537]
**Problem**
Quick suggestions do not currently appear when typing in jsdoc type fields:

```ts
/**
 * @param {|} x
 */
function foo(x) { }
```

This is because vscode sees the `comment` scope of the jsdoc type and disables quick suggestions here.

**Proposed Fix**
https://github.com/Microsoft/vscode/issues/34857 uses the `meta.embedded` scope to re-enable quick suggestions inside of JS/TS strings or comments. If we mark all jsdoc type fields as `meta.embedded.inline.typescript`, quick suggestions will show up

**Comment by mjbvz** [comment]
Will look into submitting this fix upstream against atom-javascript where we get the jsdoc grammar from

**Comment by Alhadis** [comment]
> This is because vscode sees the comment scope of the jsdoc type and disables quick suggestions here.

Do your scope selectors work like ours? If so, it's a simple addition to hide unwanted suggestions:

~~~~.diff
-comment.line
-comment.block
+comment.documentation
~~~~

I'm guessing something like that *should* work...?

**Comment by mjbvz** [comment]
@Alhadis We look at the entire scope stack. For code:

```js
/**
 * @type {foo}
 */
```

`foo` is scoped as:

```
entity.name.type.instance.jsdoc
comment.block.documentation.js
source.js
```

Since there is a comment scope in the stack, we disable quick suggestions here currently. 

If the stack had a `meta.embedded`:

```
entity.name.type.instance.jsdoc
meta.embedded.js
comment.block.documentation.js
source.js
```

that would override this behavior and turn quick suggestions back on

**Comment by mjbvz** [comment]
We added a way to explicitly override the token kind (string vs comment vs language) per scope in VS Code: https://github.com/Microsoft/vscode/commit/d74145ed7817fd07335b5308c31a31f0ed503c04

This accomplishes the same thing as using `meta.embedded` so I'm closing this issue
