### ISSUE TITLE
Incorrect javascript syntax highlighting for destructored function parameters in arrow functions

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript-TmLanguage#540]
_From @tomsiwik on November 8, 2017 15:48_

- VSCode Version: 1.17.2
- OS Version: Ubuntu 14.04 x64

Steps to Reproduce:

1. Change color-scheme to monokai (best to showcase as default scheme doesn't highlight this part)
2. Compare syntax-highlighting for the following methods:

```javascript
// 1. Correct highlighting
doSomething = (param, { a = "default" } = {}) => {
    //noop
}

// 2. Incorrect highlighting
doSomething = (param, { 
    a = "default" 
} = {}) => {
    //noop
}

// 3. Correct highlighting
doSomething(param, {
    a = "default"
} = {}) {
    //noop
}

// 4. Correct highlighting
doSomething(param, { a = "default" } = {}) {
    //noop
}

// 5. Correct highlighting (notice config module)
doSomething(param, {
    a = config.get("a") 
} = {}) {
    //noop
}

// 6. Correct highlighting (notice config module)
doSomething(param, { a = config.get("a") } = {}) {
    //noop
}

// 7. Incorrect highlighting (notice config module) while 1. does
doSomething = (param, { a = config.get("a")  } = {}) => {
    //noop
}
```

I'm surprised this even breaks github's code highlighting. Does this belong here what syntax highlighter does vscode and github use that behaves the same?

Reproduces without extensions: Yes

_Copied from original issue: Microsoft/vscode#37829_

**Comment by mjbvz** [comment]
This is a similar issue to #481 and #539 and some others. We currently do not handle multiline arrow function declarations well

**Comment by tomsiwik** [comment]
Hey thanks. Can I ask why this is typescript related and what syntax highlighter is used that causes this same issue in github's markdown? Is typescript's syntax highlighter the same as native js in vscode?

**Comment by mjbvz** [comment]
Our JavaScript grammar is just a modified version of the TypeScript grammar from this repo. I can't speak to what github does but in general JavaScript's syntax can making parsing ambiguous cases like arrow functions difficult, especially when these are split over multiple lines

**Comment by sheetalkamat** [comment]
Case 7 is now fixed but Case 2 will remain broken because of tmLanguage grammar not being able to lookup beyond current line.

**Comment by tomsiwik** [comment]
Thanks a lot for looking at it. I appreciate the nice answers :)
