### ISSUE TITLE
Wrong TypeScript syntax highlighting

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript-TmLanguage#543]
_From @PiranhaGreg on November 18, 2017 22:51_

- VSCode Version: 1.18.1 x64
- OS Version: Windows 10 Pro, Version 1709, Build 16299.64

Steps to Reproduce:

![vscode](https://user-images.githubusercontent.com/3635737/32985395-174e67cc-ccba-11e7-8fa4-24dbf038feb4.png)

Reproduces without extensions: Yes

Everything important is in the screenshot. Minus sign cause bad coloring of data type...

_Copied from original issue: Microsoft/vscode#38703_

**Comment by mjbvz** [comment]
_From @sagea on November 19, 2017 7:50_

I found what was wrong and will put in a PR here shortly

**Comment by lmcarreiro** [comment]
Is this problem the same as https://github.com/Microsoft/TypeScript/issues/20133 ?

```ts
  <number>1 && <number>2 & <number>3 | <number>4 + <number>5 ^ <number>6 && (<number>5)
//              ~~~~~~      ~~~~~~      ~~~~~~      ------      ~~~~~~        ------
//                                                  ok here, after '+'        ok here, after '('
```
