### ISSUE TITLE
Improper class method name highlighting

### ISSUE THREAD

**Issue by JNaftali** [Microsoft/TypeScript-TmLanguage#544]
**[TS and JS Grammar Extension](https://atom.io/packages/atom-typescript) version:**  latest

**Code**

```ts
class foo {
  method() {
  }
}
```
In the above example 'method' is not highlighted

**Comment by sheetalkamat** [comment]
This works fine in vscode...
![544](https://user-images.githubusercontent.com/8052792/33444414-18f67030-d5af-11e7-9bf6-ab39748cc016.JPG)

**Comment by damieng** [comment]
The description for the project states;

>This repository contains TmLanguage files that are consumed by TypeScript editors and plugins such as Visual Studio Code, The TypeScript Sublime Plugin, Atom TypeScript, and possibly others.

Right now unless I misunderstand things having those spaces in the names prevents correctly being used in any other editor?
