### ISSUE TITLE
Do not mark string template tag as being in a string scope

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript-TmLanguage#546]
**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:**  0.0.22 / latest

From https://github.com/Microsoft/vscode/issues/37176

**Problem**
For the code:

```ts
foo`content`
```

`foo` is currently scoped as:

- entity.name.function.tagged-template.js
- string.template.js
- source.js

This causes VS Code to treat `foo` as string content, which then causes us not to automatically trigger suggestions for cases like:

```js
`${a|`
```

where the cursor is at `|` because we detected that the cursor is in the string:

```
a|`
```

**Possible solutions**
- Don't mark `foo` with any `string` scopes
- Mark foo as `meta.embedded`. This will reset exist string scoping

Both seem less than ideal. Not sure if there are other ways to achieve this. @alexandrudima, any thougths?

**Comment by sheetalkamat** [comment]
I think the solution needs to come from vscode instead since this is a common naming conventions for grammars out there. (eg. https://github.com/atom/language-javascript/blob/master/grammars/javascript.cson#L1396 or even in sublime for .js files which uses the default javascript grammar in sublime)

**Comment by alexandrudima** [comment]
@mjbvz I believe you have already fixed this ... ?

![image](https://user-images.githubusercontent.com/5047891/35814009-4bde3f76-0a95-11e8-8512-edbf06e89ca4.png)

**Comment by mjbvz** [comment]
@alexandrudima Sorry, the example wasn't very clear. This is specifically for the case where you have:

```js
`${|`
```

with `|` being the cursor, and then type `a` to create:

```js
`${a|`
```

At that point, we still say that `a` is a string.

**Comment by mjbvz** [comment]
Worked around with https://github.com/Microsoft/vscode/commit/eb2b0dfc20fe80c37495a9c11f52cec2073c7f34
