### ISSUE TITLE
Syntax highlighting for object properties

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript-TmLanguage#547]
_From @evenfrost on November 25, 2017 21:12_

Would be great if we had syntax highlighting for object properties. Right now it looks like this:
![object](https://user-images.githubusercontent.com/3055750/33234838-116262ee-d23e-11e7-8a30-92a42186add4.png)
And this is how `babel-sublime` handles this:
![object-2](https://user-images.githubusercontent.com/3055750/33234844-2e1ab8dc-d23e-11e7-9692-f723b34f00b1.png)
Quoted properties here are just as an example of what it looks like to be a proper syntax highlighting for such case.

_Copied from original issue: Microsoft/TypeScript-Sublime-Plugin#632_

**Comment by sheetalkamat** [comment]
We do have scoped this correctly, as in both headers and 'headers' have same scopes with exception that 'headers' has extra string scope. Themes should be able to handle that correctly.
Scope for headers:
```
Scope:                         source.ts
                               meta.var.expr.ts
                               meta.objectliteral.ts
                               meta.object.member.ts
                               meta.object-literal.key.ts
```

Scope for 'headers':
```
Scope:                         source.ts
                               meta.var.expr.ts
                               meta.objectliteral.ts
                               meta.object.member.ts
                               meta.object-literal.key.ts
                               string.quoted.single.ts
```

**Comment by evenfrost** [comment]
@sheetalkamat I see that the scopes are pretty similar but it may be better to highlight quoted and unquoted properties the same way, what do you think?

Example with default Monokai color scheme:

*TypeScript.tmLanguage*
![1](https://user-images.githubusercontent.com/3055750/33629265-7a199266-da14-11e7-90fe-ad553b8ee14d.png)

*[JavaScript (Babel).tmLanguage](https://github.com/babel/babel-sublime/blob/master/JavaScript%20(Babel).tmLanguage)*
![2](https://user-images.githubusercontent.com/3055750/33629292-8d1d4e0c-da14-11e7-9884-9a635236feb4.png)

**Comment by sheetalkamat** [comment]
And that can be achieved in the theme but thats upto the theme maker. But I think most of the editors have default theme that distinguish between the string literals (wherever they are) with any other constructs.
