### ISSUE TITLE
Typescript syntax highlighting fails for arrow functions with multiline arguments

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript-TmLanguage#550]
_From @christianbradley on December 12, 2017 18:57_

Visual Studio Code 1.18.1
Typescript 2.6.2

See example below:

```ts
export const foo = (firstVariable: string, secondVariable: number): string => {
    return "foo"
}

export const bar = (
    firstVariable: string,
    secondVariable: number,
    thirdVariable: string
): string => {
    return "baz"
}
```

_Copied from original issue: Microsoft/vscode#40129_

**Comment by mjbvz** [comment]
Duplicate of #481 I believe

**Comment by sheetalkamat** [comment]
Correct this is same as #481

**Comment by sheetalkamat** [comment]
Released [VS Code Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version 0.0.33 that contains #552 which should address issues reported here. After letting it bake in that extension for 2-3 weeks, I could merge #552

**Comment by EduardoRFS** [comment]
Same thing happen when using export default even with the extension

```typescript
// both arguments will lack color
export default (
  state: State = { rewards: [] },
  action: LoadAction | Action
) => {};

```typescript
// now it works
const defaultFunction = (
  state: State = { rewards: [] },
  action: LoadAction | Action
) => {};
```
