### ISSUE TITLE
Different color for the same thing in Monokai Dimmed

### ISSUE THREAD

**Issue by aeschli** [Microsoft/TypeScript-TmLanguage#553]
_From @usernamehw on December 8, 2017 1:59_

![dimmed](https://user-images.githubusercontent.com/9638156/33747180-833fc24c-dbd2-11e7-899c-16ec61e38465.png)

The first one has applied TM selector `variable.other.property`
The second - `variable.other`

What is it?
* Both should be pink
* Both should be blue
* As designed 

_Copied from original issue: Microsoft/vscode#39905_

**Comment by aeschli** [comment]
The JavaScript grammar seems to give the following scopes, 
`variable.other.property.js`
`variable.other.object.property.js`

Not clear why not both times `other.object.property`.
Moving to to https://github.com/Microsoft/TypeScript-tmlanguage

**Comment by sheetalkamat** [comment]
This is exactly how atom/language-javascript scopes these. Look at like https://github.com/atom/language-javascript/blob/master/grammars/javascript.cson#L1833 and https://github.com/atom/language-javascript/blob/master/grammars/javascript.cson#L1851 

Note that in ```this.$el``` we dont know if $el is object hence just ```variable.other.property``` while in ```this.$el.style``` we know $el is object hence the scope ```variable.other.object.property```

**Comment by usernamehw** [comment]
Okay. All other themes paint these 2 properties in the same color. What was meant **specifically** in `Monokai Dimmed`?
* Both should be pink
* Both should be blue
* As designed
