### ISSUE TITLE
VSCode: Regex highlighting not properly

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript-TmLanguage#560]
_From @mnp-mid on January 17, 2018 11:43_

Highlighting is not proper for regular expressions.
I am using Visual Studio Code with AngularJs + Typescript.

- VSCode Version: 1.19.2
- OS Version: Windows

Steps to Reproduce:
```
function test(str: string) {
    str.match(/a/ims);       // <- not highlighted as below
    str.match(/a/im);        // <- works good
}
```

![image](https://user-images.githubusercontent.com/33545902/35041053-b99ec5e2-fb83-11e7-83cd-e1747e13ef8e.png)

_Copied from original issue: Microsoft/vscode#41739_

**Comment by sheetalkamat** [comment]
We use the regular expression syntax from https://github.com/atom/language-javascript/ please file a bug there and report back when its fixed. thanks.
