### ISSUE TITLE
Identifier named 'type' being treated as keyword when used as function parameter

### ISSUE THREAD

**Issue by NeekSandhu** [Microsoft/TypeScript-TmLanguage#561]
**TypeScript Version:**  next

![](https://i.imgur.com/JPgAmIi.png)

[Initially, issue was filed in TypeScript repo](https://github.com/Microsoft/TypeScript/issues/21321#issuecomment-359230228)

**Comment by sheetalkamat** [comment]
![capture](https://user-images.githubusercontent.com/8052792/35408213-27f64e9e-01c3-11e8-9a04-ee47a376ea8c.JPG)
Does not repro.

**Comment by NeekSandhu** [comment]
Please try this in typescript playground which uses monaco editor

**Comment by NeekSandhu** [comment]
vscode uses advanced techniques for tokenization

**Comment by sheetalkamat** [comment]
This repository is only for the tmLanguage grammar. So this is not right place for this issue. Playground uses monaco editor and that has its own tokenization that @mhegazy might be able to help with.

**Comment by NeekSandhu** [comment]
I intially filed the issue in ts repo and was told by @mhegazy to file it here instead : /

**Comment by sheetalkamat** [comment]
> I intially filed the issue in ts repo and was told by @mhegazy to file it here instead : /

That would be because it wasnt clear that the issue repros only in the monaco editor
