### ISSUE TITLE
Broken TypeScript highlighting in Github

### ISSUE THREAD

**Issue by MartynasZilinskas** [Microsoft/TypeScript-TmLanguage#563]
**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:**  0.0.22 / latest

After Linguist release v6.0.0 TypeScript syntax highlighting broke in github. https://github.com/github/linguist/pull/4002

Screenshots:
![image](https://user-images.githubusercontent.com/562658/35443336-6606ad50-02b3-11e8-8673-21f4142c1042.png)
https://github.com/SimplrJS/ts-extractor/blob/master/README.md
![image](https://user-images.githubusercontent.com/562658/35443369-83df9044-02b3-11e8-9adb-b2f94b8f3e38.png)
https://github.com/SimplrJS/ts-extractor/blob/master/src/api-registry.ts

**Comment by sheetalkamat** [comment]
This is not the issue in the grammar. Its issue with linguist picking Yaml file where as it should be picking .tmlanguage file.. The yaml files are for helping with the edit and not supposed to be consumed anywhere outside this repository.

**Comment by MartynasZilinskas** [comment]
Thanks for fast reply. Got it. 👍
