### ISSUE TITLE
A more specific scope for `return` keyword

### ISSUE THREAD

**Issue by aziz** [Microsoft/TypeScript-TmLanguage#565]
**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:**  0.0.26 / latest

I would like to color my `return` keywords differently but unfortunately, it shares its scope with a lot of other control flow keywords. 

What I'm asking is a more specific scope for `return` keyword, something like `keyword.control.flow.return.ts` or additional scope like `keyword.control.flow.ts keyword.return.ts`

I have the same request for `constructor` method of a class, or `async` and `await` keywords

**Comment by sheetalkamat** [comment]
While this is genuine request, it creating this has very few takers. So we can reopen this if there are more takers.
