### ISSUE TITLE
Multiline arguments for const arrow function breaks the syntax highlighting

### ISSUE THREAD

**Issue by Gokuroro** [Microsoft/TypeScript-TmLanguage#574]
**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:**  0.0.22 / latest

**Code**

```ts
// Multiline for function format (OK):
function functionName(
  firstVar: string,
  secondVar: string
): string {
  return firstVar
}
```

```ts
// Singleline for arrow format (also OK):
const functionName = (firstVar: string, secondVar: string): string => firstVar;
```

```ts
// Multiline for arrow format (NOT OK):
const functionName = (
  firstVar: string,
  secondVar: string
): string => firstVar;
```

**Comment by sheetalkamat** [comment]
This is duplicate of #481 and limitation to the tmLanguage grammar syntax which cannot look ahead over multiple lines and cant lookback in multiple lines

**Comment by sheetalkamat** [comment]
Released [VS Code Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version 0.0.33 that contains #552 which should address issues reported here. After letting it bake in that extension for 2-3 weeks, I could merge #552
