### ISSUE TITLE
Flow type in template literal breaks highlighting

### ISSUE THREAD

**Issue by charles8xu** [Microsoft/TypeScript-TmLanguage#577]
From https://github.com/akamud/vscode-theme-onedark/issues/87

## Sample code
Extract from https://github.com/facebook/react/blob/master/packages/react-reconciler/src/ReactFiberClassComponent.js#L65

```javascript
function(callback: mixed, callerName: string) {
  if (callback === null || typeof callback === 'function') {
    return;
  }
  const key = `${callerName}_${(callback: any)}`;
  if (!didWarnOnInvalidCallback[key]) {
    warning(
      false,
      '%s(...): Expected the last optional `callback` argument to be a ' +
        'function. Instead received: %s.',
      callerName,
      callback,
    );
    didWarnOnInvalidCallback[key] = true;
  }
};
```

## Filename and Language selected

Using `.js` extension with `JavaScript` file type selected

## Screenshot

![image](https://user-images.githubusercontent.com/6831013/37018641-1094e7f4-2150-11e8-851e-20b86c909100.png)

## Versions used

* VSCode version: 1.20.1
* OS Version: macOS 10.13.3

**Comment by sheetalkamat** [comment]
The syntax ````${callerName}_${(callback: any)}`;``` is not a valid javascript or typescript which is what this repo supports for colorizing. You would need to have special tmLanguage to colorize this portion correctly.
