### ISSUE TITLE
`<` in conditional expression in parenthesized expression makes rest of document highlighted as a type.

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript-TmLanguage#579]
**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:**  0.0.35

**Code**

```ts
function f(x: boolean): boolean {
    const res = (
        x ? true : 1 < 2);
    return res;
}
```

**Comment by andy-ms** [comment]
There is a similar error for `=>` in a conditional expression:
```ts
function f(): (x: number) => any {
    return true ? x => f() : x => 0;
}
const x = 0; // no highlight in rest of file
```
(both of these were discovered in `checker.ts`.)

**Comment by sheetalkamat** [comment]
The first reported scenario is because of fix in #552 which is experimental support for multiline arrows where in ( with line break are treated as arrow. can you share actual code where this happens so I can see if we can make any tweaks that are meaningful

**Comment by andy-ms** [comment]
@sheetalkamat See `mappedTypeRelatedTo` in `checker.ts`.

**Comment by sheetalkamat** [comment]
Handled the repro code 1 case where in it is now restricted to few tokens only. (the repro in the bug would still behave same) 
Repro 2 is fixed . New extension version will be released to get feedback. Thank you.
