### ISSUE TITLE
Add a meta-scope to identify import paths

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript-TmLanguage#582]
**Problem**
Similar problem to #546. In VS Code, quick suggestions are currently not enabled inside of `import` paths because we treat them as strings.

**Request**
Add a new meta scope to the string contents of import paths:

```
import 'foo'
        ---
         |               
  meta.import.path
```

This would allow us to specify that `meta.import.path` tokens should actually be treated like normal language syntax for quick suggestions and other basic language features

**Comment by sheetalkamat** [comment]
One quick question why is "meta.import.ts string" scope not used instead to detect need to enable features instead of just "string"

**Comment by mjbvz** [comment]
Yes, whatever name you think would make the most sense. On the VS Code side, we just need a unique scope at the top of the stack.  This could be:

```
meta.import.X
string.quoted.single.ts
meta.import.ts
source.ts
```

or even:

```
meta.import.X.string.quoted.single.ts
meta.import.ts
source.ts
```

**Comment by sheetalkamat** [comment]
Sorry may be i wasn't clear in asking.. Does this have to be single scope name that you want to identify or it could be a scope selector?
Eg right now the scope is:
```
Scope:                    source.ts
                               meta.import.ts
                               string.quoted.double.ts
```

So scope selector ```meta.import string.quoted" would work same as making it right?:
```
Scope:                     source.ts
                               meta.import.ts
                               meta.import.path.ts
                               string.quoted.double.ts
```

**Comment by mjbvz** [comment]
Yes this would be better. Our current implementation is pretty stupid and only looks at the top level scope to determine type instead of using a selector. Since CSS and HTML will have the exact same problem for their path completions, I'll update vscode-textmate to use scopes instead
