### ISSUE TITLE
Cmd+/ to comment JSX code uses wrong comment syntax

### ISSUE THREAD

**Issue by jamesjryan** [Microsoft/TypeScript-TmLanguage#589]
**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:**  0.0.37 / latest

Use `cmd+/` shortcut on any of the lines containing JSX below.

Expected behavior: line is commented as 
```jsx
{/*<div className="App">*/}
```

Actual behavior: line is commented as 
```jsx
// <div className="App">*/}
```
**Code**

```ts
// Please include a code snippet that demonstrates the issue
import React, { Component } from 'react';

class App extends Component {
  render() {
    return (
      <div className="App">
        <header className="App-header">
          <h1 className="App-title">Welcome to React</h1>
        </header>
      </div>
    );
  }
}

export default App;
```

**Comment by andrejunges** [comment]
@jamesjryan have you figured out how to make jsx comments work with this extension installed?

**Comment by jamesjryan** [comment]
No I haven't, I've disabled this extension sadly.

**Comment by houfeng0923** [comment]
disabled is ok .  and ,  are there any other way ?
