### ISSUE TITLE
Syntax highlighting bug on type definitions without trailing semicolo

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript-TmLanguage#592]
From https://github.com/Microsoft/vscode/issues/47315

**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:**  latest

**Code**

```ts
function test() {
  type X = { }
  return {};
}
```

**Bug**
Everything after the type definition is still scoped as `meta.type.declaration.ts`:

![screen shot 2018-04-06 at 3 18 47 pm](https://user-images.githubusercontent.com/12821956/38446607-d5694226-39ad-11e8-9c6e-d643bbbfa3ba.png)

**Comment by Wedvich** [comment]
I'm seeing this issue now, could it be a regression? Should I open a new issue or should this one be reopened?

**Comment by sheetalkamat** [comment]
New one with repro code
