### ISSUE TITLE
Broken type highlighting inside of carrots

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript-TmLanguage#593]
_From @rvinzent on March 28, 2018 16:15_

Hello,

The latest update broke the type declarations after function names but before the parentheses. It only occurs when the type is an array denoted by brackets. It seems to work fine in all other cases. 

Broken:
![broken syntax highlighting](https://user-images.githubusercontent.com/34038882/38041840-a8f3c33a-3267-11e8-86d2-f79fd18a6902.JPG)

Expected:
![correct syntax highlighting](https://user-images.githubusercontent.com/34038882/38041850-b01534e6-3267-11e8-9bdc-08dfed2b9795.JPG)

Thanks!

_Copied from original issue: Microsoft/TypeScript-Sublime-Plugin#652_

**Comment by sheetalkamat** [comment]
This is fixed in latest master branch.
