### ISSUE TITLE
`f<keyof I>()` loses highlighting

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript-TmLanguage#598]
**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:**  latest

**Code**

```ts
f<keyof I>();
```

![fkeyofi](https://user-images.githubusercontent.com/19274678/38701505-e6198bcc-3e52-11e8-99c3-51edf5f873e6.jpg)

It works fine if there are parentheses around `keyof I`.

**Comment by sheetalkamat** [comment]
Fixed by f4ca5c1aaff53a45abcf842b53d2b0a5d5691096
