### ISSUE TITLE
Type parameters break highlighting

### ISSUE THREAD

**Issue by iddan** [Microsoft/TypeScript-TmLanguage#599]
**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:**  0.0.37 / latest

**Code**

```javascript
// Please include a code snippet that demonstrates the issue
export const get = <T>(
  row: number,
  column: number,
  matrix: Matrix<T>
): T | typeof undefined => {
  const columns = matrix[row];
  if (columns === undefined) {
    return undefined;
  }
  return columns[column];
};
```
<img width="273" alt="screen shot 2018-04-13 at 20 26 19" src="https://user-images.githubusercontent.com/12671072/38749062-f3302a26-3f58-11e8-881a-84fe1a022db0.png">

**Comment by sheetalkamat** [comment]
This doesnot repro.
![image](https://user-images.githubusercontent.com/8052792/38757525-35a2c30a-3f22-11e8-8692-2186e1dd63a6.png)

Are you correctly using file type to be typescript. Javascript doesnt have types and hence the coloring for above code cannot be correct as javascript.

**Comment by iddan** [comment]
I'm using flow. Can you respect `// @flow`?

**Comment by iddan** [comment]
<img width="273" alt="screen shot 2018-04-13 at 20 26 19" src="https://user-images.githubusercontent.com/12671072/38759464-bf3e2710-3f7e-11e8-85c6-60f670013730.png">

**Comment by iddan** [comment]
<img width="1078" alt="screen shot 2018-04-14 at 00 56 25" src="https://user-images.githubusercontent.com/12671072/38759476-c6870fb4-3f7e-11e8-8707-5ce6a352e087.png">

**Comment by sheetalkamat** [comment]
You would need to use some kind of extension to have flow typings colored correctly. This repo does not handle flow. It is only for Typescript and pure javascript.
