### ISSUE TITLE
TypeScript coloring off in this case

### ISSUE THREAD

**Issue by aeschli** [Microsoft/TypeScript-TmLanguage#60]
_From @bpasero on January 18, 2016 6:23_

- open src/vs/workbench/services/files/node/watcher/unix/watcherService.ts
- go to line 34
- use light theme +

![image](https://cloud.githubusercontent.com/assets/900690/12384617/5767acae-bdb4-11e5-858c-54bd1dc5aa66.png)

_Copied from original issue: Microsoft/vscode#2076_

**Comment by aeschli** [comment]
@bpasero Can you add the code snippet? Thanks!

**Comment by aeschli** [comment]
_From @bpasero on January 18, 2016 8:40_

@aeschli https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/files/node/watcher/unix/watcherService.ts#L34-L69

**Comment by sheetalkamat** [comment]
Fixed by #257
