### ISSUE TITLE
Colour mismatch in newline method parameters types and async

### ISSUE THREAD

**Issue by awwong1** [Microsoft/TypeScript-TmLanguage#600]
**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:**  0.0.39

**VS Code** 1.22.2 `3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9`

**Code**

Running the Dark theme, I see:

<img width="294" alt="screen shot 2018-04-15 at 10 45 16 pm" src="https://user-images.githubusercontent.com/2760111/38790477-bbe4987a-40fe-11e8-8386-33da1536517a.png">

```ts
const example = {
  foo: async (param1: any, param2: any, param3: any) => {
    return { param1, param2, param3 }
  },
  bar: async (
    param1: any,
    param2: any,
    param3: any
  ) => {
    return { param1, param2, param3 };
  }
}
```

Shouldn't the colours match between `async`, `any` on foo and bar?

**Comment by sheetalkamat** [comment]
This is fixed by 60cc32899e56c265a2559f86117cc50f394f26f9
