### ISSUE TITLE
Broken comment syntax highlight (JavaScript)

### ISSUE THREAD

**Issue by aeschli** [Microsoft/TypeScript-TmLanguage#61]
_From @fabiogusmao on January 22, 2016 16:11_

Just a minor issue but I noticed that if you put a comment line in the middle of a function declaration the comment line is not showing in gray.

![image](https://cloud.githubusercontent.com/assets/2974851/12515884/bf54b75c-c111-11e5-9d60-c51b9c73f8f9.png)

_Copied from original issue: Microsoft/vscode#2185_

**Comment by aeschli** [comment]
_From @fabiogusmao on January 22, 2016 20:17_

Ah yeah and it also happens that the word **default**  is not highlighted in a switch/case block.

![image](https://cloud.githubusercontent.com/assets/2974851/12521862/5c7fb190-c134-11e5-88ed-5360f1e68819.png)

**Comment by zhengbli** [comment]
This should be solved by https://github.com/Microsoft/TypeScript-TmLanguage/pull/56

**Comment by sheetalkamat** [comment]
Fixed by #257
