### ISSUE TITLE
VSCode: Syntax highlight error in JS file

### ISSUE THREAD

**Issue by PhilRB** [Microsoft/TypeScript-TmLanguage#611]
**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:**  0.0.41 / latest

**Code**
```ts
var a = (1)
var b = (
	1)
```
![code_2018-05-11_10-39-20](https://user-images.githubusercontent.com/33292978/39918176-a45e2690-5507-11e8-83b8-60903c4f304c.png)

**Comment by sheetalkamat** [comment]
This is side effect of #552 and code like you have written is mostly very rare. So will be left as is for larger benefit of being able to color the arrow functions more accurately.
