### ISSUE TITLE
Add flow comment syntax highlighting

### ISSUE THREAD

**Issue by dyst5422** [Microsoft/TypeScript-TmLanguage#621]
**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:**  0.0.41 / latest

Would love to see VSCode support flow syntax highlighting for comment annotations like Atom does.

Should be able to reference the Atom Babel grammar for this https://github.com/gandm/language-babel

Atom:
<img width="578" alt="screen shot 2018-05-31 at 6 11 46 pm" src="https://user-images.githubusercontent.com/13282627/40815845-357dd606-64fe-11e8-8f39-db3d864a5003.png">

VSCode:
<img width="547" alt="screen shot 2018-05-31 at 6 12 00 pm" src="https://user-images.githubusercontent.com/13282627/40815843-2e9482fe-64fe-11e8-9387-6cb6b129d0eb.png">

**Comment by sheetalkamat** [comment]
You can write a vscode extension that does this. This repo is only for typescript grammar.

**Comment by sheetalkamat** [comment]
https://code.visualstudio.com/docs/extensions/overview has more information on how to author vscode extension
