### ISSUE TITLE
Broken highlighting of jsx element inside array

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript-TmLanguage#624]
From https://github.com/Microsoft/vscode/issues/51171

**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:** latest

**Code**

```ts
bar => (
    [
        <Baz key={`bar-${bar.id}`} />,
        <Qux />
    ]
)
```

![screen shot 2018-06-06 at 2 45 40 pm](https://user-images.githubusercontent.com/12821956/41066852-4d6545ee-6998-11e8-8564-d706c3243a79.png)

The opening '`' for the string is not being pick up properly

**Comment by bsmith-cycorp** [comment]
The same happens with just parenths:

![infobar_react_js_ _cyc-ui](https://user-images.githubusercontent.com/25161635/50099856-b1e11400-01e4-11e9-9af2-4ed6d2f6ed56.png)

![infobar_react_js_ _cyc-ui](https://user-images.githubusercontent.com/25161635/50099826-9b3abd00-01e4-11e9-93b0-9bf7fd58dd9d.png)

**Comment by bsmith-cycorp** [comment]
For future victims of this issue, it does not exist with the "Babel JavaScript" extension
