### ISSUE TITLE
Labeled block can break highlighting for rest of file

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript-TmLanguage#625]
**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:**  latest

**Code**
For the code:

```ts
console.log(1);
foo: {
    console.log(1);
}
console.log(1);
```

<img width="333" alt="screen shot 2018-06-06 at 3 13 28 pm" src="https://user-images.githubusercontent.com/12821956/41067953-51f2ee3c-699c-11e8-9886-6b4d27d9d1c6.png">

The syntax highlighting is not applied after the end of labeled block

**Comment by intellild** [comment]
<img width="512" alt="default" src="https://user-images.githubusercontent.com/8379858/41083611-2c7047e0-6a64-11e8-805b-0f1880e65b04.png">
totally broken with plain javascript
