### ISSUE TITLE
Inconsistency between JSX and TSX

### ISSUE THREAD

**Issue by amcasey** [Microsoft/TypeScript-TmLanguage#631]
JSX
![jsx](https://user-images.githubusercontent.com/10508071/41493871-e03e4bc0-70c0-11e8-939f-c50ca4540e9f.png)

TSX
![tsx](https://user-images.githubusercontent.com/10508071/41493879-ea512416-70c0-11e8-9279-b5e3e07deda6.png)

**Comment by sheetalkamat** [comment]
can you please paste larger code sample? Tsx and Jsx both use same grammar so it would be interesting to see why colorization could be different.

**Comment by amcasey** [comment]
That was the full text.

**Comment by sheetalkamat** [comment]
Seems like some other issue to be diagnosed on vs side since vscode shows this correctly. we are scoping it correctly.

**Comment by amcasey** [comment]
I see the same.  VS has classification in .jsx and .js, but not in .tsx or .ts.  I'll investigate.

**Comment by amcasey** [comment]
I can't figure out where it's consumed, but the behavior seems to hinge on the value of the `defaultFileExtensionForGrammar` buffer property.

**Comment by amcasey** [comment]
Yep, it's a VS bug.  Sorry for the noise.
