### ISSUE TITLE
Highlighting broken when passing dynamic string properties in JSX

### ISSUE THREAD

**Issue by sambostock** [Microsoft/TypeScript-TmLanguage#633]
**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:**  0.0.42 / latest

Highlighting seems to break when using JSX, and quotes inside a property

#### Code

```typescript
console.log('working highlighting')
<Component prop={'single quotes'} />
console.log('BROKEN highlighting')
```

```typescript
console.log('working highlighting')
<Component prop={"double quotes"} />
console.log('BROKEN highlighting')
```

```typescript
console.log('working highlighting')
<Component prop={`backticks with ${interpolation}`} />
console.log('BROKEN highlighting')
```

Oddly enough though, this one works 🤔

```typescript
console.log('working highlighting')
<Component prop={`backticks`} />
console.log('WORKING highlighting')
```

Submitting this mainly because highlighting is broken on GitHub (see above 😉), and the [contribution guidelines](https://github.com/github/linguist#theres-a-problem-with-the-syntax-highlighting-of-a-file) recommend opening an issue here. Tried this out in VSCode, and the `backticks with ${interpolation}` example breaks highlighting, but the others appear to work.

**Comment by sheetalkamat** [comment]
![image](https://user-images.githubusercontent.com/8052792/42235843-d47991c8-7ead-11e8-8de8-1aac19a370e7.png)

This does not repro with latest vscode. Github uses another repository for this.

> JSX: github-linguist/language-babel

**Comment by sambostock** [comment]
Ahhh, my bad, I was going off of

> TypeScript: Microsoft/TypeScript-TmLanguage

Thanks for the quick response!
