### ISSUE TITLE
Add TextMate Scopes for eval/package

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript-TmLanguage#634]
_From @jabacchetta on July 1, 2018 16:29_

As [documented on StackOverfow](https://stackoverflow.com/questions/51110201/italicize-javascripts-reserved-keywords-in-vs-code), I was able to target all of JavaScript's reserved keywords via TextMate with the exception of two:

1. `eval` (disallowed in strict)
2. `package` (unused future keyword)

It's not clear to me whether this is something that needs to be updated in the TextMate grammar or if support just needs to be added in VS Code.

For `eval`, a `support.function.eval.js` scope appears to make sense. With `package` not actually being used yet, I'm not sure what scope that would go under.

_Copied from original issue: Microsoft/vscode#53399_

**Comment by sheetalkamat** [comment]
eval is not scoped as support.function.eval when not part of function-call in atom or sublime. package is scoped as "keyword.control" by atom/language-javascript so adding that.

**Comment by jabacchetta** [comment]
@sheetalkamat Can you clarify "when not part of function-call" when/if you have a moment.

I'd like to italicize `eval` in this statement: `console.log(eval('2 + 2'));`

Will that be possible?

**Comment by sheetalkamat** [comment]
@jabacchetta eval in your example is scoped as "support.function" just like many other grammars do and it and other support.function can only be targeted with support.function

**Comment by jabacchetta** [comment]
Would `support.function.eval` not make sense as an addition, in order to allow specifically targeting JavaScript reserved keywords as shown in my StackOverflow post?

**Comment by sheetalkamat** [comment]
That much detail is not requested enough to actually make that change. Also changing just one grammar is not enough.. People use different grammars/plugins so need to be universal change.

**Comment by jabacchetta** [comment]
Gotcha, thanks for the clarification!
