### ISSUE TITLE
Coloring broken when function is uses as an identifier

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript-TmLanguage#64]
See screenshot

![capture](https://cloud.githubusercontent.com/assets/1931590/12678270/490d3bea-c69e-11e5-8d95-a11105e29760.png)

**Comment by zhengbli** [comment]
Can you also post the code as test? It would be convenient for testing. Thanks!

**Comment by dbaeumer** [comment]
It is part of the express node module. The file is response.js
