### ISSUE TITLE
export declare class properties missing proper scopes

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript-TmLanguage#642]
From https://github.com/Microsoft/vscode/issues/55575

**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:**  0.0.43 / latest
**Code**

```ts
export declare class TestClient {
    private readonly test1;
}
```

Gets highlighted as:

![screen shot 2018-08-02 at 1 04 26 pm](https://user-images.githubusercontent.com/12821956/43580128-9c17aaea-9654-11e8-9e5d-7513ccb9e1ce.png)

Looks like the scopes of the tokens are all:

```
variable.other.readwrite.alias.ts
meta.block.ts
meta.export.ts
source.ts
```

**Comment by zelein** [comment]
@mjbvz This should only be happening due to #643. My example from Microsoft/vscode#55575 was just using this snippet as an example that the optional property was breaking multiple things.

When I paste the snippet above into a clean `.d.ts` file I do not see the highlighting issue.

**Comment by mjbvz** [comment]
Looks like there was a regression since VS Code 1.25. This was tested using the latest version of the grammar on VS Code insiders
