### ISSUE TITLE
All variable names within "export default" blocks are treated as alias real names

### ISSUE THREAD

**Issue by rmtracey** [Microsoft/TypeScript-TmLanguage#644]
**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:**  0.0.43 / latest

I originally opened up this issue in dracula/visual-studio-code#82 - @dsifford replied and suggested that this could be an issue with the JS/TS grammar.

The gist of the problem is that all variable names within an `export default` block seem to be treated as the real name of an alias, even though that might not necessarily be the case. You can see this when using the Dracula theme in VSCode - all variable names within an `export default` block will show as italicized orange characters, which is Dracula's styling for the real names of import/export aliases.

This obviously causes a lot of wonky-looking syntax highlighting for themes such as Dracula whenever you write an `export default` block that contains anything other than references to outside variables. A common case where this happens is writing single-file components in Vue, where the recommended style is to write the entire script portion of your component within an `export default` block.

**Code**

```ts
const test = {
  testFn () {
    const testVar = 'test'
    return testVar
  }
}

export default {
  testFn () {
    const testVar = 'test'
    return testVar
  }
}

```

**Screenshot**

![image](https://user-images.githubusercontent.com/3460875/43898672-90d59012-9bad-11e8-8c9e-6d7a2d14bd24.png)

**Comment by sheetalkamat** [comment]
The scope from non default testVar is: 
```
Scope:                         source.ts
                               meta.var.expr.ts
                               meta.objectliteral.ts
                               meta.method.declaration.ts
                               meta.block.ts
                               meta.var.expr.ts
                               meta.var-single-variable.expr.ts
                               meta.definition.variable.ts
                               variable.other.constant.ts
```
and the scope for testVar in default block is:

```
Scope:                         source.ts
                               meta.export.default.ts
                               meta.objectliteral.ts
                               meta.method.declaration.ts
                               meta.block.ts
                               meta.var.expr.ts
                               meta.var-single-variable.expr.ts
                               meta.definition.variable.ts
                               variable.other.constant.ts
```

I don't think there is anything here we need to do. Theme needs to handle scopes correctly instead.

**Comment by dsifford** [comment]
Thanks @sheetalkamat! :wave: :smile:   

@rmtracey  I'll check into this further on the theme side when time allows.
