### ISSUE TITLE
Comment in class export breaks highlighting

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript-TmLanguage#650]
**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:**  0.0.43 / latest

**Code**

```ts
export /* comment */ class MyClass{
...
}
```

gets highlighted as:

![screen shot 2018-08-20 at 3 19 01 pm](https://user-images.githubusercontent.com/12821956/44342791-64e66e80-a48c-11e8-8ac9-d894f18be126.png)

Syntax highlighting is lost for `class MyClass`

**Comment by Nufflee** [comment]
Doesn't even seem to work on Github.
