### ISSUE TITLE
export default interface not highlighted properly

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript-TmLanguage#653]
**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:**  0.0.43 / latest

**Code**

```ts
export default interface IFoo {
    x: string;
}
```

The contents of the interface lacks syntax highlighting:

![screen shot 2018-08-20 at 6 29 09 pm 1](https://user-images.githubusercontent.com/12821956/44353352-f7940700-a4a6-11e8-96cf-00b61335587d.png)

**Comment by gluons** [comment]
Thank you very much.

**FYI:** You can try it with my code. (https://github.com/gluons/vue-pack/blob/997ad7b69ab14b64145dfa04651ec56ab3a4cd75/packages/%40gluons/types/src/Configuration.ts)
