### ISSUE TITLE
Destructure + highlight issue for typescript 3.0.1

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript-TmLanguage#659]
_From @unional on August 23, 2018 0:26_

```ts
interface Boo {
  a: string,
  b: string
}
function foo(x) { return x }
foo(() => ({ a, b }: Boo) => {
  return a + b
})
foo(() => ({
  a, b }: Boo) => {
})
```
![image](https://user-images.githubusercontent.com/3254987/44497863-7cf6f300-a630-11e8-8469-cc54ed25be2b.png)
Note the second `Boo` highlight is incorrect.

VSCode: 1.26.1

_Copied from original issue: Microsoft/vscode#57053_

**Comment by sheetalkamat** [comment]
This is by design to avoid cases like #304 to break. Limitation of tmLanguage lookup being single line
