### ISSUE TITLE
method with keyword name highlighted as keyword if dot is on previous line

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript-TmLanguage#660]
**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:**  0.0.43 / latest

From https://github.com/Microsoft/vscode/issues/56975

**Code**

```ts
foo().
    bar().
    catch();
```

![screen shot 2018-08-23 at 11 01 05 am](https://user-images.githubusercontent.com/12821956/44515845-d825f580-a6c3-11e8-8b39-6f37eac1385b.png)

The `catch` method name is highlighted as a keyword instead of as an variable

**Comment by sheetalkamat** [comment]
This is by design because of design limitation of the tmLanguage syntax being able to lookup only single line.

**Comment by vahpetr** [comment]
Need to improve tmLanguage
