### ISSUE TITLE
Export as a  subword highlighted as a keyword

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript-TmLanguage#664]
**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:**  0.0.44 / latest

**Code**

```ts
var exporter;
exporter = {...};
```

<img width="282" alt="screen shot 2018-09-10 at 10 15 31 am" src="https://user-images.githubusercontent.com/12821956/45312992-75fe2a80-b4e2-11e8-8f78-4d5195c294bb.png">

**Comment by sheetalkamat** [comment]
Fixed by 06edc778820e153d1b071d22a67a75dbb6fc4e42

**Comment by medikoo** [comment]
VS Code August update shipped with this issue.

Is there anyway to workaround it? When we can expect this to be fixed in VS Code public version?

**Comment by sheetalkamat** [comment]
You can install [VSCode extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) to get latest grammar in the mean time.
