### ISSUE TITLE
Comment after switch statement not scoped

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript-TmLanguage#666]
From https://github.com/Microsoft/vscode/issues/58810

**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:**  0.0.45 / latest

**Code**

```ts
switch (0) // discard and renew state per mode
{
}
```

The comment is currently scoped as `switch-statement.expr.tsx` instead of as a comment

**Comment by frevds** [comment]
This is probably related to this: 

![image](https://user-images.githubusercontent.com/5341447/45640886-2906ef00-bab4-11e8-8cd8-4dab7a707233.png)

a comment following the last member in an object declaration with key=value abbreviation syntax lets the last member be unscoped.
