### ISSUE TITLE
Tests fail on Windows

### ISSUE THREAD

**Issue by damccorm** [Microsoft/TypeScript-TmLanguage#679]
**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:**  0.0.46 / latest

**Code (on Windows platform)**

```
npm install
npm run build:grammar
npm test
```

**Expected behavior**
All tests pass

**Actual behavior**
Tests fail on Windows. This is because the generated files have CRLF line endings while the existing baseline files have LF endings.

**Comment by sheetalkamat** [comment]
Should be fixed by #682
