### ISSUE TITLE
Colorization breaks in TS file

### ISSUE THREAD

**Issue by amcasey** [Microsoft/TypeScript-TmLanguage#681]
**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:**  latest, as far as I can tell

**Code**

```ts
function F() {
    a(() => //
    {
        b[0];
    });
}

function G() { }
```

Colorization stops somewhere in `F` - the `function` before `G` is not colored.

**Comment by sheetalkamat** [comment]
This is already fixed by 775080a1658f286730c647db75ecf2c1d1fcdc31
