### ISSUE TITLE
Different scoping for function that has comment in empty parameter list

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript-TmLanguage#686]
From https://github.com/Microsoft/vscode/issues/63443

**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:**  0.0.46 / latest

**Code**

For the code:

```ts
({
    a: () => { },
    b: (/**/) => { },
});
```

`a` has the scope `entity.name.function.ts` while `b` does not. This results in different coloring:

<img width="378" alt="screen shot 2018-11-20 at 2 05 38 pm" src="https://user-images.githubusercontent.com/12821956/48805861-6878d400-eccd-11e8-9940-eae1e9ed1c0f.png">

**Comment by mlostek** [comment]
Do you have to install the plugin to be able to use the fix in the future?

**Comment by sheetalkamat** [comment]
vscode picks the fixes on regular basis. (not sure about the frequency though)

**Comment by mlostekk** [comment]
any idea when this will be published?

**Comment by mjbvz** [comment]
It's already in VS Code 1.30
