### ISSUE TITLE
[javascript] switch-case `default` not highlighted.

### ISSUE THREAD

**Issue by aeschli** [Microsoft/TypeScript-TmLanguage#69]
_From @philipgiuliani on January 20, 2016 8:46_

![bildschirmfoto 2016-01-20 um 09 43 03](https://cloud.githubusercontent.com/assets/5446019/12443760/918dae04-bf5a-11e5-8fee-c4e20ee85358.png)

I think the screenshot explains itself.

_Copied from original issue: Microsoft/vscode#2120_

**Comment by aeschli** [comment]
_From @siegebell on January 22, 2016 7:34_

same with typescript (0.10.6)

**Comment by anubmat** [comment]
Looks good now. Closing Issue.
```ts
switch (keyCode) {
	case sf.key.CH_UP;
	case sf.key.N1:
		previousDate();
		break;
	case sf.key.CH_DOWN;
	case sf.key.N4;
		nextDate();
		break;
	default:
		Nav.handleKey(keyCode);
}
```
![image](https://cloud.githubusercontent.com/assets/17298501/13690941/7a17f390-e6e9-11e5-85f7-796f00f6c741.png)
