### ISSUE TITLE
Syntax highligh is broken in .ts file when using multiline <>

### ISSUE THREAD

**Issue by vityas-off** [Microsoft/TypeScript-TmLanguage#697]
Sorry if was already reported.
```js
const a = <
Object
>req.body;

console.log('Broken');
```

![dwadwa](https://i.imgur.com/ivMTfZx.png)

1.31.0-insider
ece3a90fb58986570d8afdfb16530c4dd8c743af
x64

**Comment by sheetalkamat** [comment]
This does not repro in master
