### ISSUE TITLE
Add more prototype methods to the `support.function` scope?

### ISSUE THREAD

**Issue by atomiks** [Microsoft/TypeScript-TmLanguage#699]
**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:**  0.0.47 / latest

First off, I'm not exactly sure what `support.function` as a scope is, I'm assuming it means "built-in" rather than user-defined. For example, here are some example functions that get scoped with it:

- `require()`
- `[].join()`
- `[].sort()`
- `[].slice()`
- `[].splice()`
- `{}.toString()`

But these don't get scoped with it:

- `[].map()`
- `[].filter()`
- `[].reduce()`
- `[].flat()`
- `{}.hasOwnProperty()`

Should these (and many others) get the scopes as well?

As an example, with the Atom One Dark theme, regular functions are a more regular sky blue, while these support functions are a more cyan/teal color. But it seems weird not to have all native prototype methods have the cyan/teal color.

**Comment by sheetalkamat** [comment]
We use special casing of support functions from https://github.com/atom/language-javascript . Please file issue in that repo to handle this and we would pick up the changes when available. Thanks
