### ISSUE TITLE
Digit(s) in class method return type breaks highlighting in function body

### ISSUE THREAD

**Issue by zhengbli** [Microsoft/TypeScript-TmLanguage#7]
Example:

![Screen](https://dl.dropboxusercontent.com/u/841468/external/ts-digit-highlight.png)

Also happens if I use default color scheme. Screenshots are from Sublime Text 2.0.2.

(edit: Same problem occurs in Visual Studio Code)

Ported from https://github.com/Microsoft/TypeScript-Sublime-Plugin/issues/380

**Comment by anubmat** [comment]
No longer a problem in Sublime Text 3
code snippet:
```ts
class Vector3 {
	add( scalar: number ): Vector {
		var a = 5;
		return this;
	}
}
```
![image](https://cloud.githubusercontent.com/assets/17298501/13689455/c783ae6e-e6dd-11e5-86f9-409f86210bd7.png)
