### ISSUE TITLE
Assign `type` scope for exclamation mark preceding colon

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/TypeScript-TmLanguage#701]
```ts
class Cl {
    one?: string;
    two!: string;
}
```

Some themes have different coloring for type punctuation scopes like `keyword.operator.type`. But exclamation mark stands out because it's `keyword.operator.logical`.

![screenshot 20](https://user-images.githubusercontent.com/9638156/50540165-e322f200-0b9d-11e9-9d17-c9cdce9475de.png)

It would be nice for it to have a separate scope (like question mark `keyword.operator.optional`) or at least the same as colon `keyword.operator.type`.

**Comment by josejavierpaez** [comment]
Could someone explain to me the difference between "?" and "!", obviously in this TS context

**Comment by usernamehw** [comment]
- `!:` - property is NOT optional, and you want to override TypeScript (maybe it will definitely be assigned later)
- `?:` - property is optional (can be omitted (undefined))
