### ISSUE TITLE
Inconsistent colorization of multiple const keywords in TypeScript

### ISSUE THREAD

**Issue by LukasLSC** [Microsoft/TypeScript-TmLanguage#703]
- VSCode Version: **1.30.1 (user setup)**
- OS Version: **Windows 10 Pro (Version: 1803)**

Steps to Reproduce:

1. Write a const with the **ternary operator** in it without brackets around it: https://prnt.sc/m07226.

The second const variable won't be colorized correctly. Instead, the blue color goes on the interface name.

To fix this, you can put **brackets** around the expression: https://prnt.sc/m07446.

However, I'm using the **Prettier** extension and it removes the brackets (it thinks they aren't necessary). It has to be a bug with the VS Code.

Does this issue occur when all extensions are disabled?: **Yes**

---
### EDIT

Thank you for the response! :) Seems like the issue is with the `?` operator on the next line. Both languages `TypeScript` and `JavaScript` have this issue. Check these two simple examples.

1. The `?` is **on the next line** (doesn't work - http://prntscr.com/m2d7w6):

```typescript
const addOrMinusPaddingXToCenter = 5 === 5
    ? 4
    : 0,
    
    dropdownOffset = {},
    dropdownCOverflowsRight = 4;
```

2. The `?` is **on the same line** (works - http://prntscr.com/m2d8ho):

```typescript
const addOrMinusPaddingXToCenter = 5 === 5 ? 4
    : 0,
    dropdownOffset = {},
    dropdownCOverflowsRight = 4;
```

You should be able to see the difference in colorization. I'm using the custom theme but that doesn't have any effect. Native VSCode theme has the same issue.

Also, the colorization if there is a space between variables is **disabled**. I think it's a part of this problem with the `?`, too (http://prntscr.com/m2d9pu):

```typescript
const addOrMinusPaddingXToCenter = 5 === 5 ? 4
    : 0,
    
    dropdownOffset = {},
    dropdownCOverflowsRight = 4;
```

**Comment by mjbvz** [comment]
In the first case with the `?` on the new line, `dropdownOffset` is scoped as:

- variable.other.readwrite.js
-source.js

In second (correct) case, it is coped as:


- variable.other.constant.js
- meta.definition.variable.js
- meta.var-single-variable.expr.js
- meta.var.expr.js
- source.js


Relatively few extensions seem to actually colorize these two cases differently

**Comment by sheetalkamat** [comment]
This is limitation of tmLanaguage syntax where lookups cannot span multiple lines. At the end of `5===5` there is no way of knowing that this is not a const expression without semicolon or is going to be ternary because of that, We choose safer path to end the const expression there to avoid issues when there are missing semicolons.
