### ISSUE TITLE
Inline generic definition with extends inside class

### ISSUE THREAD

**Issue by samdenty** [Microsoft/TypeScript-TmLanguage#704]
**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:**  latest

Adding the extends keyword to an inline generic type inside a class, breaks syntax for all the following code

**Code**

```ts
class A {
  public a: <T extends string>() => void

  public asd() {}
}
```

![image](https://user-images.githubusercontent.com/13242392/50729748-feaa7180-1136-11e9-9b73-495658f93404.png)
![image](https://user-images.githubusercontent.com/13242392/50729752-05d17f80-1137-11e9-9883-7865aae91aa3.png)

**Comment by sheetalkamat** [comment]
This does not repro for code from master
