### ISSUE TITLE
Errors with highlighting on generics

### ISSUE THREAD

**Issue by emckay** [Microsoft/TypeScript-TmLanguage#706]
**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:**  0.0.47 / latest

**Code**

```ts
interface TestInterface {}
const func = <T, S = {}>(str: string) => {};
const a = 1;
func<TestInterface>(`${a} good highlighting`);
// Bug 1:
func<
  TestInterface
>(`${a} bad highlighting`);
// Bug 2:
const obj = {
  test: func<
    {test: string},
    TestInterface
  >(`${a} really bad highlighting`),
};
const hello = `${a} a test string`;
```
![image](https://user-images.githubusercontent.com/899325/50940328-b2647780-143d-11e9-8f40-56762a2bfb48.png)

Not sure if these problems are the same bug or if there are two separate issues. The second example (where function is in an object and string has a backtick) is particularly bad because it breaks highlighting for the entire remainder of the file.

Thanks!

**Comment by sheetalkamat** [comment]
This is limitation of the tmLanguage syntax where in lookups are not multi line. On line func< we do not know if it is a a < b or type assertion or lambda and hence the issue.
