### ISSUE TITLE
bug: type alias for generic function type

### ISSUE THREAD

**Issue by aleclarson** [Microsoft/TypeScript-TmLanguage#707]
**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:**  0.0.47 / latest

**Code**

```ts
type F = <T extends any>() => T;

const a = 1;
```

<img width="273" alt="screen shot 2019-01-12 at 9 55 32 am" src="https://user-images.githubusercontent.com/1925840/51074719-427a0b00-1650-11e9-93c3-b9052cb294f2.png">

**Comment by sheetalkamat** [comment]
This does not repro with master

**Comment by sheetalkamat** [comment]
@mjbvz I am not sure if you need to pull master branch into vscode but this seems to work if I update locally.

**Comment by aleclarson** [comment]
When's the next expected release? Seems odd to hold back patches for weeks on end.

**Comment by mjbvz** [comment]
It's already in [latest VS Code insiders build](https://code.visualstudio.com/insiders/)

**Comment by aleclarson** [comment]
It would be nice if [this extension](https://github.com/sheetalkamat/TypeScript-TmLanguage-VsCode) was kept up-to-date with the `master` branch of this repository. Is there a reason it's not?

**Comment by aleclarson** [comment]
It would be nice if [this extension](https://github.com/sheetalkamat/TypeScript-TmLanguage-VsCode) was kept up-to-date with the `master` branch of this repository. Is there a reason it's not?

I ask, because I wouldn't have filed a pointless issue if I could test the `master` branch easier. 😄
