### ISSUE TITLE
Bad coloring of property 'Comment' in class/interface

### ISSUE THREAD

**Issue by PiranhaGreg** [Microsoft/TypeScript-TmLanguage#709]
- VSCode Version: 1.30.2
- OS Version: Windows 10.0.17763 Build 17763

1. Create new file test.ts with content
```typescript
class Test {
    test: void;
    Comment!: void;
}
```
2. Property `Comment` should have same color as property `test`.

![bug](https://user-images.githubusercontent.com/3635737/51394642-220fec00-1b3b-11e9-9578-4455f343abce.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by sheetalkamat** [comment]
This does not repro on master branch
