### ISSUE TITLE
javascript inline regex

### ISSUE THREAD

**Issue by dna2github** [Microsoft/TypeScript-TmLanguage#717]
- VSCode Version: 1.30.2
- OS Version: MacOSX 10.12.6

Seem a fix before: https://github.com/Microsoft/vscode/issues/15692
But maybe a little different.

Steps to Reproduce:

- write a `js` file:
```
/* regex? */
function test() {
   return /"/.test('xxx"xxx');
}

console.log(test());
a = 3 /*test*/ / parseInt(/.+/.exec('3f23fg')[0]);
console.log(a);

b = 1
a = () => b
2 + (b=2), 3
b = 6
console.log(a(),b);
(b)

if (a === 1) {
   b = 2
} else if (a === 2) b = 3
else b = 4
c = 1
x = a/b/gi; y = /b/gi;
```
if want to run in `node`, add a line to define `b` and `gi`, e.g. `b = 1; gi = 1;`

- open the file in vscode; colored in red and orange:
<img width="407" alt="screen shot 2019-02-07 at 1 42 58 am" src="https://user-images.githubusercontent.com/2894341/52361718-d5ed0300-2a79-11e9-9b56-9cd45d6e63c0.png">

Monarch Tokens:
```
   {
      "start_offset": 101,
      "end_offset": 111,
      "type": "regexp.js",
      "value": "/ parseInt"
   },
   {
      "start_offset": 111,
      "end_offset": 112,
      "type": "regexp.escape.control.js",
      "value": "("
   },
   {
      "start_offset": 112,
      "end_offset": 113,
      "type": "regexp.js",
      "value": "/"
   },
   {
      "start_offset": 113,
      "end_offset": 114,
      "type": "delimiter.js",
      "value": "."
   },
   {
      "start_offset": 116,
      "end_offset": 117,
      "type": "delimiter.js",
      "value": "."
   },
   {
      "start_offset": 117,
      "end_offset": 121,
      "type": "identifier.js",
      "value": "exec"
   },
```

**Comment by sheetalkamat** [comment]
This might not be easy to fix because of the way tmLanguage lookup works. We already had issue #3 because of which anything after comment is treated as regexp if it can match completely. Will look into what best action can be taken

**Comment by dna2github** [comment]
thx, i will track the #3 then.
