### ISSUE TITLE
Javascript Syntax Highlighting & Async & Brackets

### ISSUE THREAD

**Issue by faiwer** [Microsoft/TypeScript-TmLanguage#719]
Hello. In the code below the syntax-highlighting is broken:
```
	() => (
	{
		anything: async () =>
		{
			await dispatch(anything(anything));
		},
	})
```
![img_12_02_01_82419424dec](https://user-images.githubusercontent.com/744114/52626842-4367bc00-2ede-11e9-9029-197c7ded3a96.png)

minus 1 tab and it's fixed:
```
() => (
{
	anything: async () =>
	{
		await dispatch(anything(anything));
	},
})
```
![img_12_02_01_c6cb606f922](https://user-images.githubusercontent.com/744114/52626884-5aa6a980-2ede-11e9-82d7-72f77f771724.png)

or just move `(` to next line:
```
	() => 
	(
	{
		anything: async () =>
		{
			await dispatch(anything(anything));
		},
	})
```
![img_12_02_01_aa4c2a5a40e](https://user-images.githubusercontent.com/744114/52626931-7316c400-2ede-11e9-80d8-240132009d54.png)

- vscode: Version: 1.31.0
- os: Linux Mint 18.2 Sonya

**Comment by sheetalkamat** [comment]
This would limitation of how tmLanguage grammar works with lookup only limited to single line. given that in most case ( followed by new line is start of arrow that's what we go with. Not doing so would break multiple other uses so this cant be fixed.
