### ISSUE TITLE
Multiline object destructed parameter has object literal scope

### ISSUE THREAD

**Issue by Pajn** [Microsoft/TypeScript-TmLanguage#722]
**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:**  0.0.49 / latest

**Code**

```ts
// Please include a code snippet that demonstrates the issue
const foo = ({bar}) => {}

const foo = ({
  bar
}) => {}
```

In the oneliner, bar has scopes:
```
variable.parameter.ts
meta.parameter.object-binding-pattern.ts
meta.parameters.ts
meta.arrow.ts
meta.var.expr.ts
source.ts
```

In the multiline version, bar has scopes:
```
variable.other.readwrite.ts
meta.object.member.ts
meta.objectliteral.ts
meta.var.expr.ts
source.ts
```

**Comment by sheetalkamat** [comment]
This is by design. In multiline repro code, single line lookups as part of tmLanguage syntax make it difficult to say if on line with `const foo = ({` is array or just object literal expression.

**Comment by Pajn** [comment]
I don't know tmLanguage super well so this might be a dumb question but would it be possible to have a begin on `({` (maybe even `= ({`) and end on `}) =>`?

I think that would cover most cases this code crops up as it mostly does so in React components which would only receive a single parameter.
