### ISSUE TITLE
TypeScript wrong `this` syntax highlighting in particular (but valid) class-method parentheses styling

### ISSUE THREAD

**Issue by escKeyStroke** [Microsoft/TypeScript-TmLanguage#725]
- VSCode Version: 1.31.1
- OS Version: Windows 10.0.17134 Build 17134

```ts
class C {
  
  f: (g: Function) => any 
  = g => g();

  h: () => string 
  = () =>'a';

  k: (g: Function) => any 
  =
  this.f
  (
    this.h
  )

}
```

#### Actual behavior
See how `this.h` above is is not highlighted the same way as `this.f`.
#### Expected behavior
This is valid code. `this.f` and `this.h` should be highlighted the same way.

Does this issue occur when all extensions are disabled?: Yes

EDIT

Note that the roughly equivalent JavaScript code is property highlighted.  So this is a TypeScript syntax highlight problem. Apparently, not a JavaScript one (I submit the edit after vscodebot labeled the issue as "javascript".
```javascript
class C {
  
  f() {return g()};

  h(){return 'a'};

  k(){ return (
      this.f
      (
        this.h
      )
    )
  }

}
```

**Comment by sheetalkamat** [comment]
This is limitation of tmLanguage syntax that doesn't allow multi line lookups. Class could contain constructor signature with parameters on new line and hence we prefer that over expression with parenthesis starting on new line.
