### ISSUE TITLE
The 'from' keyword should be scoped

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/TypeScript-TmLanguage#73]
The [OceanicNext tmTheme](http://tmtheme-editor.herokuapp.com/#!/editor/url/https://raw.githubusercontent.com/voronianski/oceanic-next-color-scheme/master/Oceanic%2520Next.tmTheme) ([homepage](http://labs.voronianski.com/oceanic-next-color-scheme/)) colors `from` as teal using the scope `keyword.operator`. Example js:

```js
import React from 'react';
```

*Created from https://github.com/Microsoft/vscode/issues/2684 and https://github.com/Microsoft/vscode/issues/2694*

**Comment by aeschli** [comment]
Instead of `keyword.operator`, which is also used by operators like '===' maybe better use 'keyword` or `keyword.control`

**Comment by Tyriar** [comment]
Looking at the [TextMate docs](https://manual.macromates.com/en/language_grammars) again, `keyword.other` is probably the way to go since they aren't really operator or control (eg. `return`, `while`, `continue`) related.

**Comment by anubmat** [comment]
'from' has scope keyword.control.import.include.ts. Closing this issue.
