### ISSUE TITLE
idea can't display some func as func color in typescript v2

### ISSUE THREAD

**Issue by bluelovers** [Microsoft/TypeScript-TmLanguage#733]
**TypeScript Version:**  3.4.0-dev.201xxxxx

**Search Terms:**

**Code**

idea can't display some func as func color in typescript v2

![image](https://user-images.githubusercontent.com/167966/54991139-42569e00-4ff7-11e9-8539-b951b25cb53d.png)

https://github.com/bluelovers/node-fs-iconv/blob/master/core.ts

```ts
export function WrapFSIconv<F extends typeof fsExtra = typeof fsExtra>(fsLib: F): WrapFSIconv.IWrapFS<F>
{
	let fs = clone(fsLib) as WrapFSIconv.IWrapFS<F>;


	Object.keys(fs)
		.forEach(k => {
			if (typeof fsLib[k] === 'function')
			{
				fs[k] = fsLib[k].bind(fsLib[k], fsLib);
			}
		})
	;


	fs[SymFSLib] = fsLib;


	fs.iconv = iconv;


	fs.ensureWriteStream = ensureWriteStream.bind(fs);
	fs.saveFile = saveFile.bind(fs);
	fs.saveFileSync = saveFileSync.bind(fs);


	fs.loadFileSync = loadFileSync.bind(fs);
	fs.loadFile = loadFile.bind(fs);


	fs._createStreamPassThrough = _createStreamPassThrough.bind(fs);
	fs._outputStream = _outputStream.bind(fs);
	fs._autoDecode = _autoDecode.bind(fs);


	fs.trimFilename = trimFilename;


	Object.defineProperty(exports, "__esModule", { value: true });


	// @ts-ignore
	fs.default = fs;


	return fs;
}
```

i guess problem is because it have > 1 signature for `loadFileSync`, `loadFile`, `_aotoDecode`

this is idea issues, but maybe something is about typescript

issues link in jetbrain idea
https://youtrack.jetbrains.com/issue/WEB-37873

**Expected behavior:**

> display as func color

**Actual behavior:**

> `loadFileSync`, `loadFile`, `_aotoDecode` not as func color

**Playground Link:** 

**Related Issues:**

**Comment by sheetalkamat** [comment]
`loadFileSync` and others in that example are by design since that would need semantic information and cannot be colored syntactically with this grammar.
`callClassWithoutNewDecorator` and `callClassWithoutNewDecorator2` => the issue is not clear through description but I see that in master both are colored as function.

**Comment by bluelovers** [comment]
@sheetalkamat pls looke this

this issue not only the color issue

also has this
https://github.com/Microsoft/TypeScript-TmLanguage/issues/733#issuecomment-476583970

**Comment by sheetalkamat** [comment]
This repo is only for color though
