### ISSUE TITLE
Syntax highlighting breaks in function return type

### ISSUE THREAD

**Issue by samdenty** [Microsoft/TypeScript-TmLanguage#734]
**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:**  latest

**Code**

```ts
type Generic<T, T2> = T

// Breaks when nested generics are used if the function arguments
// start parameter is on the next line
const test1 = (
  a: 1
): Generic<any, Generic<any, any>> => {}

const test2 = (a: 1): Generic<any, Generic<any, any>> => {}
```

![image](https://user-images.githubusercontent.com/13242392/55129799-72459480-5110-11e9-940c-87156ee34aba.png)

**Comment by sheetalkamat** [comment]
This is limitation of syntax grammar having just single line lookup and we cant tell on line where test1 is deteremined that it is going to be arrow so there is no safe way to apply Type rules to Generic return types

**Comment by sheetalkamat** [comment]
Fixed in master
