### ISSUE TITLE
Add scopes for variables defined as parameters when used in function body

### ISSUE THREAD

**Issue by atomiks** [Microsoft/TypeScript-TmLanguage#735]
**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:**  0.0.50 / latest

**Code**

```ts
function map(arr, fn) {
  const result = [];
  for (let i = 0; i < arr.length; i++) {
    result.push(fn(arr[i], i));
  }
  return result;
}
```

`arr` and `fn` when used in the function body should receive some sort of scope that identifies they were defined as parameters. Helps distinguish other variables and variables that were defined as as parameters.

GitHub is highlighting them as orange above, the ones in the body should have the ability to be colored orange too (if the theme wants it).

**Comment by sheetalkamat** [comment]
This is not something that can be done syntactically.

**Comment by atomiks** [comment]
I figured that would be the case, oh well!
