### ISSUE TITLE
Multiline Type Arguments

### ISSUE THREAD

**Issue by marudor** [Microsoft/TypeScript-TmLanguage#738]
**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:**  0.0.50

**Code**

```ts
function T<A, B>() {}
T<
number,
string
>();
```

<img width="161" alt="Screenshot 2019-04-08 at 20 30 48" src="https://user-images.githubusercontent.com/1881725/55747770-4f36b100-5a3d-11e9-999b-55fa66fd1a08.png">

As you can see highlighting (here VSCode) is also broken.
Based on my, fairly limited, understand of how grammar works it seems like it doesn't correctly detect start of Type Arguments and instead parses `T<` as `variable.other.constant.ts` the two types as 
`variable.other.readwrite.ts` and the closing `>` actually as `keyword.operator.relational.ts`

```
>T<
 ^
 source.ts variable.other.constant.ts
  ^
  source.ts keyword.operator.relational.ts
>string,
 ^^^^^^
 source.ts variable.other.readwrite.ts
       ^
       source.ts punctuation.separator.comma.ts
>number
 ^^^^^^
 source.ts variable.other.readwrite.ts
>>();
 ^
 source.ts keyword.operator.relational.ts
  ^
  source.ts meta.brace.round.ts
   ^
   source.ts meta.brace.round.ts
    ^
    source.ts punctuation.terminator.statement.ts
```
relevant part from writing a test for it.

I'm not experienced enough to know how to add multiline support.

**Comment by marudor** [comment]
Sadly duplicate of #479 - Is this still considered by design and wontfix?
Browsing through Issues this gets reported a lot.

**Comment by sheetalkamat** [comment]
Sadly its limitation of the tmlaguage syntax that doesn't allow multiline lookup and hence cannt be fixed
