### ISSUE TITLE
`await` colored incorrectly when part of a larger word.

### ISSUE THREAD

**Issue by rbuckton** [Microsoft/TypeScript-TmLanguage#74]
Currently, `await` is colored as a keyword when inside of a larger word, such as `awaiting`.

**Comment by billti** [comment]
@rbuckton Did you fix the TypeScriptReact grammar also? Seems this should apply to both.

**Comment by billti** [comment]
Ping @rbuckton . Please do not leave the grammars out of sync and add this to the React version also. Thanks.

**Comment by anubmat** [comment]
React version looks updated. Closing Issue.
