### ISSUE TITLE
Multi line type definitions have wrong scope / highlighting

### ISSUE THREAD

**Issue by uloco** [microsoft/TypeScript-TmLanguage#761]
**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:**  0.0.52 / latest

![image](https://user-images.githubusercontent.com/8818340/61872236-184cb400-aee3-11e9-930d-72e865908b27.png)

**Code**

```ts
// Please include a code snippet that demonstrates the issue
// right
let variable: string;

// wrong
let multilineVariable: 
  | string
  | number
  | string[];


let func: <T,U>() => [T,U]

// right
func<string, number>()

// wrong
let multiFunc = func<
  string,
  number
>()
```

**Comment by sheetalkamat** [comment]
This is working as intended. With limitation to tmLanguage syntax grammar with lookup of single line at a time we cant determine if func< is expression or start of type arguments and we prefer expression over type parameters.

For the type definition the work around is:
```ts
let multilineVariable: 
  string |
  number |
  string[];
```

**Comment by uloco** [comment]
I am sad but understand the limitation. Thanks for your reply. :)

**Comment by karlhorky** [comment]
Ok, so this means that multi-line generics like the following is not possible?

```ts
type A = SomeLongerTypeName<
  AnotherFairlyLongTypeName,
  AndFinallyAReallyLongTypeName,
>;
```

**Comment by karlhorky** [comment]
Aside from the possible workarounds to define extra types, would there be any way to tackle this as an extension developer? (to allow multi-line generic type arguments?)

Eg. for https://github.com/frigus02/vscode-sql-tagged-template-literals/pull/21

**Comment by thorn0** [comment]
> we cant determine if `func<` is expression or start of type arguments

@sheetalkamat Didn't you consider relying on whitespace conventions (`func <` vs `func<`) for resolving this ambiguity?
