### ISSUE TITLE
Incorrect highlighting of return value with nested generics

### ISSUE THREAD

**Issue by matt-tingen** [microsoft/TypeScript-TmLanguage#765]
**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:**  0.0.52 / latest

**Code**

```ts
const foo = (
): Foo<Bar<number>> => {};
```

![Screen Shot 2019-08-05 at 5 00 56 PM](https://user-images.githubusercontent.com/8584728/62494984-b9205680-b7a2-11e9-8779-7d415c0be8b2.png)

Removing the new line results in the expected highlighting:

![Screen Shot 2019-08-05 at 5 03 19 PM](https://user-images.githubusercontent.com/8584728/62495081-f08f0300-b7a2-11e9-9a7e-7513ea6ea4c7.png)

In more complex examples, the incorrect highlighting carries into the function body:
```ts
export const indexBy = <T>(
  items: T[],
  iteree: (item: T) => string,
): Partial<Record<string, [T, number]>> => {
  const indexed: Partial<Record<string, [T, number]>> = {};
  // ...
  return indexed;
};
```

![Screen Shot 2019-08-05 at 5 07 31 PM](https://user-images.githubusercontent.com/8584728/62495315-86c32900-b7a3-11e9-9ddf-cd1e61bcb0e9.png)

**Comment by sheetalkamat** [comment]
This does not repro in master
![image](https://user-images.githubusercontent.com/8052792/62495441-bdd91080-b78a-11e9-82a9-9fdd943d324f.png)
