### ISSUE TITLE
Incorrect highlighting of regular expressions due to unescaped slash

### ISSUE THREAD

**Issue by alexr00** [microsoft/TypeScript-TmLanguage#771]
The issue is that the grammar happily accepts the invalid regular expression and highlights it as though it were a good regular expression. This makes the squiggle with the error hard to understand.

From @FremyCompany in https://github.com/microsoft/vscode/issues/80405:

Issue Type: <b>Bug</b>

The javascript syntax highlighter of visual studio code doesn't work properly one regular expressions that contain a close slash inside a parenthesis block.

```javascript
let flag = /(///)/.test(string) ? (
    'has_doc_comment' : 'has_no_doc_comment'
)
```

The syntax error is correct, but impossible to understand due to incorrect highlighting. Compare here below Visual Studio's highlighting vs a proper javascript parser highlighting:

> ![image](https://user-images.githubusercontent.com/364405/64348349-531f2d00-cff5-11e9-8229-961bf3289ccd.png)

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:25.463Z)
OS version: Linux x64 4.15.0-58-generic

**Comment by sheetalkamat** [comment]
Most colorizers are more permissive than the actual grammar.. Eg. if you test this in sublime as js file it will be colored similarly.
