### ISSUE TITLE
Highlight custom jsdoc tags that include a dash

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript-TmLanguage#772]
**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:**   latest

**Code**
For the js:

```ts
/**
 * @tag
 * @dash-tag
 */
function foo() {}
```

The custom tag `tag` is highlighted as a jsdoc element but `dash-tag` it not since it contains a dash

**Comment by sheetalkamat** [comment]
Typescript parses jsdoc tag names as identifier so grammar rule here does same thing. So unless something changes in how typescript identifies jsdoc, this wont be fixed
