### ISSUE TITLE
Coloring broken after simple type declaration

### ISSUE THREAD

**Issue by mysticatea** [microsoft/TypeScript-TmLanguage#775]
**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:**  0.0.52

**Code**

```ts
type Pattern = {
    source: string
    schema: parseXML.Schema
    expected: any
}

describe("parseXML()", () => {
    const patterns: Pattern[] = [
        // ....
    ]

    for (const { expected, schema, source } of patterns) {
    }
})
```

If I put a semicolon into the last of the type declaration, the coloring revives.

![image](https://user-images.githubusercontent.com/1937871/65673421-bc8adc80-e085-11e9-9cd4-51524ff5411f.png)

↑ problematic code

![image](https://user-images.githubusercontent.com/1937871/65673506-df1cf580-e085-11e9-92ea-0f154eacfce7.png)

↑ with a semicolon

---

<details>
<summary>As a side note, GitHub's syntax highlight is broken as same.</summary>

![image](https://user-images.githubusercontent.com/1937871/65673733-52266c00-e086-11e9-82be-f599ac2dd589.png)

↑ problematic code

![image](https://user-images.githubusercontent.com/1937871/65673783-6bc7b380-e086-11e9-8386-51c74324d939.png)

↑ with a semicolon

</details>

**Comment by sheetalkamat** [comment]
Fixed by 74f669d
