### ISSUE TITLE
Broken colorization with nullish coalescing

### ISSUE THREAD

**Issue by falsandtru** [microsoft/TypeScript-TmLanguage#777]
**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:**  0.0.52

**Code**

```ts
const a = 0 ?? 0;
const b = 0;

class C {
  public a() {
    0 ?? 0;
  }
  public b() {
    return;
  }
}
```

**Comment by falsandtru** [comment]
ping @sheetalkamat

**Comment by falsandtru** [comment]
ping @sheetalkamat

**Comment by sheetalkamat** [comment]
This is already working correctly in the master.
