### ISSUE TITLE
Export keyword highlighted wrong in const enum

### ISSUE THREAD

**Issue by tinganho** [Microsoft/TypeScript-TmLanguage#78]
The export keyword is highlighted wrong below, it should be highlighted in blue?

<img width="223" alt="screen shot 2016-02-05 at 11 51 11" src="https://cloud.githubusercontent.com/assets/1324476/12837538/c79634de-cbfe-11e5-8fa9-5fe26e60631d.png">

**Comment by tinganho** [comment]
Also namespaces are highlighted wrong(should be blue?).

<img width="257" alt="screen shot 2016-02-05 at 13 46 58" src="https://cloud.githubusercontent.com/assets/1324476/12839008/5b675f84-cc0f-11e5-8f96-1573b3a689e3.png">

**Comment by aeschli** [comment]
duplicate of #37

**Comment by anubmat** [comment]
Solved. Closing.
