### ISSUE TITLE
No syntax highlighting for multiline object literal value with generics

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript-TmLanguage#784]
From https://github.com/microsoft/vscode/issues/77808

**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:**  0.0.53 / latest

**Code**

```ts
const a = ({
    a: f<
        Pick<any, 'allIds'>
    >((acc, {}) => { return acc; })
});
```

**Bug**
The body of the function is not highlighted:

![Screen Shot 2019-10-25 at 2 52 04 PM](https://user-images.githubusercontent.com/12821956/67606706-0e7f5a80-f737-11e9-8f36-918db38308c6.png)

**Comment by sheetalkamat** [comment]
Duplicate of #475
