### ISSUE TITLE
Typescript syntax is broken with decorators.

### ISSUE THREAD

**Issue by aeschli** [Microsoft/TypeScript-TmLanguage#79]
_From @oliverjanik on February 9, 2016 7:30_

![image](https://cloud.githubusercontent.com/assets/2280140/12910046/0fee6da0-cf5b-11e5-9d01-9baad2e85e97.png)

_Copied from original issue: Microsoft/vscode#2822_

**Comment by keithmattix** [comment]
I'm seeing this too...

**Comment by felixfbecker** [comment]
![image](https://cloud.githubusercontent.com/assets/10532611/14883479/a6e79c9c-0d3e-11e6-9795-0a3afe40be40.png)

VS Code 1.0.0

**Comment by oliverjanik** [comment]
Issue persists:
![image](https://cloud.githubusercontent.com/assets/2280140/14905715/e9e239b8-0df6-11e6-8187-c8175fd3bc75.png)

**Comment by sheetalkamat** [comment]
Fixed by #257

**Comment by felixfbecker** [comment]
@sheetalkamat can we have an Insiders release with it? I want this 😄
