### ISSUE TITLE
Multiline function arguments in arrow functions aren't colored as arguments

### ISSUE THREAD

**Issue by rmtracey** [microsoft/TypeScript-TmLanguage#791]
**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:**  0.0.53 / latest

**Code**

```ts
const test = (foo, bar) => `${foo} ${bar}`

const test2 = (
  foo,
  bar
) => `${foo} ${bar}`

function test3(foo, bar) {
  return `${foo} ${bar}`
}
function test4(
  foo,
  bar
) {
  return `${foo} ${bar}`
}
```
(Interesting, seems as though GitHub does the same thing)

Screenshot:
![image](https://user-images.githubusercontent.com/3460875/69433887-80cd6580-0d0a-11ea-83eb-325a64e33756.png)

Like the title says, if the arguments of an arrow function span multiple lines, they lose the proper argument syntax highlighting. The issue doesn't occur for regular functions. I've seen a few similar issues to this one, but most of them say something about the issue being fixed with https://github.com/microsoft/TypeScript-TmLanguage/pull/552. However, I'm seeing the problem even on the latest grammar.

**Comment by xenophilicibex** [comment]
This is still a problem, why are all the issues being closed for it?
