### ISSUE TITLE
Inconsistent highlighting of multiline expression 

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript-TmLanguage#795]
**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:**  latest

From https://github.com/microsoft/vscode/issues/86899

**Code**

```ts
function test() {
  return abc;
}

function test() {
  return (
    xyz
  );
}
```

`abc` and `xyz` are scoped differently. Specifically `xyz` is scoped as `variable.parameter.tsx` while `abc` is `variable.other.readwrite.tsx`.  This cause some grammars to highlight it differently from `abc`

**Comment by sheetalkamat** [comment]
This is working as intended since tm language grammar doesn't allow more than a line lookup. Which means we cant determine if `return (` is arrow or parenthesized expression we have tailered it to mean possibly arrow since that's the most common case.
