### ISSUE TITLE
Highlight `type` as a keyword in `import type`

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript-TmLanguage#800]
**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:**  0.0.53 / latest

**Code**

```ts
import type { x } from './x'
```

**Bug**
`type` here should probably be treated as a keyword (or modifier). Currently it is scoped as:

```
variable.other.readwrite.alias.ts
meta.import.ts
source.ts
```

**Comment by sheetalkamat** [comment]
Closed by #792
