### ISSUE TITLE
Regular expression ending in ? breaks highlighting

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript-TmLanguage#805]
From https://github.com/microsoft/vscode/issues/90184

**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:**  0.0.53 / latest

**Code**

```ts
const x = !/s?/;
let foo;
```

After the regular expression, the highlighting is off:

![Screen Shot 2020-02-07 at 11 28 22 AM](https://user-images.githubusercontent.com/12821956/74059477-fc02f700-499c-11ea-94c9-dbf77fd0eb7a.png)

**Comment by zajrik** [comment]
I believe this is the similar to my issue (#806), in that it's actually fine if you remove the `!`:
![image](https://user-images.githubusercontent.com/10369802/74563650-df356900-4f32-11ea-9e3b-59061ff5e595.png)

**Comment by sheetalkamat** [comment]
Yep fixed by d63aae4
