### ISSUE TITLE
Typescript syntax highlighting breaking on certain regex following !

### ISSUE THREAD

**Issue by zajrik** [microsoft/TypeScript-TmLanguage#806]
- VSCode Version: 1.43.0-insider (user setup)
- OS Version: Windows 10 pro

Steps to Reproduce:
1. Fresh install of VSCode Insiders (Also occurring on stable)
2. Paste the following code into a file:
```ts
class Foo {
    public foo(): boolean {
        return !/[():\w]/.test('foo');
    }

    private bar(): void {}
}
```

Does this issue occur when all extensions are disabled?: Yes

Funnily enough, it appears this code breaks GitHub's syntax highlighting as well.

Escaping the parens will fix syntax highlighting on the remainder of the document, but the syntax highlighting on the regular expression itself is still broken. Removing the `!` and not escaping the parens fixes everything, but obviously that completely changes the meaning of the code.

Here's the example above:
![image](https://user-images.githubusercontent.com/10369802/74555449-582bc500-4f21-11ea-8cf3-67b8c0a22607.png)

And here's the prominent example in my code that sparked this issue:
![image](https://user-images.githubusercontent.com/10369802/74555423-4d713000-4f21-11ea-8754-a7bebc6a0e22.png)

The last screenshot is from stable with all my extensions, however I can confirm it appears similarly broken on a fresh insiders install with no extensions.

**Comment by mjbvz** [comment]
Confirmed with the latest grammar from master

**Comment by zajrik** [comment]
I gotta tell ya, this does not feel right at all:
![image](https://user-images.githubusercontent.com/10369802/75259755-1ff07600-57ae-11ea-8b7b-ac6376707798.png)

But at least I can work again 🤷‍♀️

**Comment by zajrik** [comment]
Another potential solution would be to simply take the inverse of the character set in the regular expression itself, like:
```js
if (/[^():\w]/.test(reader.peek(index)))
    return false;
```

I ended up using this a few times today in some new code, but this solution is of course not always viable.

Hope to see some resolution to this issue soon.

**Comment by infinnie** [comment]
> Funnily enough, it appears this code breaks GitHub's syntax highlighting as well.

Due to GitHub using this as their TypeScript syntax highlight grammar.

**Comment by zajrik** [comment]
That makes a lot of sense.

**Comment by qsniyg** [comment]
The way I worked around this issue was to just add parenthesis around the expression:

`!(/regex/.test(...))`

**Comment by zajrik** [comment]
Oh, I hadn't considered that under the assumption that it would throw warnings due to the `no-extra-parens` typescript-eslint rule but I tested it just now it looks like it doesn't. Good to know. Obviously a fix for this problem is still the desirable solution, though.

**Comment by mjbvz** [comment]
@sheetalkamat When you have a chance, can you or someone on the TS team please take a look at this. We're seeing a lot of reports on the VS Code side but I had trouble figuring out what's going wrong in the grammar

**Comment by KostyaTretyak** [comment]
In VS Code v1.43.2, the issue and https://github.com/microsoft/vscode/issues/92904 does not seem to be resolved.
