### ISSUE TITLE
Incorrect syntax highlight when the operator ! is followed by a regular expression.

### ISSUE THREAD

**Issue by infinnie** [microsoft/TypeScript-TmLanguage#808]
**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:**  0.0.53 / latest

**Code**

```ts
// Please include a code snippet that demonstrates the issue
!/a/
```

**Comment by mjbvz** [comment]
Duplicate of #806
