### ISSUE TITLE
Simple string breaks vscode's and github's syntax highlighting

### ISSUE THREAD

**Issue by pushkine** [microsoft/TypeScript-TmLanguage#809]
- VSCode Version: 1.42.1
- OS Version: windows_nt 1903

Paste the following line into a javascript file :
```
;(false ? '' : ') =>') + ''
```
anything coming after it won't get parsed
```javascript
console.log()
Object.assign()
;(false ? '' : ') =>') + ''
console.log()
Object.assign()
```
...github breaks on it too, guess y'all use the same stuff

edit : 
github fails on preview but still applies syntax after posting
 on vscode, the first example only breaks the following line, 
here is another that breaks the whole end of the file
```
(false ? '' : ') =>') + `${''}`
```

**Comment by mjbvz** [comment]
I confirmed this using the latest grammar from master. I believe the issue is that `(false ? '' : ') =>` gets parsed as an arrow expression
