### ISSUE TITLE
TypeScript highlighting of multi-line unions inside objects does not highlight basic types

### ISSUE THREAD

**Issue by bmalehorn** [microsoft/TypeScript-TmLanguage#812]
- VSCode Version: 1.44.0-insider
- OS Version: Darwin x64 18.7.0

Steps to Reproduce:

1. Create a TypeScript file with the following contents:
```
type Foo = {
  bar: number
   | string;
};
```

![image](https://user-images.githubusercontent.com/3344958/77587185-a7600080-6ea4-11ea-8c9e-e8cec2a49c07.png)

Note that `number` and `string` have different colors, but should have the same color as they're both basic types.

It works properly if both types are on the same line:

![image](https://user-images.githubusercontent.com/3344958/77587272-d0809100-6ea4-11ea-9631-b9679451f951.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by sheetalkamat** [comment]
This is limitation of tmlanguage syntax that allows only single line lookup.

**Comment by Dassderdie** [comment]
@sheetalkamat 
> This is limitation of tmlanguage syntax that allows only single line lookup.

I just did a quick search, because I couldn't imagine that tmlanguage has such a limitation, and found out, that `begin`-, `end`-regex-blocks should be used for multiline stuff.

I guess this isn't practicable for this usecase?

**Comment by bmalehorn** [comment]
> @sheetalkamat
> 
> > This is limitation of tmlanguage syntax that allows only single line lookup.
> 
> I just did a quick search, because I couldn't imagine that tmlanguage has such a limitation, and found out, that `begin`-, `end`-regex-blocks should be used for multiline stuff.
> 
> I guess this isn't practicable for this usecase?

@Dassderdie I've spent some time writing tmlanguage syntax highlighting. The easiest way to write tmlanguage is to write line-by-line regexes. While it is possible to write begin- and end- blocks, I found that writing complex versions of this was extremely difficult and reverted back to line-by-line regexes.

So I'm guessing @sheetalkamat means that it's not worth the effort to fix this bug.

**Comment by Dassderdie** [comment]
> > @sheetalkamat
> > 
> > > This is limitation of tmlanguage syntax that allows only single line lookup.
> > 
> > I just did a quick search, because I couldn't imagine that tmlanguage has such a limitation, and found out, that `begin`-, `end`-regex-blocks should be used for multiline stuff.
> > 
> > I guess this isn't practicable for this usecase?
> 
> @Dassderdie I've spent some time writing tmlanguage syntax highlighting. The easiest way to write tmlanguage is to write line-by-line regexes. While it is possible to write begin- and end- blocks, I found that writing complex versions of this was extremely difficult and reverted back to line-by-line regexes.
> 
> So I'm guessing @sheetalkamat means that it's not worth the effort to fix this bug.

Thanks for the clarification :)
