### ISSUE TITLE
Syntax highlighting breaks by Prettier output

### ISSUE THREAD

**Issue by Hawmex** [microsoft/TypeScript-TmLanguage#817]
- VSCode Version: 1.43.2
- OS Version: Win7

The following code formatted by Prettier breaks syntax highlighting:
```js
const a = (b) =>
  ((
    {
      c: () => {
        return b + 1;
      },
    }[c] || (() => b)
  )());
```

Does this issue occur when all extensions are disabled?: No

**Comment by sheetalkamat** [comment]
This cannot be fixed because of limitation of tmLanguage syntax which doesn't allow lookup of more than the current line.
