### ISSUE TITLE
`type Foo = {}` breaks next line's highlighting

### ISSUE THREAD

**Issue by andy-hanson** [Microsoft/TypeScript-TmLanguage#82]
In:

	type Foo = {}
	// a comment

The line `// a comment` is not highlighted.
The problem happens for any object type and any following line.
Tested on vscode `0.10.8`.

**Comment by anubmat** [comment]
![image](https://cloud.githubusercontent.com/assets/17298501/13720008/97b7ebb0-e7b3-11e5-8093-9049f3895a37.png)
Doesn't look like a problem anymore.
