### ISSUE TITLE
Broken highlighting after generic template string

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript-TmLanguage#822]
From https://github.com/microsoft/vscode/issues/97179#issuecomment-625730290

**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:**  latest

**Code**

```ts
const ComponentContainer = f({})<Pick<null, "a">>`
`;

const bla = 1;
```

**Bug**

<img width="966" alt="Screen Shot 2020-05-08 at 10 36 22 PM" src="https://user-images.githubusercontent.com/12821956/81465112-58cca400-917c-11ea-9b7f-292d4507eb21.png">

**Comment by mikestopcontinues** [comment]
Here's another reproduction, though the problem is a bit different:

<img width="452" alt="81820322-1990b100-94f6-11ea-905b-53ab55930db1" src="https://user-images.githubusercontent.com/150434/81820900-d1be5980-94f6-11ea-9ee5-2037080e9367.png">
