### ISSUE TITLE
Broken syntax coloring for jsx tag with < on own line

### ISSUE THREAD

**Issue by kubukoz** [microsoft/TypeScript-TmLanguage#825]
- VSCode Version: 1.44.2
- OS Version: macOS 10.15.4 Catalina

Steps to Reproduce:

1. Create new JSX file and have React available
2. Input this text, for example:

```jsx
import React from 'react'

const demo =
        <div>
            <
                div className="foo">
            </div>
        </div>;

```

Actual output:
![image](https://user-images.githubusercontent.com/894884/81296370-1028c400-9072-11ea-9017-940bef09db8e.png)

I believe the empty line between the nested `div`'s opening chevron and the element's name is to blame. Without the empty line:

![image](https://user-images.githubusercontent.com/894884/81296392-1ae35900-9072-11ea-8d67-5ff8bb80270b.png)

This also occurs in .tsx files.

Does this issue occur when all extensions are disabled?: Yes

Edit: apparently, github's parser also doesn't handle this well, but it's correct JSX.

**Comment by sheetalkamat** [comment]
This is limitation of textmate where it doesnt allow lookup beyond current line so we cant tell if < is start of the tag or just simple operator.
