### ISSUE TITLE
Broken highlighting in arrow functions without parameter type annotations when returning nested generic types

### ISSUE THREAD

**Issue by beepboop271** [microsoft/TypeScript-TmLanguage#831]
**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:**  0.0.53 / latest
VSCode version: 1.45.1 (Commit `5763d909d5f12fe19f215cbfdd29a91c0fa9208a`)
OS: Windows 10.0.18363 x64

When an arrow function expression has a parameter but no parameter type declaration, using a return type with more than two nested generics results in incorrect highlighting for the return type as well as the async keyword.

**Minimal Example**

```ts
const nums = [1, 2, 3];

nums.map(async (n): Promise<Array<number | string>> =>
  [n]
);

nums.map(async (n): Promise<Array<Array<number | string>>> =>
  [[n]]
);
```

**Expected behaviour**
The two arrow functions highlight the same way.

**Actual behaviour + more examples**

![image](https://user-images.githubusercontent.com/53926222/85218791-93c11a80-b36b-11ea-815b-8abdf2de20f0.png)

**Comment by sheetalkamat** [comment]
Fixed by d6e677b8cdb2cafe3166b71e8fc4f5398ad0c2f0
