### ISSUE TITLE
Syntax color issue

### ISSUE THREAD

**Issue by NoMoreDeps** [microsoft/TypeScript-TmLanguage#836]
We have written the need
Issue Type: <b>Bug</b>

Following this sample of code : 

![image](https://user-images.githubusercontent.com/3484915/92024086-ad97ba00-ed2b-11ea-99f3-a2f2b24a24aa.png)

The syntax color is correct, but if I format it differently, the last statement loses syntax coloration.

![image](https://user-images.githubusercontent.com/3484915/92024013-9789f980-ed2b-11ea-8313-e364461b1539.png)

VS Code version: Code - Insiders 1.49.0-insider (b6d4fec3714ff897f72c1dab8cc02b7421a8f131, 2020-09-01T05:54:42.740Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 0 @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (8.51GB free)|
|Process Argv|--crash-reporter-id bf356a28-e8c2-49fc-94e2-539aed5d2ce9|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
shadow-align|fsk|1.0.6
mongodb-vscode|mon|0.1.1
vscode-docker|ms-|1.5.0
remote-containers|ms-|0.138.0
remote-wsl|ms-|0.44.5

</details>
ed data into your clipboard because it was too large to send. Please paste.

**Comment by mjbvz** [comment]
Thanks!
