### ISSUE TITLE
Decorators should be allowed to have a different color from functions in syntax highlighting

### ISSUE THREAD

**Issue by navmed** [microsoft/TypeScript-TmLanguage#842]
I see that Decorators have been added, but specifying a color for `meta.decorator.ts` in VSCode gets overridden by the color for `entity.name.function.ts`.

![image](https://user-images.githubusercontent.com/2507639/99193180-e5b07580-273c-11eb-8cff-98593aa71475.png)

**Comment by sheetalkamat** [comment]
This isnt issue with grammar. you would need to set correct scope selector.
https://macromates.com/manual/en/scope_selectors
