### ISSUE TITLE
Typescript syntax highlighting breaks after `Generic<typeof x>`

### ISSUE THREAD

**Issue by connor4312** [microsoft/TypeScript-TmLanguage#846]
Happens on TS 4.1.2 as well as their nightly 4.2.0-dev.20201211. However it _doesn't_ happen in the TS playground, which is why I'm opening an issue here (initially)

1. Have code like:

```ts
function foo(): number { return 42; }
let bar: ReturnType<typeof foo>;
bar = 1;
foo();
new Uint8Array();
```

2. Notice highlighting breaks after the `let` statement:

    ![](https://memes.peet.io/img/20-12-5c9be795-e14f-48ef-a7cd-c5fb82c24c08.png)

Playground is okay: https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABMOcAUBKAXIsIC2ARgKYBOiA3oqcVCKUgCwBMA3IgL4BQANrYoQCGpHACVa9MABUAngAdiAHijzicYMlQA+VlyHkAvIgCMulOgy6wxAO6IAqjDBQAHAEFSpQTMysgA

**Comment by connor4312** [comment]
Here's a code sample where it happens: https://github.com/connor4312/cosmonaut/blob/f825e62d99049dbc66304eaa613fd5282378f1f4/src/model.ts#L100-L105

<img width="705" alt="image" src="https://user-images.githubusercontent.com/2230985/103156300-3368c680-475c-11eb-8521-bf0a1d50c4f1.png">

A bisect reports that this isn't a user extension

<img width="447" alt="image" src="https://user-images.githubusercontent.com/2230985/103156310-47142d00-475c-11eb-98cd-8fcc63f52216.png">

**Comment by tamasfe** [comment]
It doesn't have to be in generic argument position, this is broken for me as well:

```ts
function getLog(): typeof log {
  log.heading = "lerna-watcher";
  return log;
}
```
![image](https://user-images.githubusercontent.com/25967296/103384577-34e91480-4af7-11eb-9d1c-76c0a9ace0af.png)

ending the typeof expression with any of [`=`,`;`,`,`,`}`,`)`] will not mess the scopes afterwards.

```
Version: 1.53.0-insider
Commit: 4a875e23d20b64504a818834f3fa4c40adb8d480
Date: 2020-12-21T12:39:40.504Z
Electron: 11.1.0
Chrome: 87.0.4280.88
Node.js: 12.18.3
V8: 8.7.220.29-electron.0
OS: Linux x64 5.9.14-100.fc32.x86_64
```

**Comment by andreialecu** [comment]
Also reported at:
https://github.com/microsoft/vscode/issues/113657
https://github.com/microsoft/vscode/issues/113345

**Comment by pacexy** [comment]
Same for me.
Seems that `typeof` is parsed as a HTML tag (Syntax highlighting works if wrap `typeof x` with parentheses, `Generic<(typeof x)>`).
