### ISSUE TITLE
[typescript]: "export" keyword syntax highlighing inconsistency

### ISSUE THREAD

**Issue by aeschli** [Microsoft/TypeScript-TmLanguage#85]
_From @jumpinjackie on February 12, 2016 0:49_

This fragment of TypeScript

    export type DataLoadSingleSuccessCallback<T> = (result: T) => void;
    export type DataLoadSuccessCallback<T> = (results: T[]) => void;
    export type DataLoadFailureCallback = (error: any) => void;
    export type SaveObjectChangesCallback<T> = (obj: T, changes: IChangeAction[]) => void;

    export enum SubscriptionTopic {
        VisitStarted
    }
    
    export interface IChangeAction {
        
    }

Is highlighted like this (vscode version included)

![capture](https://cloud.githubusercontent.com/assets/563860/12995822/823a9cb0-d17e-11e5-8427-11d1dd6cdc42.png)

_Copied from original issue: Microsoft/vscode#2952_

**Comment by Ciantic** [comment]
Someone has fixed this, you can update your VS Code coloring file like this:

Open `C:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\typescript\syntaxes\` and replace the two files with equivalent files in this repository.

![image](https://cloud.githubusercontent.com/assets/64731/13863137/6bc107b6-eca0-11e5-8aa1-b2fe37448e4a.png)

**Comment by sheetalkamat** [comment]
Fixed by #257
