### ISSUE TITLE
JavaScript division assignment operator not interpreted as a textmate scope 

### ISSUE THREAD

**Issue by dziku86** [microsoft/TypeScript-TmLanguage#850]
- VSCode Version: 1.53.0-insider
- OS Version: Windows_NT ia32 6.1.7601

Steps to Reproduce: N/A

JavaScript division assignment operator `/=` should be  interpreted as an independent textmate scope to allow for a proper color customization.
Currently it is not. 

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Confirmed with the latest grammar versions

**Comment by dziku86** [comment]
@mjbvz @sheetalkamat  It isn't recognized as a `keyword.operator.assignment.compound.js` in situation like this:
```JavaScript
let a = 3

console.log(a /= 2)
```
It is when it doesn't have variable and right operand:
```JavaScript
/=
```

**Comment by sheetalkamat** [comment]
You probably arent using latest grammar as verified it is recognized correctly with the master branch

**Comment by dziku86** [comment]
> You probably arent using latest grammar as verified it is recognized correctly with the master branch

Just updated and it's still an issue.

Version: 1.53.0-insider (system setup)
Commit: 861a88ebadb4335df92251faf6420b598440e082
Date: 2021-01-29T21:57:41.683Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT ia32 6.1.7601
