### ISSUE TITLE
typeof breaks syntax

### ISSUE THREAD

**Issue by svipas** [microsoft/TypeScript-TmLanguage#858]
- VS Code Version: 1.53.2
- OS Version: macOS 11.2.1

Steps to Reproduce:

1. Open new TypeScript file
2. Paste this code:
```ts
function Baz() {}

class Foo {
    bar(): typeof Baz {
        if (true) {
            console.log('Hello World')
        }
        return
    }
}
```

With `typeof`:

![Screen Shot 2021-03-01 at 14 13 50](https://user-images.githubusercontent.com/10441177/109495787-67cc6c00-7a98-11eb-9c79-5ca443786457.png)

Without `typeof`:

![Screen Shot 2021-03-01 at 14 13 55](https://user-images.githubusercontent.com/10441177/109495775-63a04e80-7a98-11eb-959b-358dd7df3963.png)

As you can see somehow `typeof` return type in `bar` function breaks syntax coloring. If you cannot see difference just look at the `if` and `return` keywords and compare them by looking at the screenshots provided above. Also, I suggest to copy-paste given code to VS Code and you will see the problem immediately.

/cc @mjbvz

**Comment by mjbvz** [comment]
https://github.com/microsoft/vscode/issues/118640

Here's another example of `typeof` causing issues:

```ts
class X {
    constructor() {
        foo(false ? typeof defaultValue : undefined);
    }

    public foo() { }
}
```

![Screen Shot 2021-03-10 at 11 48 05 AM](https://user-images.githubusercontent.com/12821956/110688492-7b618c00-8196-11eb-81db-0a180a3675b4.png)

**Comment by pushkine** [comment]
Another one
```ts
let a: any;
let b: any & [boolean][];
let c: typeof a & [boolean][];
```
<img width="185" alt="Code_2021-03-12_16-23-44" src="https://user-images.githubusercontent.com/30108880/110960767-62500b00-834f-11eb-8453-afb8370b10ff.png">

**Comment by pushkine** [comment]
Another
```ts
    let foo;
    let bar;
    type Foo = { [K in keyof typeof foo & keyof typeof bar]: 1 };
```
<img width="363" alt="Code_2021-04-03_13-30-16" src="https://user-images.githubusercontent.com/30108880/113477253-e134f100-9480-11eb-900f-c7d0808fc995.png">

**Comment by pushkine** [comment]
Another
```ts
const foo = {
    get bar(): typeof foo['leet'] {
        return this.leet;
    },
    leet: 1
};
```
<img width="215" alt="Code_2021-04-06_21-07-24" src="https://user-images.githubusercontent.com/30108880/113765272-53753200-971c-11eb-80d6-997cc899488c.png">
