### ISSUE TITLE
Support highlighting override as a storage modifier 

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript-TmLanguage#868]
**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:**  latest

**Code**

```ts
class Foo {
    override bar() { }
}
```

Currently `override` ends up being scoped as:

```
variable.other.readwrite.ts
meta.class.ts
source.ts
```

However, I think `override` should instead align more with how `async` or `public` is highlighted. `async` for example is highlighted as:

```
storage.modifier.async.ts
meta.method.declaration.ts
meta.class.ts
source.ts
```

**Comment by andrewbranch** [comment]
@sheetalkamat, would you be able to look at this for 4.3?

**Comment by andrewbranch** [comment]
Thanks!
