### ISSUE TITLE
VSCode typings don't support DOMRectList iteration

### ISSUE THREAD

**Issue by danBamikiya** [microsoft/TypeScript-TmLanguage#872]
**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:**  0.0.55 / latest
VSCode doesn't support DOMRectList iteration in typings. According to [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Element/getClientRects) the return of `getClientRects` is a "collection" of `DOMRect` objects. I can iterate through it but when I switched to typescript VSCode was giving this error:

**Code**

```ts
// Please include a code snippet that demonstrates the issue

```
![image](https://user-images.githubusercontent.com/58262528/119282680-7e670700-bc32-11eb-9f9a-d9c456db9c7a.png)

**Comment by orta** [comment]
This is in the wrong repo, and there's nothing in the HTML spec which indicates that DOMRectList is iterable (aka usable in a for of loop) - https://drafts.fxtf.org/geometry-1/#domrectlist

Check the JS code in your link, it uses the length and then picks nodes from the indexes
