### ISSUE TITLE
Grammar needs to support 'async'/'await' keywords

### ISSUE THREAD

**Issue by zhengbli** [Microsoft/TypeScript-TmLanguage#9]
Ported from https://github.com/Microsoft/TypeScript-Sublime-Plugin/issues/374

![image](https://cloud.githubusercontent.com/assets/972891/10553851/f5a45ad4-7412-11e5-9fdd-af3ed7a596ed.png)

**Comment by DanielRosenwasser** [comment]
Closed by #20 thanks to @ejsmith.
