### ISSUE TITLE
Incorrect Highlighting of Multi-line Generic Type List when used in object

### ISSUE THREAD

**Issue by szubariev** [microsoft/TypeScript-TmLanguage#903]
vscode v1.65.2

similar to: [microsoft/TypeScript-TmLanguage#452](https://github.com/microsoft/TypeScript-TmLanguage/issues/452)

**Code**

```ts
function test<T1, T2, T3, T4>() {
    // code
}
interface IT1 {
    p: string;
}
interface IT2 {
    p: string;
}
interface IT3 {
    p: string;
}
interface IT4 {
    p: string;
}
const store = {
    colorsAsExpected: test<T1, T2, T3, T4>(),
    colorsDifferent: test<
        T1,
        T2,
        T3,
        T4
    >(),
}

```

<img width="406" alt="image" src="https://user-images.githubusercontent.com/5457461/160904621-078e36bb-dc75-4dd9-aaf2-6dd2c0c5a3a5.png">

**Comment by BryceBarbara** [comment]
@sheetalkamat It appears this one has been unaddressed for some time. Do you have any information on who might be maintaining this at this time?

**Comment by sheetalkamat** [comment]
This is duplicate of #475 and limitation of tmlanguage syntax
