### ISSUE TITLE
VSCode Syntax highlighting broken when using optional chaining in string templates

### ISSUE THREAD

**Issue by semos** [microsoft/TypeScript-TmLanguage#906]
**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:**  0.0.55 / latest

In vscode, syntax highlighting breaks when using optional chaining in string templates :

![image](https://user-images.githubusercontent.com/3511388/163392135-2b3000cd-fd54-49ec-b3b4-444e04d08ca3.png)

```ts
  const foo = `rawString_${obj.foo}`;

  const bar = `rawString_${obj?.bar}`;

  const baz = `BROKEN_HIGHLIGHTING`;

```

**Comment by sheetalkamat** [comment]
Doesnt repro:

![image](https://user-images.githubusercontent.com/8052792/217670285-009bb9fe-f68f-47bd-be33-a2661073cd7d.png)
