### ISSUE TITLE
Bracket highlighting does not work properly in VSCode

### ISSUE THREAD

**Issue by qwq0** [microsoft/TypeScript-TmLanguage#918]
![image](https://user-images.githubusercontent.com/82009862/177005301-9db448d6-e295-4597-a2b8-066a10bb5b36.png)

_Originally posted by @qwq0 in https://github.com/microsoft/vscode/issues/153980#issuecomment-1172909552_

**Comment by sheetalkamat** [comment]
@mjbvz i dont have permission to trasfer this to vscode repo. Highlighting seems to be correct ?
