### ISSUE TITLE
Ampersand (`&`) is highlighted red when used in JSX string literal

### ISSUE THREAD

**Issue by srmagura** [microsoft/TypeScript-TmLanguage#924]
**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:**  0.0.55 / latest   <------ this is a broken link in the issue template

Testing using VS Code Insiders:

```text
Version: 1.70.0-insider (Universal)
Commit: f3528d481b366b24321c382d5e5849f4c7d65248
```

**Code**

```jsx
render(<Section title="Voice & Video" />)
```

![image](https://user-images.githubusercontent.com/801549/178559917-092ded9c-02a1-40ea-a870-124816d6943c.png)

It makes sense to highlight the ampersand red — but only when it is used without double quotes. The screenshot shows that it is highlighted red whenever used inside a JSX expression, even if it is quoted.

Presumably this is the line of code that causes the red highlighting: https://github.com/microsoft/TypeScript-TmLanguage/blob/0dfae8cc4807fecfbf8f1add095d9817df824c95/TypeScriptReact.tmLanguage#L9994

**Comment by sheetalkamat** [comment]
Fixed by 2a56f0b
