### ISSUE TITLE
TypeScript syntax highlighting error with ternary and optional types

### ISSUE THREAD

**Issue by theusaf** [microsoft/TypeScript-TmLanguage#934]
Does this issue occur when all extensions are disabled?: Yes

Minimal example:
* ```ts
  const foo = Math.random() < 0.5
      ? 0 : 1,
    bar: [string?] = [];
  if (Math.random() > 0.5) console.log("baz");
  else console.log("qux");
  ```
Not affected:
* ```ts
  const foo = Math.random() < 0.5 ? 0 : 1,
    bar: [string?] = [];
  if (Math.random() > 0.5) console.log("baz");
  else console.log("qux");
* ```ts
  const foo = Math.random() < 0.5
      ? 0 : 1,
    bar: [string] = ["hello"];
  if (Math.random() > 0.5) console.log("baz");
  else console.log("qux");
  ```

![image](https://user-images.githubusercontent.com/32113157/197902789-c7c4a241-b727-4782-8dc3-79d95b15596d.png)

VS Code version: Code 1.72.2 (d045a5eda657f4d7b676dedbfa7aab8207f8a075, 2022-10-12T22:15:18.074Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Sandboxed: No

**Comment by sheetalkamat** [comment]
This is limitation of tmLangaugae where in new line cant be looked up and hence we dont know if ternary operator is continuation of variable declaration or not and is assumed to be out of variable declaration scope.
