### ISSUE TITLE
All greater-than signs (>) marked as "unmatched brackets" even when not part of a bracketed expression

### ISSUE THREAD

**Issue by Jessidhia** [microsoft/TypeScript-TmLanguage#936]
**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:**  0.0.55 / latest

**Code**

```ts
const test = () => 1 > 2
```

("Dark+ (default dark)" theme, Cascadia Code font (but happens on any font))
<img width="565" alt="image" src="https://user-images.githubusercontent.com/73085/200515870-2ac5dc63-4c9f-4c25-9d1a-c37226066a1f.png">

Both `>` tokens are marked as unmatched brackets and colorized red; the first `>` is part of the `=>` token, the second is an ordinary `>` operator. Disabling the `ms-vscode.typescript-javascript-grammar` fixes the highlighting and shows no errors, as does disabling `editor.bracketPairColorization.enabled` as that simply disables any kind of colorization.

c.f. https://github.com/microsoft/vscode/issues/157322

While this manifests as the `unexpected-closing-bracket` class being added to spans containing the `>` character, the "Developer: Inspect Editor Tokens and Scopes" tool still shows `=>` as a single token, both with the same `foreground` color value. It's only `.monaco-editor .unexpected-closing-bracket` that then colors it red.

Note also that `1 < 2 > 3` doesn't get colorized as mismatched brackets because it thinks the `<` operator is the start of a bracketed expression.

**Comment by sheetalkamat** [comment]
Does not repro 
![image](https://user-images.githubusercontent.com/8052792/217901891-42d97b43-503d-4486-b3a0-9e35650162d5.png)
