### ISSUE TITLE
Add support for instantiation expressions

### ISSUE THREAD

**Issue by cdbattags** [microsoft/TypeScript-TmLanguage#951]
Version: 1.74.2
Commit: e8a3071ea4344d9d48ef8a4df2c097372b0c5161
Date: 2022-12-20T10:32:21.587Z (1 wk ago)
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 22.2.0
Sandboxed: No
OS Version: macOS 13.0.1

**Code**

```ts
const generic = <T,>(initial: T) => initial
type thing = <T extends object>(what: T) => ReturnType<typeof generic<T>>
```

Obviously this is a terrible example but mainly any time I see `ReturnType<typeof something<T>>` the angle bracket syntax highlighting is breaking.

<img width="666" alt="image" src="https://user-images.githubusercontent.com/4399055/209906027-afe44704-a7c6-453e-b0f8-dd1274ec8bb3.png">

**Comment by cdbattags** [comment]
Hello, folks! Any update here?

**Comment by awmottaz** [comment]
I still have this issue. It can be seen using a simple example from the docs.

Version: 1.77.3
Commit: 704ed70d4fd1c6bd6342c436f1ede30d1cff4710
Date: 2023-04-12T09:41:48.638Z
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 13_3_1) AppleWebKit/537.36 (KHTML, like Gecko) Code/1.77.3 Chrome/102.0.5005.196 Electron/19.1.11 Safari/537.36

<img width="329" alt="Screenshot 2023-04-27 at 13 57 41" src="https://user-images.githubusercontent.com/17735385/234964604-92284915-cd24-4b20-abc7-b44404f9e590.png">
