### ISSUE TITLE
Add `@satisfies` JSDoc tag support

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript-TmLanguage#953]
TS 5.0 adds support for `@satisfies` and `@overload` JSDoc tags. `@overload` doesn't need any special support, but `@satisfies` should work the same as `@type`.

```js
/** @type {string} */
/** @satisfies {string} */
```

But currently it doesn't:

![image](https://user-images.githubusercontent.com/972891/214183770-bbfe0f72-9274-4c85-bc4b-23cebc5529c7.png)

**Comment by sheetalkamat** [comment]
Closed by #955
