### ISSUE TITLE
Generic parameters, e.g. in `typeof foo<T1, T2>` not recognized for typeof types

### ISSUE THREAD

**Issue by ryanrhee** [microsoft/TypeScript-TmLanguage#957]
**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:**  0.0.55 / latest

**Code**

```ts
// Please include a code snippet that demonstrates the issue

// this is similar to apollo-client's `useQuery` but simplified for the repro
function useQuery<TData, TVariables>(_vars: TVariables, _data: TData) {
  console.log('hello world')
}

export type UseQuery<TData, TVariables> = typeof useQuery<TData, TVariables>
```

<img width="575" alt="image" src="https://user-images.githubusercontent.com/242548/215655815-b1eb3a7d-4538-4f1d-967b-c81b7521589f.png">

Note the last `>` - it's red.

This syntax is valid. I believe it's valid as of TS 4.7, from https://github.com/microsoft/TypeScript/pull/47607 .

I've also confirmed that the bug still happens for cases where there's only 1 generic parameter.

**Comment by adamschoenemann** [comment]
I'm seeing the same issue.

**Comment by adamschoenemann** [comment]
Nice! A stupid question: how can I update vscode to use the fixed tmLanguage definition?

**Comment by ryanrhee** [comment]
same question here.
