### ISSUE TITLE
Provide jsdoc highlighting

### ISSUE THREAD

**Issue by egamma** [Microsoft/TypeScript-TmLanguage#97]
_From @Tyriar on February 23, 2016 17:39_

Supporting jsdoc highlighting would make them easier to read, this comment documentation style is pretty widespread.

```js
/**
 * Sorts an array.
 * @param {Array} arr The array to sort.
 * @returns An array.
 */
function sort(array) {
  ...
}
```

`@param`, `@returns` at the least would be easy to highlight (Atom supports this). `{Array}` and `arr` could potentially also be highlighted.

Related https://github.com/Microsoft/vscode/issues/514

_Copied from original issue: Microsoft/vscode#3364_

**Comment by sheetalkamat** [comment]
Fixed by #257
