### ISSUE TITLE
[Bug] `instanceof` syntax highlighting is broken

### ISSUE THREAD

**Issue by wenfangdu** [microsoft/TypeScript-TmLanguage#985]
**[JavaScript and TypeScript Nightly](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next) version:** 5.2.20230704

**Code**
https://github.com/wenfangdu/vite-vue-3/blob/instanceof/src/App.vue#L7-L18
![image](https://github.com/microsoft/TypeScript-TmLanguage/assets/28700378/75d3139a-af42-449f-9c84-86c3a14581f7)

**Comment by sheetalkamat** [comment]
This isnt covered by the grammar in this repo.

**Comment by wenfangdu** [comment]
@sheetalkamat Could [`TypeScript-TmLanguage`](https://github.com/microsoft/TypeScript-TmLanguage) cover this syntax? If not, which repo is responsible for this?

**Comment by douira** [comment]
If the language allows this without erroring either the compiler is wrong or the highlighting is wrong. Some component in this has the responsibility to deal with this feature, either by requiring parentheses or by highlighting the permitted syntax.
What does "This isn't covered by the grammar in this repo." mean? Does it mean such constructs are out of scope for this repo? If so, then why does vue language features not have anything to do with this, according to them?

**Comment by johnsoncodehk** [comment]
@sheetalkamat As far as I know, this problem cannot be solved in Vue's TM Language. But I found that the following changes to TypeScript-TmLanguage can solve most of the syntax issues we encountered in Vue template, I'm not sure if it's the right fix for this project.

https://github.com/johnsoncodehk/TypeScript-TmLanguage/commit/2e853d3f070319cecd77d03f3d06967ad586f532

**Comment by douira** [comment]
Since vue language tools can't fix it, the responsibility to deal with this evidently falls to the TS language grammar (this repo). Maybe you could just make a PR?

**Comment by Fuzzyma** [comment]
@sheetalkamat since you closed this and a fix seems to be available, what are the chances of reopening this and merging the fix?

**Comment by Tamas-hi** [comment]
I have followed a pretty long road from my Vue project until here to find out the source of my issue.
As I see, a lot of things have been addressed, merged, but as of today, syntax highlighting is still broken.

![Image](https://github.com/user-attachments/assets/25b36f04-4103-4b8d-bc2b-b297ce0b7c7f)

Do I miss something or this is still a problem and a new issue should be open?

**Comment by sdasun** [comment]
Same as @Tamas-hi, followed here long path from Vue.

The same issue can happen on `:class` / `:style` bindings.
<img width="651" alt="Image" src="https://github.com/user-attachments/assets/7af18f76-00b7-44da-b09b-9e34e279e67c" />
